"use client";

import { useCallback, useEffect, useState } from 'react';
import { useLocale, useTranslations } from 'next-intl';
import * as Dialog from '@radix-ui/react-dialog';
import { ThinkingOrb } from 'thinking-orbs';
import { Plus, Xmark, NavArrowRight, NetworkLeft, Check, User, Folder, Mail, Refresh } from 'iconoir-react';
import type { WorkspaceGraph } from '@/lib/setup/workspace-graph';
import { BrandMark } from './brand-mark';
import { PERSONA_PRESETS } from './agent-avatar/personas';
import { AvalAgentAvatar } from './agent-avatar/AgentAvatar';
import { SetupMemory } from './setup-memory';
import { IndependenceControls } from './independence-controls';
import { WorkspaceMembers } from './workspace-members';
import { ConnectionDialog, type Provider } from './connection-dialog';
import { IntegrationsCatalog } from './integrations-catalog';
import { PmsMatrix } from './pms-matrix';
import { usePrefersReducedMotion } from './experience';

type Graph = WorkspaceGraph & {canManage:boolean};
type Employee = WorkspaceGraph['employees'][number];
type Selection = {kind:'workspace'|'employee'|'connection'|'team'|'knowledge'|'create';id?:string};
const tabs=['overview','connections','employees','team','permissions','knowledge'] as const;

export function SetupWorkspace({onNavigateAgents}:{onNavigateAgents:()=>void}) {
 const t=useTranslations('SetupGraph'),locale=useLocale(),reduced=usePrefersReducedMotion();
 const [graph,setGraph]=useState<Graph|null>(null),[providers,setProviders]=useState<Provider[]>([]),[tab,setTab]=useState<string>('overview');
 const [selection,setSelection]=useState<Selection|null>(null),[connection,setConnection]=useState<Provider|null>(null),[focus,setFocus]=useState<string|null>(null);
 const [search,setSearch]=useState(''),[offset,setOffset]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[detailTab,setDetailTab]=useState('overview');
 const load=useCallback(async(signal?:AbortSignal)=>{
  try {
   const params=new URLSearchParams({search,offset:String(offset),...(focus?{employeeId:focus}:{})});
   const [r,p]=await Promise.all([fetch(`/api/setup/workspace-graph?${params}`,{signal,cache:'no-store'}),fetch('/api/integrations',{signal,cache:'no-store'})]);
   if(!r.ok)throw Error(t('loadError'));
   const data=await r.json() as Graph, catalog=await p.json() as {providers?:Provider[]};
   if(signal?.aborted)return;
   setGraph(data);setProviders(catalog.providers??[]);setError('');
  }catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:t('loadError'));}
 },[search,offset,focus,t]);
 useEffect(()=>{const c=new AbortController();queueMicrotask(()=>{if(!c.signal.aborted)void load(c.signal);});const timer=setInterval(()=>void load(c.signal),15000);const refresh=()=>void load(c.signal);window.addEventListener('focus',refresh);return()=>{c.abort();clearInterval(timer);window.removeEventListener('focus',refresh);};},[load]);
 const open=(value:Selection)=>{setSelection(value);setDetailTab('overview');if(value.kind==='employee')setFocus(value.id??null);};
 const changed=async()=>{await load();window.dispatchEvent(new Event('aval:configuration-changed'));};
 const mutate=async(url:string,method:string,body:unknown)=>{
  setBusy(true);setError('');
  try{const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as {error?:string;employee?:{id:string}};if(!r.ok)throw Error(data.error??t('saveError'));await changed();return data;}
  catch(e){setError(e instanceof Error?e.message:t('saveError'));return null;}finally{setBusy(false);}
 };
 const employee=graph?.employees.find(e=>e.id===(selection?.kind==='employee'?selection.id:focus))??graph?.selected;
 const chosenConnection=graph?.connections.find(c=>c.id===selection?.id);
 const assignments=(e:Employee)=>graph?.connections.filter(c=>e.scopes.connection?.includes(c.id))??[];
 const grant=(e:Employee,kind:string,value:string,enabled:boolean)=>mutate(`/api/agents/employees/${e.id}`,'POST',{action:enabled?'grant':'revoke',scope:{kind,value}});
 const patch=(e:Employee,body:unknown)=>mutate(`/api/agents/employees/${e.id}`,'PATCH',body);
 const nodeConnection=(c:NonNullable<Graph>['connections'][number])=><button type="button" className={`living-node living-snap${c.status==='connected'?' is-live':''}`} key={c.id} onClick={()=>open({kind:'connection',id:c.id})}><BrandMark provider={c.provider} small/><span><strong>{c.label}</strong><small>{c.account??t('workspaceConnection')}</small></span><span className={`living-status ${c.status==='connected'?'is-connected':''}`}>{t.has(`status_${c.status}`)?t(`status_${c.status}`):c.status}</span><NavArrowRight width={14}/></button>;
 const focused=focus?graph?.employees.find(e=>e.id===focus)??graph?.selected:null;
 const running=graph?.work.some(w=>w.state==='RUNNING')??false;
 const connectionNodes=(focused?assignments(focused):graph?.connections??[]).filter(c=>!graph?.channels.some(x=>x.id===c.id));
 const channelNodes=(focused?assignments(focused):graph?.channels??[]).filter(c=>graph?.channels.some(x=>x.id===c.id));
 return <div className="view-wrap living-setup">
  <header className="living-header"><div><p className="eyebrow">AVAL WORKSPACE</p><h1>{t('title')}</h1><p>{t('subtitle')}</p></div><div className="living-actions"><button type="button" className="soft-button" onClick={()=>open({kind:'create'})}><Plus width={16}/>{t('newEmployee')}</button><button type="button" className="primary-button" onClick={()=>setTab('connections')}><Plus width={16}/>{t('addConnection')}</button></div></header>
  <nav className="living-tabs" aria-label={t('title')}>{tabs.map(value=><button key={value} type="button" aria-current={tab===value?'page':undefined} onClick={()=>setTab(value)}>{t(value)}</button>)}</nav>
  {error&&<div className="living-error" role="alert">{error}<button type="button" className="text-button" onClick={()=>void load()}>{t('retry')}</button></div>}
  {!graph&&!error&&<p role="status">{t('loading')}</p>}
  {graph&&tab==='overview'&&<>
   <div className="living-canvas-heading"><span>{focused?t('accessFor',{name:focused.name}):t('workspaceMap')}</span>{focused?<button className="text-button" onClick={()=>setFocus(null)}>{t('showWorkspace')}</button>:<button className="text-button" onClick={()=>void load()}><Refresh width={13}/>{t('refresh')}</button>}</div>
   <div className="living-canvas">
    <svg className="living-flow-lines" viewBox="0 0 1200 610" preserveAspectRatio="none" aria-hidden="true">
     {channelNodes.length>0&&<><path className="living-flow-base" d="M60 190 H410 Q455 190 455 235 H530"/>{channelNodes.some(c=>c.status==='connected')&&<path className="living-flow-pulse" d="M60 190 H410 Q455 190 455 235 H530"/>}</>}
     {graph.knowledgeSources.length>0&&<><path className="living-flow-base" d="M60 315 H405 Q455 315 455 258 H530"/><path className="living-flow-pulse is-slow" d="M60 315 H405 Q455 315 455 258 H530"/></>}
     {connectionNodes.length>0&&<><path className="living-flow-base" d="M670 235 H745 Q745 190 790 190 H1140"/>{connectionNodes.some(c=>c.status==='connected')&&<path className="living-flow-pulse" d="M670 235 H745 Q745 190 790 190 H1140"/>}</>}
     {(graph.total>0||graph.humans.length>0)&&<><path className="living-flow-base" d="M600 330 V430 Q600 458 570 458 H260 M600 458 H940"/><path className="living-flow-pulse is-down" d="M600 330 V430 Q600 458 570 458 H260 M600 458 H940"/></>}
    </svg>
    <div className="living-wing living-inputs"><p className="living-caption">{t('communication')}</p>{channelNodes.slice(0,4).map(nodeConnection)}{!channelNodes.length&&<button className="living-add" onClick={()=>setTab('connections')}><Mail width={17}/>{t('connectCommunication')}<Plus width={15}/></button>}<button className={`living-node living-knowledge living-snap${graph.knowledgeSources.length?' is-live':''}`} onClick={()=>open({kind:'knowledge'})}><Folder width={20}/><span><strong>{t('knowledge')}</strong><small>{t('documentCount',{count:graph.knowledgeSources.length})}</small></span><NavArrowRight width={14}/></button></div>
    <div className="living-core"><button className="living-orb-card" onClick={()=>open(focused?{kind:'employee',id:focused.id}:{kind:'workspace'})}><span className="living-orb" data-active={running||undefined}><ThinkingOrb state="solving" size={64} speed={running?1:.55} paused={reduced} aria-label={t(running?'working':'ready')}/><span className="living-gravity-cursor" aria-hidden="true"><svg viewBox="0 0 24 30"><path d="M2 1.5v23.7l6.3-5.4 4.2 8.5 4.1-2-4.2-8.3 8-.8L2 1.5Z"/></svg></span></span><strong>{focused?.name??'Aval'}</strong><span>{focused?.role??t('teamSummary',{employees:graph.total,connections:graph.connections.filter(c=>c.status==='connected').length})}</span><span className="living-core-link">{t('configure')}<NavArrowRight width={14}/></span></button></div>
    <div className="living-wing living-systems"><p className="living-caption">{t('systems')}</p>{connectionNodes.slice(0,4).map(nodeConnection)}{connectionNodes.length>4&&<button className="text-button" onClick={()=>setTab('connections')}>{t('viewAll',{count:connectionNodes.length})}</button>}<button className="living-add" onClick={()=>setTab('connections')}><NetworkLeft width={18}/>{t('addConnection')}<Plus width={15}/></button></div>
    <div className="living-roster living-snap"><div className="living-roster-heading"><span>{t('employees')} <small>{graph.total}</small></span><button className="text-button" onClick={()=>open({kind:'create'})}><Plus width={14}/>{t('newEmployee')}</button></div><div className="living-people">{graph.employees.slice(0,5).map(e=><button className="living-person living-snap" key={e.id} onClick={()=>{setFocus(e.id);open({kind:'employee',id:e.id});}}><AvalAgentAvatar personaId={e.id} shape={PERSONA_PRESETS.general.shape} theme={PERSONA_PRESETS.general.theme} size={38}/><span><strong>{e.name}</strong><small>{e.role}</small><small>{t(`status_${e.status}`)} · {t('workCount',{count:e.openWork})}</small></span><NavArrowRight width={14}/></button>)}{!graph.total&&<button className="living-add" onClick={()=>open({kind:'create'})}>{t('createFirst')}<Plus width={15}/></button>}{graph.total>5&&<button className="living-add" onClick={()=>setTab('employees')}>{t('viewAll',{count:graph.total})}<NavArrowRight width={14}/></button>}</div><div className="living-human-row"><button className="text-button" onClick={()=>open({kind:'team'})}><User width={15}/>{t('team')} · {graph.humans.length}</button>{graph.humans.slice(0,3).map(h=><button key={h.userId} className="living-human living-snap" onClick={()=>open({kind:'team',id:h.userId})}>{h.displayName||h.email}<small>{h.role}</small></button>)}<button className="text-button" onClick={()=>open({kind:'team'})}><Plus width={14}/>{t('invite')}</button></div></div>
   </div>
   {focused&&<section className="living-edge-panel"><h2>{t('accessFor',{name:focused.name})}</h2>{graph.edges.filter(e=>e.from===focused.id).map(edge=><button className="living-edge" key={edge.id} onClick={()=>open({kind:'connection',id:edge.to})}><span>{focused.name} → {graph.connections.find(c=>c.id===edge.to)?.label??t('unavailable')}</span><small>{edge.active?t('assigned'):t('inactive')} · {t(edge.autonomy)} · {t('capabilityCount',{count:edge.capabilities.length})}</small><NavArrowRight width={16}/></button>)}<button className="text-button" onClick={()=>{open({kind:'employee',id:focused.id});setDetailTab('access');}}>{t('editAccess')}</button></section>}
   {!!graph.attention.length&&<section className="living-attention"><h2>{t('attention')} <small>{graph.attention.length}</small></h2>{graph.attention.slice(0,4).map(a=><button key={`${a.kind}:${a.id}`} onClick={()=>a.kind==='work'?onNavigateAgents():open({kind:a.kind as 'employee'|'connection',id:a.id})}><span className="living-attention-dot"/><span>{a.label}<small>{t.has(`status_${a.state}`)?t(`status_${a.state}`):a.state.replaceAll('_',' ')}</small></span><NavArrowRight width={15}/></button>)}</section>}
  </>}
  {tab==='connections'&&<IntegrationsCatalog providers={providers} loading={!providers.length} onOpen={id=>setConnection(providers.find(p=>p.id===id)??null)}/>}
  {tab==='employees'&&<><div className="living-actions"><input aria-label={t('searchEmployees')} placeholder={t('searchEmployees')} value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/><button className="primary-button" onClick={()=>open({kind:'create'})}>{t('newEmployee')}</button></div><div className="living-directory">{graph?.employees.map(e=><button className="living-person" key={e.id} onClick={()=>open({kind:'employee',id:e.id})}><AvalAgentAvatar personaId={e.id} shape={PERSONA_PRESETS.general.shape} theme={PERSONA_PRESETS.general.theme} size={42}/><span><strong>{e.name}</strong><small>{e.role} · {t(e.autonomyMode)}</small><small>{t('capabilityCount',{count:e.tools.length})}</small></span><NavArrowRight width={16}/></button>)}</div><div className="living-actions"><button className="soft-button" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-24))}>{t('previous')}</button><button className="soft-button" disabled={(graph?.employees.length??0)<24} onClick={()=>setOffset(offset+24)}>{t('next')}</button></div></>}
  {tab==='team'&&<WorkspaceMembers/>}
  {tab==='permissions'&&<><IndependenceControls/><PmsMatrix/><section className="living-edge-panel"><h2>{t('approvalAuthority')}</h2><p>{t('approvalExplanation')}</p>{graph?.humans.filter(h=>h.role!=='member').map(h=><button className="living-edge" key={h.userId} onClick={()=>open({kind:'team',id:h.userId})}>{h.displayName||h.email}<span>{h.role}</span><NavArrowRight width={15}/></button>)}</section></>}
  {tab==='knowledge'&&<Knowledge graph={graph} locale={locale}/>}
  <Dialog.Root open={!!selection} onOpenChange={value=>{if(!value){setSelection(null);void changed();}}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay living-overlay"/><Dialog.Content className="living-inspector"><div className="living-inspector-heading"><div><p className="eyebrow">{t('title')}</p><Dialog.Title>{selection?.kind==='employee'?employee?.name:selection?.kind==='connection'?chosenConnection?.label:selection?.kind==='workspace'?'Aval':selection?.kind==='create'?t('newEmployee'):selection?.kind==='team'?t('team'):t('knowledge')}</Dialog.Title></div><Dialog.Close className="icon-button" aria-label={t('close')}><Xmark width={21}/></Dialog.Close></div><Dialog.Description className="sr-only">{t('detailDescription')}</Dialog.Description>{error&&<p role="alert" className="living-error">{error}</p>}
   {selection?.kind==='workspace'&&<><nav className="living-tabs">{['overview','memory','independence'].map(v=><button key={v} aria-current={detailTab===v?'page':undefined} onClick={()=>setDetailTab(v)}>{t(v)}</button>)}</nav>{detailTab==='memory'?<SetupMemory/>:detailTab==='independence'?<IndependenceControls/>:<div className="living-summary"><p>{t('teamSummary',{employees:graph?.total??0,connections:graph?.connections.length??0})}</p><button className="living-edge" onClick={()=>setDetailTab('memory')}>{t('memory')}<small>{t('memoryCount',{count:graph?.memory.length??0})}</small><NavArrowRight width={16}/></button><button className="living-edge" onClick={()=>setDetailTab('independence')}>{t('independence')}<NavArrowRight width={16}/></button><button className="living-edge" onClick={()=>{setSelection(null);setTab('permissions');}}>{t('approvalAuthority')}<NavArrowRight width={16}/></button></div>}</>}
   {selection?.kind==='employee'&&employee&&<><nav className="living-tabs">{['overview','access','expertise','memory'].map(v=><button key={v} aria-current={detailTab===v?'page':undefined} onClick={()=>setDetailTab(v)}>{t(v)}</button>)}</nav>{detailTab==='overview'&&<><p>{employee.role}</p><p>{employee.objective}</p><div className="living-actions">{employee.status!=='archived'&&<button className="soft-button" disabled={busy||!graph?.canManage} onClick={()=>void mutate(`/api/agents/employees/${employee.id}`,'POST',{action:employee.status==='active'?'pause':employee.status==='draft'?'activate':'resume'})}>{t(employee.status==='active'?'pause':'activate')}</button>}<span className="living-status">{t(`status_${employee.status}`)}</span></div><label className="living-field">{t('independence')}<select value={employee.autonomyMode} disabled={busy||!graph?.canManage} onChange={e=>void patch(employee,{autonomyMode:e.target.value})}>{['supervised','assisted','autonomous'].map(v=><option key={v} value={v}>{t(v)}</option>)}</select></label><p className="living-hint">{t('autonomyHint')}</p><button className="primary-button" onClick={()=>{setSelection(null);window.location.assign(`/${locale}?view=agents&agent=${employee.id}`);}}>{t('openWork')}<NavArrowRight width={15}/></button></>}
    {detailTab==='access'&&<><h3>{t('connections')}</h3>{graph?.connections.map(c=><label className="living-toggle" key={c.id}><input type="checkbox" disabled={busy||!graph.canManage} checked={employee.scopes.connection?.includes(c.id)??false} onChange={e=>void grant(employee,'connection',c.id,e.target.checked)}/><span>{c.label}<small>{c.account??c.status}</small></span></label>)}<label className="living-toggle"><input type="checkbox" checked={employee.mayCommunicateExternally} disabled={busy||!graph?.canManage} onChange={e=>void patch(employee,{mayCommunicateExternally:e.target.checked})}/>{t('externalCommunication')}</label><h3>{t('capabilities')}</h3><p className="living-hint">{t('capabilityHint')}</p>{graph?.capabilities.map(c=><label className="living-toggle" key={c.name}><input type="checkbox" disabled={busy||!graph.canManage} checked={employee.scopes.capability?.includes(c.name)??false} onChange={e=>void grant(employee,'capability',c.name,e.target.checked)}/><span>{c.summary}<small>{employee.tools.includes(c.name)?t('available'):employee.scopes.capability?.includes(c.name)?t('unavailable'):t('notGranted')} · {c.risk}</small></span>{employee.tools.includes(c.name)&&<Check width={14}/>}</label>)}</>}
    {detailTab==='memory'&&<EmployeeInstructions employee={employee} disabled={busy||!graph?.canManage} onSave={instructions=>patch(employee,{instructions})}/>}
    {detailTab==='expertise'&&graph?.expertise.map(x=><label className="living-toggle" key={x.id}><input type="checkbox" checked={employee.expertise.some(e=>e.id===x.id)} disabled={busy||!graph.canManage} onChange={e=>void mutate(`/api/agents/employees/${employee.id}`,'POST',{action:e.target.checked?'grant_expertise':'revoke_expertise',expertiseId:x.id})}/><span>{x.name}<small>{x.description}</small></span></label>)}</>}
   {selection?.kind==='connection'&&chosenConnection&&<><p>{chosenConnection.account??chosenConnection.label} · {chosenConnection.status}</p><p className="living-hint">{chosenConnection.authMode}</p><button className="primary-button" onClick={()=>{setSelection(null);setConnection(providers.find(p=>p.id===chosenConnection.provider)??null);setTab('connections');}}>{t('manageConnection')}</button><h3>{t('reportingAccess')}</h3><div className="living-chips">{chosenConnection.reportingCapabilities.map(c=><span key={c}>{c}</span>)}</div>{chosenConnection.matrix&&<><h3>{t('providerCapabilities')}</h3>{Object.entries(chosenConnection.matrix).map(([name,value])=><div className="living-edge" key={name}><span>{name}</span><small>{value.state}</small></div>)}</>}<h3>{t('usedBy')}</h3>{graph?.employees.map(e=><label className="living-toggle" key={e.id}><input type="checkbox" disabled={busy||!graph.canManage} checked={e.scopes.connection?.includes(chosenConnection.id)??false} onChange={event=>void grant(e,'connection',chosenConnection.id,event.target.checked)}/><span>{e.name}<small>{e.role}</small></span></label>)}<p className="living-hint">{t('assignmentHint')}</p></>}
   {selection?.kind==='team'&&<WorkspaceMembers/>}{selection?.kind==='knowledge'&&<Knowledge graph={graph} locale={locale}/>}
   {selection?.kind==='create'&&<NewEmployee templates={graph?.templates??[]} disabled={busy||!graph?.canManage} onCreate={async body=>{const data=await mutate('/api/agents/employees','POST',body);if(data?.employee){setFocus(data.employee.id);open({kind:'employee',id:data.employee.id});}}}/>}
  </Dialog.Content></Dialog.Portal></Dialog.Root>
  {connection&&<ConnectionDialog provider={connection} onClose={()=>setConnection(null)} onRefresh={()=>void changed()}/>}
 </div>;
}
function EmployeeInstructions({employee,disabled,onSave}:{employee:Employee;disabled:boolean;onSave:(value:string)=>Promise<unknown>}) {const t=useTranslations('SetupGraph');const [value,setValue]=useState(employee.instructions??'');return <form onSubmit={e=>{e.preventDefault();void onSave(value);}}><label className="living-field">{t('instructions')}<textarea rows={8} maxLength={4000} value={value} onChange={e=>setValue(e.target.value)} disabled={disabled}/></label><p className="living-hint">{t('instructionsHint')}</p><button className="primary-button" disabled={disabled}>{t('save')}</button></form>;}
function NewEmployee({templates,disabled,onCreate}:{templates:WorkspaceGraph['templates'];disabled:boolean;onCreate:(body:unknown)=>Promise<void>}) {const t=useTranslations('SetupGraph');const [role,setRole]=useState(''),[objective,setObjective]=useState('');return <form className="living-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void onCreate({name:d.get('name'),role,objective});}}><label className="living-field">{t('startFrom')}<select defaultValue="" onChange={e=>{const template=templates.find(x=>x.slug===e.target.value);setRole(template?.role??'');setObjective(template?.objective??'');}}><option value="">{t('scratch')}</option>{templates.map(x=><option key={x.slug} value={x.slug}>{x.name}</option>)}</select></label><label className="living-field">{t('name')}<input name="name" required maxLength={120}/></label><label className="living-field">{t('role')}<input value={role} onChange={e=>setRole(e.target.value)} required maxLength={120}/></label><label className="living-field">{t('objective')}<textarea value={objective} onChange={e=>setObjective(e.target.value)} rows={4} maxLength={4000}/></label><p className="living-hint">{t('creationHint')}</p><button className="primary-button" disabled={disabled}>{t('create')}</button></form>;}

function Knowledge({graph,locale}:{graph:Graph|null;locale:string}) {const t=useTranslations('SetupGraph');return <section className="living-summary"><p>{t('knowledgeHint')}</p><a className="primary-button" href={`/${locale}?view=documents`}>{t('manageDocuments')}</a>{graph?.knowledgeSources.map(d=><a className="living-edge" href={`/${locale}?view=documents`} key={d.id}><Folder width={17}/><span>{d.title}<small>{d.kind}</small></span><NavArrowRight width={15}/></a>)}</section>;}
