/** Affordable Housing & Subsidy Operations — 12 Aval Specialists, coordinated by Affordable Housing & Subsidy Operations Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "affordable.program-eligibility-intake",
    name: "Program Eligibility Intake",
    domain: "affordable",
    boundary: "Collects the household composition, income sources, assets and program-specific items an applicant for a subsidized or income-restricted unit must provide, and marks each checklist item received, missing or not applicable. Stops at a complete intake file queued for authorized certification review; it does not determine eligibility.",
    notThis: { specialist: "screening.application-completeness", because: "Application completeness checks a rental application against the screening criteria; this gathers the household and income data a housing program requires for certification." },
    triggers: ["affordable application", "income restricted", "tax credit unit", "household composition", "program intake"],
    inputs: ["application", "program type and checklist version", "household declarations"],
    outputs: ["intake checklist with status and source per item", "missing-item list", "queue entry for certification review"],
    capabilities: ["application.read", "affordable.read", "document.read", "document.extract"],
    execution: "expertise",
    completion: { doneWhen: "Every item the program checklist requires is marked received, missing or not applicable with its source, and the file is queued for authorized review.", notDoneWhen: "Documents were gathered, but the household was treated as eligible without an authorized person's determination." },
    forbidden: ["tell an applicant they qualify or do not qualify", "ask about disability or another protected trait beyond what the program's written rules require to be verified"],
    approvals: [],
    collaborators: ["affordable.income-and-asset-document-collection", "affordable.rent-calculation-support", "affordable.utility-allowance-tracking", "screening.application-completeness"],
  },
  {
    id: "affordable.voucher-and-pha-coordination",
    name: "Voucher & PHA Coordination",
    domain: "affordable",
    boundary: "Handles the paperwork and correspondence with a public housing agency for a voucher tenancy: request for tenancy approval, rent reasonableness, PHA inspection scheduling, HAP contract status, rent and household change notices. Stops at prepared submissions and a tracked PHA status; payment variances go elsewhere.",
    notThis: { specialist: "affordable.subsidy-payment-exception", because: "Subsidy payment exception explains why a housing assistance payment differs from what was expected; this prepares and tracks the submissions that establish and change the contract." },
    triggers: ["voucher", "pha", "rfta", "hap contract", "housing authority", "section 8"],
    inputs: ["voucher holder's tenancy details", "PHA forms and requirements", "PHA correspondence"],
    outputs: ["prepared PHA submissions", "PHA status per tenancy with next action and due date"],
    capabilities: ["voucher.read", "affordable.read", "lease.read", "communication.read", "document.read"],
    execution: "expertise",
    completion: { doneWhen: "Each PHA submission has a sent date, the PHA's acknowledgement and the next required action with its due date.", notDoneWhen: "The request was sent, but the tenancy or subsidy was treated as approved before the executed HAP contract was on file." },
    forbidden: ["treat a voucher holder's application differently from other applicants", "represent a PHA decision the PHA has not issued in writing"],
    approvals: ["submission to the PHA"],
    collaborators: ["affordable.nspire-and-inspection-readiness", "affordable.subsidy-payment-exception", "lease-admin.lease-draft-assembly", "receivables.rent-charge-schedule"],
  },
  {
    id: "affordable.recertification-calendar",
    name: "Recertification Calendar",
    domain: "affordable",
    boundary: "Computes each household's annual recertification date and the dated notice sequence its program requires, and queues each notice and outreach step as it falls due. Stops at dated alerts and queued outreach; it does not collect documents or decide whether an interim change is needed.",
    notThis: { specialist: "affordable.interim-recertification", because: "Interim recertification reacts to a reported mid-year change; the calendar runs the fixed annual cycle from each household's anniversary." },
    triggers: ["recertification due", "annual recert", "recert notice", "anniversary date", "certification expiring"],
    inputs: ["household certification history", "program and its notice schedule version", "lease dates"],
    outputs: ["next recertification date per household", "dated notice schedule", "queued outreach tasks"],
    capabilities: ["affordable.read", "lease.read", "resident.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Each household has its next recertification date and every program-required notice dated, and each notice now due has been prepared and handed to a person.", notDoneWhen: "The due date is on the calendar, but a required advance notice was not issued on time." },
    forbidden: ["use one program's notice intervals for every household", "move a recertification date to fit staff capacity"],
    approvals: [],
    collaborators: ["affordable.income-and-asset-document-collection", "affordable.hud-packet-preparation", "risk-compliance.regulatory-calendar"],
  },
  {
    id: "affordable.income-and-asset-document-collection",
    name: "Income & Asset Document Collection",
    domain: "affordable",
    boundary: "Requests and follows up on household documents and third-party verifications (pay stubs, benefit letters, account statements), and checks each for household member, date window, legibility and program acceptability. Stops at a validated document set with gaps listed; it does not compute income.",
    notThis: { specialist: "affordable.rent-calculation-support", because: "Rent calculation turns validated figures into rent; collection obtains and validates the evidence those figures come from." },
    triggers: ["pay stubs", "verification of income", "bank statement", "benefit letter", "missing documents", "third-party verification"],
    inputs: ["declared income sources and assets", "program document rules", "received documents"],
    outputs: ["validated document set per income source and asset", "gap list and follow-up messages"],
    capabilities: ["document.read", "document.extract", "affordable.read", "communication.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Every declared income source and asset has a document within the program's age limit or a recorded third-party verification attempt, and remaining gaps are listed.", notDoneWhen: "Documents were requested or uploaded but never checked for date, household member and program acceptability." },
    forbidden: ["treat a resident's statement of income as verified", "keep or forward full account or benefit numbers beyond what verification needs"],
    approvals: [],
    collaborators: ["affordable.program-eligibility-intake", "affordable.rent-calculation-support", "affordable.recertification-calendar", "data-integrations.document-ingestion"],
  },
  {
    id: "affordable.interim-recertification",
    name: "Interim Recertification",
    domain: "affordable",
    boundary: "Takes a reported mid-year change (income change, member added or leaving) to a recorded program-rule outcome: interim required, permitted or not; where required, gathers evidence, triggers recalculation and sets the effective date. Stops at a prepared interim in authorized review.",
    notThis: { specialist: "affordable.recertification-calendar", because: "The calendar runs the scheduled annual cycle; interim recertification starts from a change the household or a record reports between anniversaries." },
    triggers: ["income changed", "lost job", "new household member", "moved out of household", "interim"],
    inputs: ["reported change and its source", "program interim rules version", "current certification"],
    outputs: ["program-rule outcome for the change", "prepared interim with effective date"],
    capabilities: ["affordable.read", "recertification.prepare", "document.read", "communication.read"],
    execution: "child_run",
    completion: { doneWhen: "The change has a recorded program-rule outcome and, where required, a prepared interim with its effective date sits in authorized review.", notDoneWhen: "The change was noted in a message, but whether an interim is required was never determined." },
    forbidden: ["change the resident's rent before the interim is approved", "hold a reported income decrease until the annual recertification when the program requires it be processed"],
    approvals: ["interim certification"],
    collaborators: ["affordable.income-and-asset-document-collection", "affordable.rent-calculation-support", "affordable.hud-packet-preparation"],
  },
  {
    id: "affordable.rent-calculation-support",
    name: "Rent Calculation Support",
    domain: "affordable",
    boundary: "Computes annual and adjusted income, tenant payment and rent-limit checks from validated inputs and the program parameters in effect (income limits, rent limits, deductions, utility allowance), producing a reproducible worksheet. Stops at the worksheet for authorized review.",
    notThis: { specialist: "affordable.utility-allowance-tracking", because: "Utility allowance tracking supplies the allowance in effect for the unit; rent calculation consumes it with every other input to produce the rent." },
    triggers: ["calculate rent", "tenant rent", "adjusted income", "rent limit", "ttp"],
    inputs: ["validated income and asset figures", "program parameter tables with effective dates", "applicable utility allowance"],
    outputs: ["calculation worksheet with each input's source", "resulting rent and limit checks"],
    capabilities: ["affordable.read", "recertification.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "The worksheet lists each input with its source document and each parameter version, and reproduces the rent from those recorded inputs.", notDoneWhen: "A rent was produced, but an input came from an unvalidated document or a parameter table outside its effective period." },
    forbidden: ["estimate a missing input", "round or adjust outside the program's stated rules"],
    approvals: ["calculated rent within the certification"],
    collaborators: ["affordable.income-and-asset-document-collection", "affordable.utility-allowance-tracking", "affordable.hud-packet-preparation"],
  },
  {
    id: "affordable.hud-packet-preparation",
    name: "HUD Packet Preparation",
    domain: "affordable",
    boundary: "Assembles the current certification packet (certification form data, household signatures, verifications, lease and addenda) and checks its figures match the reviewed worksheet. Stops when the packet is in the authorized reviewer's queue; transmission to HUD or a contract administrator follows that review.",
    notThis: { specialist: "affordable.compliance-audit-preparation", because: "Audit preparation looks back over existing files for an auditor; packet preparation builds the certification now due." },
    triggers: ["50059", "certification packet", "tracs", "move-in certification", "submit certification"],
    inputs: ["reviewed calculation worksheet", "signed household certifications", "verifications and lease documents"],
    outputs: ["certification packet with completeness checklist", "queue entry for authorized review"],
    capabilities: ["recertification.prepare", "affordable.read", "document.read", "lease.read"],
    execution: "expertise",
    completion: { doneWhen: "Every required form and signature is present, the figures match the reviewed worksheet, and the packet is in the authorized reviewer's queue.", notDoneWhen: "The packet was assembled, but household signatures are missing or it went out without authorized review." },
    forbidden: ["sign or date a certification on behalf of a household member or the owner's agent", "change a figure to agree with a prior certification without a documented basis"],
    approvals: ["certification packet before transmission"],
    collaborators: ["affordable.rent-calculation-support", "affordable.income-and-asset-document-collection", "affordable.compliance-audit-preparation", "lease-admin.lease-addendum-preparation"],
  },
  {
    id: "affordable.nspire-and-inspection-readiness",
    name: "NSPIRE & Inspection Readiness",
    domain: "affordable",
    boundary: "Prepares a property for a scored program inspection (NSPIRE, PHA unit inspection): measures open deficiencies against the applicable standard, arranges pre-inspections, and produces correction work items dated before the inspection. Stops at a verified readiness list; the inspection itself belongs to the program.",
    notThis: { specialist: "inspections.periodic-property-inspection", because: "Periodic inspection is the workspace's own condition check; readiness measures the property against the program's scored standard ahead of a set inspection date." },
    triggers: ["nspire", "reac", "pha inspection", "hqs", "inspection readiness", "life-threatening deficiency"],
    inputs: ["inspection date and standard version", "open deficiencies and work orders", "pre-inspection findings"],
    outputs: ["readiness list by deficiency", "correction work items with dates", "verification status per correction"],
    capabilities: ["nspire.read", "inspection.read", "inspection.prepare", "work_order.read", "maintenance.read"],
    execution: "expertise",
    completion: { doneWhen: "Every deficiency against the standard has a correction verified before the inspection date, and life-threatening items were escalated within the standard's timeline.", notDoneWhen: "Work orders exist, but corrections were not verified before the inspection." },
    forbidden: ["mark a deficiency corrected on a vendor's word alone", "reschedule an inspection with the program without authorization"],
    approvals: [],
    collaborators: ["inspections.inspection-deficiency-triage", "maintenance.work-order-creation", "maintenance.completion-verification", "affordable.voucher-and-pha-coordination"],
  },
  {
    id: "affordable.subsidy-payment-exception",
    name: "Subsidy Payment Exception",
    domain: "affordable",
    boundary: "Investigates a difference between the certified subsidy and what was received (missing, partial, abated, retroactive) and traces its cause: certification not processed, abatement after a failed inspection, agency error. Stops at an evidenced cause and a prepared correction request; it does not bill the resident.",
    notThis: { specialist: "receivables.payment-posting-and-reconciliation", because: "Payment posting records and reconciles what was received; this explains why the subsidy portion differs from the certified amount." },
    triggers: ["hap short", "subsidy missing", "abatement", "hap variance", "retroactive adjustment"],
    inputs: ["certified subsidy amounts", "payment and remittance detail", "agency correspondence", "inspection status"],
    outputs: ["variance with traced cause and evidence", "prepared correction request"],
    capabilities: ["voucher.read", "affordable.read", "payment.read", "ledger.read"],
    execution: "expertise",
    completion: { doneWhen: "Each variance has an evidenced cause and either a prepared correction request or a record that the adjustment is correct.", notDoneWhen: "The shortfall was moved to the resident's balance before its cause was established." },
    forbidden: ["charge the resident for an unpaid subsidy portion", "adjust the ledger to hide a variance"],
    approvals: ["correction request to the agency or contract administrator"],
    collaborators: ["affordable.voucher-and-pha-coordination", "receivables.payment-posting-and-reconciliation", "affordable.hud-packet-preparation", "finance.general-ledger-review"],
  },
  {
    id: "affordable.utility-allowance-tracking",
    name: "Utility Allowance Tracking",
    domain: "affordable",
    boundary: "Keeps the utility allowance schedule in effect for each property and unit type, with its adopted, effective and required-update dates, and flags households needing recalculation when a schedule changes or goes stale. Stops at the applicable allowance per unit.",
    notThis: { specialist: "utilities.resident-utility-billing", because: "Resident utility billing charges residents for usage; the allowance is a program credit applied inside the rent calculation." },
    triggers: ["utility allowance", "ua schedule", "allowance update", "new ua"],
    inputs: ["adopted allowance schedules with dates", "unit types and utility responsibilities"],
    outputs: ["applicable allowance per unit", "households flagged for recalculation"],
    capabilities: ["affordable.read", "utility.read", "unit.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each unit has its allowance from a schedule whose effective and review dates are recorded, and households affected by a new schedule are flagged.", notDoneWhen: "The allowance on file comes from a schedule past its update date and nobody was alerted." },
    forbidden: ["apply one property's or agency's schedule to another", "estimate an allowance with no adopted schedule"],
    approvals: [],
    collaborators: ["affordable.rent-calculation-support", "affordable.recertification-calendar", "utilities.utility-bill-audit"],
  },
  {
    id: "affordable.compliance-audit-preparation",
    name: "Compliance Audit Preparation",
    domain: "affordable",
    boundary: "Prepares for a management review, agency file audit or investor compliance review: samples tenant files, checks completeness and calculation consistency, tracks each finding to correction, and assembles the response. Stops at a response package approved by the compliance owner.",
    notThis: { specialist: "affordable.hud-packet-preparation", because: "Packet preparation builds the certification due now; audit preparation examines past files as an auditor will and corrects what it finds." },
    triggers: ["file audit", "management review", "mor", "compliance review", "8823", "auditor request"],
    inputs: ["audit notice and file list", "tenant files", "prior findings"],
    outputs: ["file checklist results", "findings tracker with owners and dates", "response package"],
    capabilities: ["affordable.read", "document.read", "compliance.read", "nspire.read", "report.prepare"],
    execution: "child_run",
    completion: { doneWhen: "Each requested or sampled file has a checklist result, each finding has an owner and date, and the compliance owner approved the response package.", notDoneWhen: "Files were assembled for the auditor, but findings from the pre-audit review were neither corrected nor disclosed." },
    forbidden: ["backdate, create or alter a document to close an audit gap", "withhold a file the auditor requested"],
    approvals: ["response package to the auditor"],
    collaborators: ["affordable.hud-packet-preparation", "affordable.nspire-and-inspection-readiness", "data-integrations.audit-and-provenance", "risk-compliance.regulatory-calendar"],
  },
  {
    id: "affordable.affordable-housing-accommodation-support",
    name: "Affordable Housing Accommodation Support",
    domain: "affordable",
    boundary: "Adds the subsidy-program layer to an accommodation in a subsidized property: live-in aide verification, accessible-unit transfer lists, agency approvals such as payment standard exceptions, and household composition updates. Prepares that program paperwork after the authorized decision; it neither decides nor runs the request.",
    notThis: { specialist: "risk-compliance.reasonable-accommodation-workflow", because: "The workflow carries the request to an authorized decision; this prepares only what the housing program needs once that decision exists, and intake is a third job again." },
    triggers: ["live-in aide", "accessible unit transfer", "payment standard exception", "504", "accommodation in subsidized unit"],
    inputs: ["recorded accommodation decision", "program rules", "household certification"],
    outputs: ["program submissions and household updates prepared for the authorized person", "status per program step"],
    capabilities: ["accommodation.read", "affordable.read", "voucher.read", "fair_housing.review"],
    execution: "expertise",
    completion: { doneWhen: "Every program step the recorded decision needs is prepared, handed to the authorized person and tracked to the program's response.", notDoneWhen: "The accommodation was approved, but the program paperwork it depends on was never submitted." },
    forbidden: ["store medical detail in the tenant file beyond the verification the program requires", "count a live-in aide in household income or eligibility unless the program rules say so"],
    approvals: ["program submissions arising from an accommodation decision"],
    collaborators: ["risk-compliance.reasonable-accommodation-workflow", "resident-experience.accommodation-request-intake", "affordable.voucher-and-pha-coordination", "affordable.interim-recertification"],
  },
];
