/** Commercial Property Operations — 10 Aval Specialists, coordinated by Commercial Property Operations Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "commercial.commercial-lease-abstract",
    name: "Commercial Lease Abstract",
    domain: "commercial",
    boundary: "Abstracts a commercial lease and its amendments in order: premises and area, pro rata share, base rent, escalation type, CAM, tax and insurance recovery terms (base year, stop, gross-up, caps, exclusions), options, co-tenancy, use and assignment, each cited to clause and amendment. Stops at the abstract.",
    notThis: { specialist: "lease-admin.lease-abstract", because: "The residential abstract carries rent, deposit and notice terms; this carries the recovery, cap, exclusion and option terms that CAM, billing and option tracking compute from." },
    triggers: ["commercial lease", "abstract", "pro rata share", "cam terms", "amendment", "base year"],
    inputs: ["executed commercial lease", "amendments in date order", "measured area records"],
    outputs: ["commercial abstract with clause and amendment citations", "ambiguities flagged for review"],
    capabilities: ["commercial.read", "lease.read", "document.read", "document.extract"],
    execution: "child_run",
    completion: { doneWhen: "Every field, including caps, exclusions, gross-up and base year, has a value or explicit 'not stated' with clause and amendment citation, and the amendment chain is applied in order.", notDoneWhen: "The base lease was abstracted, but a later amendment changing rent, recoveries or options was not applied." },
    forbidden: ["resolve an ambiguous recovery or cap clause into one value without flagging it", "fill a field from market convention"],
    approvals: ["abstract before it drives billing"],
    collaborators: ["commercial.cam-estimate", "commercial.cam-reconciliation", "commercial.commercial-rent-escalation", "commercial.commercial-option-and-notice-date", "data-integrations.document-ingestion"],
  },
  {
    id: "commercial.cam-estimate",
    name: "CAM Estimate",
    domain: "commercial",
    boundary: "Computes each tenant's monthly CAM, tax and insurance estimates for the coming year from the approved budget, abstracted pro rata shares, base year or stop, caps, exclusions and gross-up. Stops at an estimate schedule for review; year-end true-up is reconciliation's job.",
    notThis: { specialist: "commercial.cam-reconciliation", because: "The estimate sets monthly charges in advance from the budget; reconciliation compares a closed year's actuals with what was billed." },
    triggers: ["cam estimate", "opex estimate", "budget year", "monthly cam", "estimated recoveries"],
    inputs: ["approved operating budget", "abstracted recovery terms per tenant"],
    outputs: ["estimate schedule per tenant with clause for each cap and exclusion applied"],
    capabilities: ["commercial.read", "cam.prepare", "budget.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each tenant's estimate traces to budget lines, its share and the clause for every cap, exclusion and gross-up applied, and the schedule is in review.", notDoneWhen: "Estimates were computed from a budget that is not the approved version, or a tenant's cap was not applied." },
    forbidden: ["include a cost the tenant's lease excludes", "use a share or base year not taken from the abstract"],
    approvals: ["estimate schedule before billing"],
    collaborators: ["commercial.commercial-lease-abstract", "commercial.commercial-tenant-billing", "finance.budget-vs-actual"],
  },
  {
    id: "commercial.cam-reconciliation",
    name: "CAM Reconciliation",
    domain: "commercial",
    boundary: "Reconciles a closed year: expense pools from the general ledger, exclusions and caps, gross-up, allocation by share, estimates billed against actual, and a tenant statement with backup. Stops at reviewed statements; billing the balance is a separate step.",
    notThis: { specialist: "commercial.cam-estimate", because: "The estimate works forward from a budget; reconciliation works backward from closed actuals and produces the true-up each tenant owes or is owed." },
    triggers: ["cam reconciliation", "year-end true-up", "recovery reconciliation", "tenant statement", "expense pool"],
    inputs: ["closed-period general ledger", "abstracted recovery terms", "estimates billed"],
    outputs: ["reconciliation per tenant with clause citations", "tenant statements with backup"],
    capabilities: ["commercial.read", "cam.prepare", "gl.read", "accounting.read", "report.prepare"],
    execution: "child_run",
    completion: { doneWhen: "Each tenant's statement ties to the closed ledger, shows every exclusion and cap with its clause, and has been approved by the reviewer.", notDoneWhen: "Statements were generated from an open period, or a statement was issued before review." },
    forbidden: ["recover a capital cost the lease does not allow to be passed through", "net a tenant's credit against another charge without review"],
    approvals: ["reconciliation statements before issue"],
    collaborators: ["commercial.commercial-lease-abstract", "commercial.commercial-tenant-billing", "finance.month-end-close-coordination", "finance.general-ledger-review"],
  },
  {
    id: "commercial.commercial-rent-escalation",
    name: "Commercial Rent Escalation",
    domain: "commercial",
    boundary: "Computes scheduled base-rent changes under a commercial lease: fixed steps, percentage increases and index adjustments using the named series, lookback month, floor and cap; flags fair-market resets for negotiation. Stops at a new-rent schedule for review compared with billed rent.",
    notThis: { specialist: "lease-admin.rent-escalation-tracking", because: "Residential escalation tracks steps and concession burn-off written in a residential lease; this handles index formulas, floors, caps and market resets commercial leases use." },
    triggers: ["cpi adjustment", "rent bump", "escalation", "index increase", "fair market reset"],
    inputs: ["abstracted escalation clause", "published index values", "current billed rent"],
    outputs: ["new rent with effective date and index value used", "variance against billed rent"],
    capabilities: ["commercial.read", "lease.read", "charge.read", "market.public.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each escalation has an amount, effective date, the index value and publication used where indexed and its clause, and variances from billed rent are listed.", notDoneWhen: "The new rent was computed with a different index month, floor or cap from the clause." },
    forbidden: ["substitute a different index series or month from the one the lease names", "set a fair-market reset amount"],
    approvals: ["rent change before billing"],
    collaborators: ["commercial.commercial-lease-abstract", "commercial.commercial-tenant-billing", "commercial.commercial-option-and-notice-date"],
  },
  {
    id: "commercial.commercial-tenant-billing",
    name: "Commercial Tenant Billing",
    domain: "commercial",
    boundary: "Prepares commercial tenant charges (base rent, CAM estimates, reconciliation true-ups, percentage rent from sales reports, utility and after-hours service recoveries), each tied to its approved source. Stops at a charge batch for approval before posting.",
    notThis: { specialist: "receivables.rent-charge-schedule", because: "The residential charge schedule maintains flat recurring rent and fees; commercial billing assembles charges from several approved computations, each of which must be approved before it bills." },
    triggers: ["tenant billing", "percentage rent", "true-up billing", "after-hours hvac", "commercial invoice"],
    inputs: ["approved estimates and reconciliations", "escalation schedule", "tenant sales reports", "service usage records"],
    outputs: ["charge batch with a source per charge", "items held for missing approval"],
    capabilities: ["charge.prepare", "charge.read", "invoice.prepare", "commercial.read"],
    execution: "expertise",
    completion: { doneWhen: "Each charge cites its approved source and the batch is approved for posting.", notDoneWhen: "The batch includes a true-up whose reconciliation statement was not approved." },
    forbidden: ["bill percentage rent from an estimated or unreported sales figure without flagging it", "bill a charge whose source computation is unapproved"],
    approvals: ["charge batch before posting"],
    collaborators: ["commercial.cam-estimate", "commercial.cam-reconciliation", "commercial.commercial-rent-escalation", "finance.charge-posting-preparation"],
  },
  {
    id: "commercial.commercial-coi-compliance",
    name: "Commercial COI Compliance",
    domain: "commercial",
    boundary: "Compares each commercial tenant's insurance certificate with that tenant's lease insurance clause (limits, additional insureds for landlord and lender, waiver of subrogation), tracks expirations and requests compliant replacements. Stops at a compliant certificate on file or an escalated gap.",
    notThis: { specialist: "spend-vendor.vendor-insurance-and-coi-compliance", because: "Vendor COI compliance holds contractors to the workspace's requirement before they work; this holds tenants to their own lease's clause, which differs lease by lease." },
    triggers: ["tenant coi", "tenant insurance", "certificate expired", "additional insured", "tenant certificate"],
    inputs: ["tenant certificates", "abstracted insurance clause per lease", "lender requirements"],
    outputs: ["compliance status per tenant", "requests for replacement certificates", "escalated gaps"],
    capabilities: ["insurance.read", "commercial.read", "lease.read", "document.extract"],
    execution: "deterministic",
    completion: { doneWhen: "Each tenant's current certificate is compared with that lease's clause, and each gap or expiry is tracked to a compliant certificate on file.", notDoneWhen: "An expired certificate was flagged, but no compliant replacement is on file." },
    forbidden: ["apply a portfolio standard in place of the tenant's lease requirement", "declare a tenant in default for an insurance gap"],
    approvals: [],
    collaborators: ["commercial.commercial-lease-abstract", "risk-compliance.vendor-insurance-compliance", "risk-compliance.property-insurance-monitor"],
  },
  {
    id: "commercial.tenant-improvement-coordination",
    name: "Tenant Improvement Coordination",
    domain: "commercial",
    boundary: "Carries one tenant's improvement work under its work letter: landlord and tenant work split, plan approvals, contractor certificates, allowance draws with invoices and lien waivers, and the delivery or completion date. Stops at prepared draws and approvals.",
    notThis: { specialist: "commercial.commercial-vendor-and-property-operations", because: "Vendor and property operations runs the building's day-to-day services; this carries one tenant's improvement project to completion and allowance close-out." },
    triggers: ["tenant improvement", "ti allowance", "work letter", "build-out", "draw request", "lien waiver"],
    inputs: ["work letter and abstract", "plans and approvals", "contractor invoices and lien waivers"],
    outputs: ["allowance ledger", "prepared draw requests", "completion record and delivery date"],
    capabilities: ["commercial.read", "lease.read", "vendor.read", "invoice.read", "payment.prepare", "document.read"],
    execution: "child_run",
    completion: { doneWhen: "The work letter deliverables are complete, every draw has its invoice and lien waiver, and the delivery or completion date is recorded.", notDoneWhen: "The allowance was fully drawn, but final lien waivers or the completion certificate are missing." },
    forbidden: ["prepare a draw beyond the remaining allowance", "release an allowance payment without the lien waiver the work letter requires"],
    approvals: ["each allowance draw", "tenant plan approval"],
    collaborators: ["commercial.commercial-lease-abstract", "commercial.commercial-option-and-notice-date", "spend-vendor.invoice-work-order-matching", "spend-vendor.vendor-insurance-and-coi-compliance"],
  },
  {
    id: "commercial.commercial-option-and-notice-date",
    name: "Commercial Option & Notice Date",
    domain: "commercial",
    boundary: "Tracks commercial lease rights and deadlines: renewal, expansion and termination options, first-offer and first-refusal rights, exercise windows and notice methods, rent commencement, co-tenancy triggers and estoppel response dates. Stops at acknowledged alerts and a recorded outcome.",
    notThis: { specialist: "lease-admin.critical-date-tracking", because: "Residential critical dates are mostly expirations and notice windows; commercial options carry exercise conditions and strict notice methods whose loss changes the asset's value." },
    triggers: ["option window", "renewal option", "termination right", "rofr", "estoppel", "rent commencement"],
    inputs: ["abstracted options and notice clauses", "delivery and commencement dates"],
    outputs: ["dated window schedule with notice method", "alerts with acknowledgement", "outcome per option"],
    capabilities: ["commercial.read", "lease.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Each window has its dates, notice method and clause, and each opened window has an acknowledged owner and a recorded outcome: exercised, lapsed or waived.", notDoneWhen: "The window closed after the alert was sent, with no recorded outcome." },
    forbidden: ["treat a tenant's email of intent as an exercise when the lease requires another method", "compute a window from a default where the lease is silent"],
    approvals: [],
    collaborators: ["commercial.commercial-lease-abstract", "commercial.commercial-rent-escalation", "lease-admin.critical-date-tracking"],
  },
  {
    id: "commercial.commercial-vendor-and-property-operations",
    name: "Commercial Vendor & Property Operations",
    domain: "commercial",
    boundary: "Handles commercial building operations and tenant service requests by the lease's repair and maintenance clauses: decides whether landlord or tenant bears each item and whether its cost is recoverable, then routes landlord-side work. Stops at routed work or a documented tenant notice.",
    notThis: { specialist: "maintenance.service-request-intake", because: "Service request intake takes residential repair reports; this first decides from the commercial lease who is responsible and whether the cost can be recovered." },
    triggers: ["tenant request", "building service", "hvac service", "janitorial", "landlord repair", "tenant responsibility"],
    inputs: ["service request", "repair and maintenance clauses", "building service contracts"],
    outputs: ["responsibility and recoverability decision with clause", "routed work or tenant notice"],
    capabilities: ["commercial.read", "lease.read", "work_order.read", "vendor.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "Each request records the clause assigning responsibility and cost, and has either landlord-side work routed or a documented tenant notice.", notDoneWhen: "Work was dispatched at landlord cost with no recorded responsibility decision." },
    forbidden: ["route landlord-paid work on an item the lease assigns to the tenant without approval", "mark a cost recoverable without the clause"],
    approvals: ["landlord-paid work on a tenant-responsibility item"],
    collaborators: ["maintenance.work-order-creation", "commercial.cam-reconciliation", "spend-vendor.approval-routing", "commercial.commercial-lease-abstract"],
  },
  {
    id: "commercial.commercial-reporting",
    name: "Commercial Reporting",
    domain: "commercial",
    boundary: "Builds commercial measures from abstracted lease terms and closed periods: rent roll with expirations, weighted average lease term, recoveries against budget, tenant arrears and co-tenancy exposure, each figure with its source and as-of date. Stops at the report.",
    notThis: { specialist: "data-integrations.operational-report-generation", because: "Operational reports are the workspace's standard reports from synced data; this computes commercial measures that depend on abstracted lease terms." },
    triggers: ["walt", "commercial rent roll", "expiry schedule", "recovery ratio", "tenant arrears report"],
    inputs: ["abstracts", "ledger and closed periods", "reconciliation results"],
    outputs: ["commercial report with source and as-of date per figure"],
    capabilities: ["commercial.read", "financial.statement.read", "delinquency.read", "report.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Each figure traces to the abstract, ledger or closed period it came from, and the report states its as-of date.", notDoneWhen: "The report used an open period or unapplied amendments without saying so." },
    forbidden: ["present unsigned renewals as committed occupancy", "mix periods in one measure without labeling them"],
    approvals: [],
    collaborators: ["data-integrations.operational-report-generation", "commercial.commercial-lease-abstract", "owner-services.property-performance-brief", "portfolio-strategy.portfolio-kpi"],
  },
];
