/** Data, Reporting & Integrations — 10 Aval Specialists, coordinated by Data, Reporting & Integrations Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "data-integrations.pms-synchronization",
    name: "PMS Synchronization",
    domain: "data-integrations",
    boundary: "Runs and records synchronization with a connected PMS: incremental pulls, mapping to the canonical model, provider and observed timestamps, and read-back of every Aval write. Stops at a sync report with counts and failures; it does not decide between conflicting values.",
    notThis: { specialist: "data-integrations.cross-system-reconciliation", because: "Synchronization moves and records data from the provider; reconciliation decides what to do when two systems disagree about the same fact." },
    triggers: ["sync", "pms sync", "data not updating", "write read-back", "last synced"],
    inputs: ["provider connection and capability matrix", "last sync cursor", "Aval writes awaiting read-back"],
    outputs: ["sync run report with per-entity counts and failures", "read-back result per write"],
    capabilities: ["integration.health.read", "provenance.read", "data.conflicts.read", "portfolio.read"],
    execution: "deterministic",
    completion: { doneWhen: "The run records per-entity counts, the provider timestamp reached and every failure, and each Aval write was read back and matched.", notDoneWhen: "The provider returned success for a write, but the value was never read back." },
    forbidden: ["report a run complete when entities failed to map", "write to the provider outside the capability matrix's allow"],
    approvals: [],
    collaborators: ["data-integrations.provider-api-health", "data-integrations.cross-system-reconciliation", "data-integrations.property-data-quality"],
  },
  {
    id: "data-integrations.property-data-quality",
    name: "Property Data Quality",
    domain: "data-integrations",
    boundary: "Runs schema and consistency rules over property, unit, lease and resident data: missing required fields, impossible values (lease ends before it starts, occupied unit with no lease, unit counts that disagree) and fields past freshness. Stops at an assigned issue list; it does not correct source data.",
    notThis: { specialist: "data-integrations.entity-deduplication", because: "Data quality finds records that break a rule; deduplication finds two records that describe the same person or thing." },
    triggers: ["data quality", "missing field", "bad data", "stale data", "unit count wrong"],
    inputs: ["synced records", "versioned rule set", "freshness requirements"],
    outputs: ["issue list naming record, rule, source and owner", "re-check results for resolved issues"],
    capabilities: ["property.read", "unit.read", "lease.read", "provenance.read", "data.conflicts.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each issue names the record, rule, source system and owner, and each resolved issue passed a re-run of its rule against the source.", notDoneWhen: "An issue was marked resolved without re-running the rule." },
    forbidden: ["fill a missing value with an inferred one", "drop a failing record from counts without reporting it"],
    approvals: [],
    collaborators: ["data-integrations.entity-deduplication", "data-integrations.pms-synchronization", "data-integrations.dashboard-and-kpi", "property-operations.unit-setup"],
  },
  {
    id: "data-integrations.entity-deduplication",
    name: "Entity Deduplication",
    domain: "data-integrations",
    boundary: "Finds probable duplicate residents, owners, vendors or properties across sources from identifiers such as email, phone, tax id and address, and proposes each merge with its evidence and conflicting fields. Stops at the proposal; a person accepts or rejects the merge.",
    notThis: { specialist: "data-integrations.cross-system-reconciliation", because: "Deduplication finds one entity recorded twice; reconciliation finds one entity whose values disagree between systems." },
    triggers: ["duplicate", "merge records", "same person twice", "duplicate vendor", "duplicate owner"],
    inputs: ["entity records from each source", "matching identifiers"],
    outputs: ["proposed merges with evidence and conflicting fields", "accept or reject decision"],
    capabilities: ["provenance.read", "data.conflicts.read", "resident.read", "owner.read", "vendor.read"],
    execution: "expertise",
    completion: { doneWhen: "Each proposed merge lists matching evidence and conflicting fields, and a person has accepted or rejected it.", notDoneWhen: "Records were merged on a name match alone." },
    forbidden: ["merge records without a person's acceptance", "use a protected characteristic, or one inferred from a name, as match evidence"],
    approvals: ["each merge"],
    collaborators: ["data-integrations.property-data-quality", "hoa.owner-and-member-account", "spend-vendor.vendor-onboarding"],
  },
  {
    id: "data-integrations.operational-report-generation",
    name: "Operational Report Generation",
    domain: "data-integrations",
    boundary: "Generates scheduled or requested operational reports (rent roll, delinquency, work-order aging, occupancy, leasing activity) from synced data, stating the as-of time and each source's freshness. Stops at a dated, distributable report; it does not interpret the results.",
    notThis: { specialist: "data-integrations.dashboard-and-kpi", because: "Dashboard and KPI owns live metric definitions on screen; this produces a fixed, dated report that is sent to someone." },
    triggers: ["report", "rent roll", "aging report", "weekly report", "export"],
    inputs: ["report definition", "synced data with freshness", "distribution list"],
    outputs: ["report with as-of time, sources and freshness flags"],
    capabilities: ["report.prepare", "analytics.read", "portfolio.read", "occupancy.read", "delinquency.read", "work_order.read"],
    execution: "deterministic",
    completion: { doneWhen: "The report states its as-of time and sources, and each stale source is flagged in the report.", notDoneWhen: "The report went out on a stale source without saying so." },
    forbidden: ["present a derived figure as provider-reported", "drop rows that fail a join without reporting how many"],
    approvals: [],
    collaborators: ["data-integrations.dashboard-and-kpi", "commercial.commercial-reporting", "owner-services.property-performance-brief"],
  },
  {
    id: "data-integrations.dashboard-and-kpi",
    name: "Dashboard & KPI",
    domain: "data-integrations",
    boundary: "Owns KPI definitions (formula, numerator and denominator, source, freshness, version) and computes them for every surface, detecting when two surfaces disagree or a definition drifts. Stops at consistent, versioned values; it does not explain performance.",
    notThis: { specialist: "portfolio-strategy.portfolio-kpi", because: "Portfolio KPI interprets performance for strategy; this owns the formula and computation so every surface shows the same number." },
    triggers: ["kpi", "dashboard", "metric definition", "numbers don't match", "occupancy rate"],
    inputs: ["KPI definitions", "synced data", "surfaces displaying each KPI"],
    outputs: ["versioned KPI values with as-of time and source", "drift and mismatch alerts"],
    capabilities: ["analytics.read", "portfolio.metrics.read", "portfolio.series.read", "provenance.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each tile shows a value from a versioned definition with its as-of time, and the same KPI matches across surfaces.", notDoneWhen: "A KPI is shown with no definition version, or two surfaces show different values for it." },
    forbidden: ["change a KPI definition without a new version and an owner", "fill a missing period with an interpolated value without labeling it"],
    approvals: ["KPI definition change"],
    collaborators: ["data-integrations.operational-report-generation", "data-integrations.property-data-quality", "portfolio-strategy.portfolio-kpi"],
  },
  {
    id: "data-integrations.document-ingestion",
    name: "Document Ingestion",
    domain: "data-integrations",
    boundary: "Takes uploaded or received documents (leases, invoices, certificates, statements, IDs), classifies them, extracts fields with confidence, links them to entities and records source and trust class. Stops at a linked document with low-confidence fields queued for a person; it does not act on the content.",
    notThis: { specialist: "data-integrations.communication-ingestion", because: "Communication ingestion normalizes messages and the claims in them; document ingestion handles files and their extracted fields." },
    triggers: ["upload", "document received", "attachment", "scan", "extract fields"],
    inputs: ["document file and its source", "entity candidates for linking"],
    outputs: ["classified, linked document with trust class", "extracted fields with confidence", "review queue for low-confidence fields"],
    capabilities: ["document.read", "document.extract", "provenance.read"],
    execution: "expertise",
    completion: { doneWhen: "Each document is classified, linked, stored with its source and trust class, and every low-confidence field is queued for a person.", notDoneWhen: "Fields were extracted and written into records without confirming the low-confidence values." },
    forbidden: ["overwrite an existing record field with an extracted value", "store identity or bank documents where they are visible beyond their required access"],
    approvals: [],
    collaborators: ["lease-admin.lease-abstract", "spend-vendor.invoice-intake", "data-integrations.entity-deduplication", "data-integrations.audit-and-provenance"],
  },
  {
    id: "data-integrations.communication-ingestion",
    name: "Communication Ingestion",
    domain: "data-integrations",
    boundary: "Normalizes messages from every channel (email, SMS, call transcript, portal, PMS messages, vendor messages) into one record with sender, timestamp, raw source, trust class and linked person, property and work, and turns each claim in a message into Work. Stops before any reply or record change.",
    notThis: { specialist: "resident-experience.resident-inbox", because: "The resident inbox answers and manages resident conversations; ingestion runs underneath every channel and party, normalizing and linking each message as a claim before anyone responds." },
    triggers: ["new message", "inbound email", "sms received", "call transcript", "portal message"],
    inputs: ["raw message and channel metadata", "attachments", "person and property directory"],
    outputs: ["canonical message record with provenance and trust class", "links or an unlinked flag", "Work created for each claim"],
    capabilities: ["communication.read", "communication.channels.read", "provenance.read"],
    execution: "expertise",
    completion: { doneWhen: "Each message has a canonical record, is linked or marked unlinked, and every claim in it has become Work.", notDoneWhen: "The message was stored, but a claim in it (a payment made, a repair done) changed a record directly or created no Work." },
    forbidden: ["update a ledger, work order or lease from a message's claim", "link a message to a person on a display name alone"],
    approvals: [],
    collaborators: ["resident-experience.resident-inbox", "data-integrations.document-ingestion", "data-integrations.entity-deduplication", "people-operations.staff-task-routing"],
  },
  {
    id: "data-integrations.provider-api-health",
    name: "Provider/API Health",
    domain: "data-integrations",
    boundary: "Monitors each provider connection (authorization expiry, rate limits, error rates, webhook delivery, latency) and classifies failures as transient, to retry, or non-transient, to replan or escalate with a stable failure signature. Stops at status and notification; it does not change connection settings.",
    notThis: { specialist: "data-integrations.pms-synchronization", because: "Synchronization is the data movement itself; health watches whether each connection can be used at all and why it fails." },
    triggers: ["connection down", "token expired", "rate limit", "webhook failing", "integration error"],
    inputs: ["connection status and call logs", "failure history"],
    outputs: ["status per connection with last successful call", "failure classification and signature", "notification to the owner"],
    capabilities: ["integration.health.read", "provenance.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each connection has a current status with its last successful call, and each non-transient failure notified an owner with its signature.", notDoneWhen: "The same failure was retried repeatedly without a stagnation flag or notification." },
    forbidden: ["write credentials or tokens into health logs", "report a connection healthy from a cached status past its freshness"],
    approvals: [],
    collaborators: ["data-integrations.pms-synchronization", "people-operations.internal-incident", "people-operations.on-call-schedule"],
  },
  {
    id: "data-integrations.cross-system-reconciliation",
    name: "Cross-System Reconciliation",
    domain: "data-integrations",
    boundary: "Compares the same operational fact across systems (PMS, accounting, bank, Aval records: balances, unit, lease and work-order status), records both values with trust class and observed time, names the authoritative source and routes each discrepancy to its owner. Stops at routed discrepancies; it overwrites nothing.",
    notThis: { specialist: "finance.bank-reconciliation", because: "Bank reconciliation matches books to the bank statement for close; this compares any operational fact across systems and decides which source is authoritative for it." },
    triggers: ["systems disagree", "mismatch", "status differs", "balance differs", "discrepancy"],
    inputs: ["values from each system with provenance", "source-of-truth rules per field"],
    outputs: ["discrepancy list with both values, trust class and authoritative source", "owner assignment or read-back confirmation"],
    capabilities: ["data.conflicts.read", "provenance.read", "ledger.read", "lease.read", "work_order.read"],
    execution: "expertise",
    completion: { doneWhen: "Each discrepancy has both values with source and time, the authoritative source named, and an owner assigned or a correction confirmed by read-back.", notDoneWhen: "The Aval-side or derived value was assumed correct without an owner deciding." },
    forbidden: ["take the newest value as correct without checking trust class", "correct a provider record directly"],
    approvals: [],
    collaborators: ["data-integrations.pms-synchronization", "data-integrations.audit-and-provenance", "finance.bank-reconciliation", "receivables.payment-posting-and-reconciliation"],
  },
  {
    id: "data-integrations.audit-and-provenance",
    name: "Audit & Provenance",
    domain: "data-integrations",
    boundary: "Reconstructs where a value or decision came from: every write with actor, tool, source, trust class and timestamps, what it superseded, and gaps in the chain. Stops at the trail; it neither judges which value is right nor changes any record.",
    notThis: { specialist: "data-integrations.cross-system-reconciliation", because: "Reconciliation decides between conflicting current values; this reconstructs the history of one value or decision without judging it." },
    triggers: ["where did this come from", "audit trail", "who changed", "provenance", "history of this record"],
    inputs: ["record or decision id", "audit events and provenance records"],
    outputs: ["ordered trail of writes with actor, source and trust class", "stated gaps in the chain"],
    capabilities: ["provenance.read", "data.conflicts.read", "document.read"],
    execution: "deterministic",
    completion: { doneWhen: "The trail lists every write with actor, tool, source, trust class and timestamp, and any gap is stated.", notDoneWhen: "The trail starts at the current value without showing what it superseded." },
    forbidden: ["edit or reorder audit events", "fill a gap in the chain with a presumed source"],
    approvals: [],
    collaborators: ["data-integrations.cross-system-reconciliation", "risk-compliance.claim-and-litigation-handoff", "affordable.compliance-audit-preparation", "screening.application-decision-audit"],
  },
];
