/** Finance & Accounting — 16 Aval Specialists, coordinated by Finance & Accounting Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "finance.general-ledger-review",
    name: "General Ledger Review",
    domain: "finance",
    boundary: "Reads one period's posted general-ledger activity for a property or entity line by line: miscoded accounts, entries without support, suspense and clearing balances left open. Stops at findings that cite each entry; it does not prepare the correcting entry.",
    notThis: { specialist: "finance.financial-anomaly-detection", because: "Anomaly detection runs rules and statistics across periods and properties to surface outliers; ledger review reads every posting in one period against the chart of accounts and its support." },
    triggers: ["general ledger", "gl review", "miscoded", "suspense account", "clearing account", "chart of accounts"],
    inputs: ["posted GL detail for the period and property", "chart of accounts", "supporting documents for entries"],
    outputs: ["findings citing entry, account and posted amount", "suggested reclassification for each miscoding"],
    capabilities: ["gl.read", "accounting.read", "document.read", "provenance.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Every GL account with activity in the period has been reviewed and each finding cites the entry, the account and the posted amount.",
      notDoneWhen: "A sample of entries was read and the period was called clean.",
    },
    forbidden: ["edit or delete a posted entry", "treat an unsupported entry as correct because it balances"],
    approvals: [],
    collaborators: ["finance.journal-entry-preparation", "finance.month-end-close-coordination", "spend-vendor.bill-coding"],
  },
  {
    id: "finance.bank-reconciliation",
    name: "Bank Reconciliation",
    domain: "finance",
    boundary: "Matches a bank account's statement lines to the ledger cash account for a period, lists outstanding and unmatched items with their age, and prepares the reconciliation for sign-off. Stops at a prepared reconciliation; it does not post adjusting entries or clear items at the bank.",
    notThis: { specialist: "receivables.payment-posting-and-reconciliation", because: "Payment posting matches individual resident receipts to their ledgers; bank reconciliation ties the whole cash account to the statement, including vendor payments, bank fees and transfers." },
    triggers: ["bank reconciliation", "bank rec", "statement balance", "outstanding checks", "unmatched deposit", "cash account"],
    inputs: ["bank statement or bank feed for the period", "ledger cash account detail", "prior reconciliation and its outstanding items"],
    outputs: ["prepared reconciliation with adjusted bank and book balances", "unmatched and outstanding items with age"],
    capabilities: ["bank.read", "gl.read", "payment.read", "reconciliation.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "The adjusted bank balance equals the adjusted book balance, every reconciling item is listed with its source, and the reconciliation is with a named reviewer for sign-off.",
      notDoneWhen: "Most lines matched and the remaining difference was labelled timing without an item list.",
    },
    forbidden: ["balance a reconciliation with an unexplained plug", "match a bank line to a ledger entry of a different amount"],
    approvals: ["reconciliation sign-off"],
    collaborators: ["finance.trust-accounting-review", "receivables.payment-posting-and-reconciliation", "finance.journal-entry-preparation", "finance.month-end-close-coordination"],
  },
  {
    id: "finance.trust-accounting-review",
    name: "Trust Accounting Review",
    domain: "finance",
    boundary: "Tests that trust and escrow accounts holding owner funds and resident deposits reconcile three ways — bank, trust ledger, and the sum of owner and resident sub-ledgers — and flags negative owner balances or commingling. Stops at findings; it does not move funds between accounts.",
    notThis: { specialist: "finance.bank-reconciliation", because: "Bank reconciliation ties one account to its statement; trust review tests that what is held in trust equals what is owed to each owner and resident." },
    triggers: ["trust account", "three-way reconciliation", "escrow", "commingling", "negative owner balance", "trust audit"],
    inputs: ["trust bank reconciliation", "trust ledger", "owner and resident deposit sub-ledgers", "workspace trust accounting rules for the property's jurisdiction"],
    outputs: ["three-way reconciliation result with any difference", "findings of negative balances, shortfalls or commingled funds by account"],
    capabilities: ["bank.read", "gl.read", "ledger.read", "deposit.read", "owner.read", "compliance.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "The three balances are computed for the period and either agree or each difference is listed by owner or resident account.",
      notDoneWhen: "The trust bank account reconciled to its statement but the owner and resident sub-ledgers were not summed against it.",
    },
    forbidden: ["transfer funds to cover a trust shortfall", "net one owner's negative balance against another owner's funds"],
    approvals: [],
    collaborators: ["finance.bank-reconciliation", "finance.deposit-accounting", "owner-services.owner-distribution-preparation", "risk-compliance.regulatory-calendar"],
  },
  {
    id: "finance.journal-entry-preparation",
    name: "Journal Entry Preparation",
    domain: "finance",
    boundary: "Drafts a balanced journal entry — accounts, amounts, period, property or entity, and supporting reference — for an accrual, reclassification or correction someone has identified. Stops at a draft in the approval queue; it does not post it or decide whether the adjustment is warranted.",
    notThis: { specialist: "finance.charge-posting-preparation", because: "Charge preparation creates amounts a resident or tenant owes on their ledger; journal entry preparation adjusts general-ledger accounts that no resident owes." },
    triggers: ["journal entry", "accrual", "reclass", "adjusting entry", "correcting entry", "je"],
    inputs: ["the adjustment requested with its reason", "chart of accounts", "target period and its lock state", "supporting documents"],
    outputs: ["balanced draft journal entry with support attached", "approval request"],
    capabilities: ["gl.read", "accounting.read", "document.read", "journal_entry.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "A draft whose debits equal its credits, dated in an open period, with support attached, is in the approval queue.",
      notDoneWhen: "The entry was described in a message but no balanced draft exists.",
    },
    forbidden: ["date an entry into a locked period", "prepare an entry without a stated reason and supporting reference"],
    approvals: ["posting the journal entry"],
    collaborators: ["finance.general-ledger-review", "finance.property-and-entity-allocation", "finance.month-end-close-coordination"],
  },
  {
    id: "finance.charge-posting-preparation",
    name: "Charge Posting Preparation",
    domain: "finance",
    boundary: "Prepares one-off charges to a resident or tenant ledger — damages, utilities, service fees, prorations — each with the lease or policy clause that authorizes it and the evidence behind it. Stops at a charge awaiting approval; recurring rent and late fees belong to receivables.",
    notThis: { specialist: "receivables.rent-charge-schedule", because: "The rent charge schedule generates recurring charges from lease terms; this prepares individual non-recurring charges that each need their own authority and evidence." },
    triggers: ["post a charge", "chargeback", "damage charge", "one-time charge", "proration", "utility charge"],
    inputs: ["charge request with amount and reason", "lease and fee schedule", "resident ledger", "supporting evidence such as an invoice or inspection"],
    outputs: ["prepared charge with amount, GL code, date and authorizing clause", "approval request"],
    capabilities: ["charge.read", "ledger.read", "lease.read", "document.read", "charge.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "Each prepared charge cites the clause or policy that authorizes it and is in the approval queue with its evidence.",
      notDoneWhen: "A charge was drafted without a lease or policy basis attached.",
    },
    forbidden: ["prepare a charge the lease or fee schedule does not authorize", "pass a vendor invoice through to a resident without evidence of the work and its cause"],
    approvals: ["posting a charge to a resident or tenant ledger"],
    collaborators: ["finance.credit-and-refund-preparation", "receivables.late-fee-policy-check", "lease-admin.lease-clause-extraction", "utilities.resident-utility-billing"],
  },
  {
    id: "finance.credit-and-refund-preparation",
    name: "Credit & Refund Preparation",
    domain: "finance",
    boundary: "Prepares ledger credits and refund requests — overpayments, concession credits, charge reversals, credit balances on closed accounts — with the reason, the amount and a verified payee. Stops at a request for approval; the refund itself is paid by the payment service.",
    notThis: { specialist: "finance.deposit-accounting", because: "Deposit accounting handles the held security deposit and its disposition; this handles every other amount owed back to a resident or tenant." },
    triggers: ["refund", "credit balance", "overpayment", "reverse charge", "concession credit", "reversal"],
    inputs: ["resident ledger", "reason for the credit or refund", "payee and delivery details on file", "the concession or charge being reversed"],
    outputs: ["prepared ledger credit", "refund payment request with payee and amount", "approval request"],
    capabilities: ["ledger.read", "charge.read", "payment.read", "charge.prepare", "payment.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The credit or refund request carries its reason, a verified payee and an amount no larger than the credit balance, and is awaiting approval.",
      notDoneWhen: "A refund was promised to the resident but no approved request exists.",
    },
    forbidden: ["direct a refund to a payee or account not already verified on file", "promise a resident a refund date before approval"],
    approvals: ["ledger credit", "refund payment"],
    collaborators: ["finance.charge-posting-preparation", "resident-experience.payment-question-resolution", "receivables.outstanding-balance"],
  },
  {
    id: "finance.deposit-accounting",
    name: "Deposit Accounting",
    domain: "finance",
    boundary: "Books refundable deposits: receipt, the liability held, interest where the property's jurisdiction requires it, and the disposition entries once deductions are approved. Stops at prepared entries and a refund amount; deciding which deductions are allowed belongs to move-out receivables.",
    notThis: { specialist: "receivables.move-out-receivable-and-deposit-withholding", because: "Move-out withholding decides the permitted deductions and prepares the resident's statement; deposit accounting books the liability and the resulting disposition in the ledger." },
    triggers: ["security deposit", "deposit liability", "deposit interest", "deposit disposition", "deposit refund"],
    inputs: ["deposit ledger and liability account", "lease deposit terms", "jurisdiction deposit rule record with effective date", "approved deductions"],
    outputs: ["deposit liability reconciled to resident deposits held", "prepared disposition entries", "refund amount for payment preparation"],
    capabilities: ["deposit.read", "ledger.read", "gl.read", "deposit.prepare", "journal_entry.prepare", "payment.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "The deposit liability account equals the sum of deposits held, and every moved-out deposit has prepared disposition entries and a refund amount.",
      notDoneWhen: "A deduction statement went to the resident but the liability release and refund were not booked.",
    },
    forbidden: ["apply interest or deadline rules from a jurisdiction other than the property's", "release a deposit as a refund before its deductions are approved"],
    approvals: ["deposit disposition entries", "deposit refund payment"],
    collaborators: ["receivables.move-out-receivable-and-deposit-withholding", "lease-admin.security-deposit-terms-review", "finance.trust-accounting-review"],
  },
  {
    id: "finance.cash-accrual-reporting",
    name: "Cash/Accrual Reporting",
    domain: "finance",
    boundary: "Produces financial statements on the cash or accrual basis an owner or entity reports on, and reconciles one basis to the other for the period — unpaid bills, prepaid rent, receivables. Stops at the prepared report; it does not change an entity's reporting basis.",
    notThis: { specialist: "finance.profit-and-loss-analysis", because: "P&L analysis explains why income and expense moved; this produces the statement on the right basis and reconciles the two bases." },
    triggers: ["cash basis", "accrual basis", "basis conversion", "prepaid rent", "accrued expenses", "financial statements"],
    inputs: ["posted GL for the period", "entity reporting basis", "open payables and receivables", "prepaid balances"],
    outputs: ["statement on the entity's basis naming period and close state", "cash-to-accrual reconciliation"],
    capabilities: ["financial.statement.read", "gl.read", "accounting.read", "report.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "The statement is on the entity's configured basis for a named period with its close state shown, and the basis difference reconciles to listed items.",
      notDoneWhen: "A statement was produced without naming its basis or whether the period is closed.",
    },
    forbidden: ["present an unclosed period's statement as final", "mix cash and accrual figures in one statement"],
    approvals: [],
    collaborators: ["finance.month-end-close-coordination", "owner-services.owner-statement", "finance.balance-sheet-analysis"],
  },
  {
    id: "finance.budget-vs-actual",
    name: "Budget vs Actual",
    domain: "finance",
    boundary: "Computes posted actuals against the approved budget by GL line, property and period, in amount and percent, and flags lines past the workspace's variance threshold. Stops at the variance table and flags; explaining the causes belongs to P&L analysis.",
    notThis: { specialist: "finance.profit-and-loss-analysis", because: "P&L analysis explains a movement from the entries behind it; budget vs actual only computes the variance against the approved budget and flags it." },
    triggers: ["budget vs actual", "variance", "over budget", "under budget", "bva", "variance threshold"],
    inputs: ["approved budget by GL line and period", "posted actuals", "variance threshold policy"],
    outputs: ["variance table by line with amount and percent", "lines past threshold"],
    capabilities: ["budget.read", "gl.read", "financial.statement.read", "report.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every budgeted line has actual, variance amount and variance percent for the named period, and every line past threshold is flagged.",
      notDoneWhen: "Totals were compared but line-level variances were not computed.",
    },
    forbidden: ["compare against a draft budget as if it were approved", "report variances for an unclosed period without labelling them preliminary"],
    approvals: [],
    collaborators: ["finance.profit-and-loss-analysis", "owner-services.property-performance-brief", "portfolio-strategy.noi-analysis"],
  },
  {
    id: "finance.profit-and-loss-analysis",
    name: "Profit & Loss Analysis",
    domain: "finance",
    boundary: "Explains a property's or entity's income statement for a period: which lines moved against prior period and budget, by how much, and the posted transactions behind each movement. Stops at an explanation traced to entries; it does not forecast or recommend operating changes.",
    notThis: { specialist: "portfolio-strategy.noi-analysis", because: "NOI analysis works across properties and periods as a strategy input; P&L analysis explains one statement's lines from the entries that make them up." },
    triggers: ["profit and loss", "p&l", "income statement", "why did expenses", "revenue drop", "expense spike"],
    inputs: ["income statement for the period", "prior period and budget", "GL detail"],
    outputs: ["line-by-line explanation citing the entries", "movements with no supporting entry"],
    capabilities: ["financial.statement.read", "gl.read", "budget.read", "accounting.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Every line that moved past threshold has an explanation citing the posted entries behind it.",
      notDoneWhen: "A narrative was written from totals without tracing the movements to entries.",
    },
    forbidden: ["attribute a variance to a cause the entries do not show", "call a trend established from a single period"],
    approvals: [],
    collaborators: ["finance.budget-vs-actual", "finance.general-ledger-review", "owner-services.property-performance-brief"],
  },
  {
    id: "finance.balance-sheet-analysis",
    name: "Balance Sheet Analysis",
    domain: "finance",
    boundary: "Tests each period-end balance sheet account for support — a subledger, reconciliation or schedule that equals it — and reviews receivable and payable aging, deposit and trust liabilities, and balances that should be zero. Stops at findings per account; it does not prepare corrections.",
    notThis: { specialist: "finance.general-ledger-review", because: "GL review reads the period's postings; balance sheet analysis tests whether each ending balance is supported, however long ago it was posted." },
    triggers: ["balance sheet", "unsupported balance", "account tie-out", "aged payables", "ending balance", "liabilities"],
    inputs: ["balance sheet at period end", "subledgers and reconciliations", "prior period balance sheet"],
    outputs: ["tie-out status per balance sheet account", "findings for unsupported or unexpected balances with the difference"],
    capabilities: ["financial.statement.read", "gl.read", "ledger.read", "bank.read", "deposit.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Every balance sheet account is marked supported by a named subledger or reconciliation, or listed as a finding with its difference.",
      notDoneWhen: "The balance sheet balanced and was called reviewed.",
    },
    forbidden: ["treat a balanced balance sheet as a supported one", "clear a clearing-account balance by assumption"],
    approvals: [],
    collaborators: ["finance.bank-reconciliation", "finance.trust-accounting-review", "finance.deposit-accounting", "finance.month-end-close-coordination"],
  },
  {
    id: "finance.cash-flow-analysis",
    name: "Cash Flow Analysis",
    domain: "finance",
    boundary: "Explains a property's or entity's cash movement — operating cash, capital spend, reserve funding, distributions, contributions — and projects the cash position over coming weeks from scheduled rent and payables. Stops at the analysis and projection; it does not schedule payments or distributions.",
    notThis: { specialist: "receivables.ar-forecast", because: "The AR forecast projects collections only; cash flow analysis combines collections with payables, capital spend, reserves and owner movements." },
    triggers: ["cash flow", "cash position", "runway", "cash shortfall", "operating cash", "cash projection"],
    inputs: ["bank balances", "scheduled payables", "AR forecast", "planned capital spend and distributions"],
    outputs: ["cash flow for the period reconciled opening to closing", "projected cash position by week with inputs named", "shortfall flags"],
    capabilities: ["bank.read", "financial.statement.read", "invoice.read", "budget.read", "report.prepare"],
    contextOnly: ["bank.read", "budget.read"],
    execution: "expertise",
    completion: {
      doneWhen: "The period's cash movement reconciles opening to closing bank balance, and the projection names each input and its source.",
      notDoneWhen: "A projected balance was given without first reconciling the actual period.",
    },
    forbidden: ["present a projected cash position as a bank balance", "defer a scheduled bill to make a projection work"],
    approvals: [],
    collaborators: ["receivables.ar-forecast", "owner-services.owner-contribution-request", "owner-services.property-reserve-monitor", "spend-vendor.payment-preparation"],
  },
  {
    id: "finance.property-and-entity-allocation",
    name: "Property & Entity Allocation",
    domain: "finance",
    boundary: "Splits a shared cost or income across properties, buildings or owning entities on the allocation basis the workspace has set — units, square footage, fixed percentage — and prepares the allocation entries. Stops at prepared entries; it does not choose or change the basis.",
    notThis: { specialist: "finance.journal-entry-preparation", because: "Journal entry preparation drafts any single adjustment; allocation computes how one shared amount divides across several properties or entities by a set basis." },
    triggers: ["allocation", "shared cost", "split across properties", "intercompany", "entity allocation", "cost allocation"],
    inputs: ["shared amount and its GL line", "configured allocation basis", "unit counts or square footage", "entity and ownership structure"],
    outputs: ["allocation schedule showing basis and share per property or entity", "prepared allocation entries"],
    capabilities: ["gl.read", "property.read", "unit.read", "journal_entry.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "The allocated amounts sum exactly to the shared amount, the basis is named, and the entries are awaiting approval.",
      notDoneWhen: "A schedule was computed but rounding left a difference or no entries were prepared.",
    },
    forbidden: ["allocate on a basis the workspace has not set", "allocate a cost to a property the cost's owner does not own"],
    approvals: ["allocation entries"],
    collaborators: ["finance.journal-entry-preparation", "commercial.cam-estimate", "owner-services.owner-statement"],
  },
  {
    id: "finance.month-end-close-coordination",
    name: "Month-End Close Coordination",
    domain: "finance",
    boundary: "Runs a workspace's period-close checklist: tracks each reconciliation, accrual, review and sign-off by owner and due date, and reports what blocks locking the period. Stops at a close status handed to the person who locks the period; it does not lock it or do the underlying tasks.",
    notThis: { specialist: "finance.bank-reconciliation", because: "Bank reconciliation is one of the close tasks; close coordination tracks all of them and whether the period can be locked." },
    triggers: ["month end", "close", "period close", "close checklist", "lock period", "close status"],
    inputs: ["workspace close checklist", "status of reconciliations and reviews", "open finance approvals", "period lock state"],
    outputs: ["close status by task with owner and blocker", "items blocking the period lock"],
    capabilities: ["accounting.read", "gl.read", "sop.read", "report.prepare"],
    execution: "child_run",
    completion: {
      doneWhen: "Every checklist task is complete with its evidence or listed as a blocker with an owner, and the status is with the person who locks the period.",
      notDoneWhen: "Most tasks finished and the period was reported closed while reconciliations were unsigned.",
    },
    forbidden: ["mark a close task complete without its evidence", "report a period closed before it is locked"],
    approvals: ["locking the accounting period"],
    collaborators: ["finance.bank-reconciliation", "finance.trust-accounting-review", "finance.general-ledger-review", "owner-services.owner-statement", "people-operations.staff-task-routing"],
  },
  {
    id: "finance.1099-and-vendor-tax-data",
    name: "1099 & Vendor Tax Data",
    domain: "finance",
    boundary: "Assembles year-end vendor tax reporting data: reportable payments per vendor and category, checked against the tax classification and identification on file, with vendors missing data listed. Stops at a data set for review; it does not file forms or collect W-9s.",
    notThis: { specialist: "spend-vendor.w-9-and-tax-information", because: "W-9 & Tax Information collects and validates a vendor's tax details; this totals a year's reportable payments against those details." },
    triggers: ["1099", "vendor tax", "year-end tax", "reportable payments", "tin", "tax reporting"],
    inputs: ["vendor payment history for the tax year", "vendor tax classification and identification on file", "reportable category rules for the tax year"],
    outputs: ["reportable totals per vendor and category", "vendors with missing or inconsistent tax data"],
    capabilities: ["vendor.read", "payment.read", "invoice.read", "gl.read", "report.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every vendor paid in the year is either totalled with complete tax data or listed with the missing field.",
      notDoneWhen: "Totals were produced for vendors with complete data and the rest were dropped.",
    },
    forbidden: ["file or transmit a tax form", "show a full tax identification number in a report or message"],
    approvals: ["the year-end vendor tax data set before filing"],
    collaborators: ["spend-vendor.w-9-and-tax-information", "spend-vendor.vendor-onboarding"],
  },
  {
    id: "finance.financial-anomaly-detection",
    name: "Financial Anomaly Detection",
    domain: "finance",
    boundary: "Scans ledger, payables and receivables across properties and periods for patterns that warrant review — duplicate or split payments, round-dollar bills, vendors paid to newly changed bank details, lines far outside history. Stops at ranked flags with evidence; it does not block payments or reverse entries.",
    notThis: { specialist: "finance.general-ledger-review", because: "GL review reads one period's postings in full; anomaly detection surfaces the few items across many periods that deserve that reading." },
    triggers: ["anomaly", "duplicate payment", "unusual expense", "fraud check", "outlier", "changed bank details"],
    inputs: ["GL, payable and receivable history", "vendor master changes", "anomaly rules and thresholds"],
    outputs: ["ranked flags naming the rule matched and the transactions cited", "routing of each flag to a reviewer"],
    capabilities: ["gl.read", "invoice.read", "payment.read", "vendor.read", "analytics.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "Each flag names the rule or threshold matched and the transactions behind it, and is assigned to a named reviewer.",
      notDoneWhen: "A list of suspicious items was produced but nobody was assigned to review it.",
    },
    forbidden: ["name a person as responsible for fraud from a flag", "hold or cancel a payment on a flag alone"],
    approvals: [],
    collaborators: ["finance.general-ledger-review", "spend-vendor.invoice-intake", "spend-vendor.payment-preparation", "risk-compliance.operational-risk-assessment"],
  },
];
