/** HOA & Community Associations — 10 Aval Specialists, coordinated by HOA & Community Associations Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "hoa.owner-and-member-account",
    name: "Owner & Member Account",
    domain: "hoa",
    boundary: "Keeps each lot's member record: owner of record from the deed or transfer document, notice address and preferred notice method, owners' tenants, and voting eligibility, updating it on a recorded transfer. Stops at the record; it does not issue resale disclosures or change balances.",
    notThis: { specialist: "owner-services.owner-and-client-onboarding", because: "Owner onboarding brings a management client and their rental property into the workspace; this maintains the homeowner members of an association, whose rights come from the governing documents." },
    triggers: ["new owner", "sale closed", "change of address", "member record", "voting eligibility", "transfer"],
    inputs: ["deed or transfer document", "member's notice preferences", "association roster"],
    outputs: ["updated member record with source and date", "notice address and voting eligibility"],
    capabilities: ["association.read", "assessment.read", "document.read", "document.extract"],
    execution: "expertise",
    completion: { doneWhen: "The member record matches the recorded deed or transfer document, with its source and date, and the notice address and voting eligibility are current.", notDoneWhen: "Ownership was changed on an email or a call without the recorded transfer document." },
    forbidden: ["change the owner of record from a communication alone", "share one member's contact or account details with another member"],
    approvals: [],
    collaborators: ["hoa.assessment-coordination", "hoa.community-communication", "data-integrations.entity-deduplication"],
  },
  {
    id: "hoa.assessment-coordination",
    name: "Assessment Coordination",
    domain: "hoa",
    boundary: "Computes each lot's regular and special assessments from the adopted budget and the governing documents' allocation formula, and prepares the charges, citing the approving board or membership vote. Stops at prepared charges; collection of unpaid assessments belongs to delinquency.",
    notThis: { specialist: "hoa.association-delinquency", because: "Assessment coordination sets what each owner owes; delinquency works the accounts that have not paid it." },
    triggers: ["assessment", "dues", "special assessment", "budget adopted", "allocation"],
    inputs: ["adopted budget", "allocation formula and lot shares", "board or member approval record"],
    outputs: ["assessment schedule per lot", "prepared charges with the approval cited"],
    capabilities: ["assessment.read", "association.read", "budget.read", "charge.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Each lot's assessment matches the adopted budget and allocation, the approving vote is cited, and charges are prepared for posting.", notDoneWhen: "Charges were prepared for a special assessment whose required approval is not on record." },
    forbidden: ["prepare charges for an assessment that has not been adopted", "change a lot's allocation share without an amendment"],
    approvals: ["assessment charges before posting"],
    collaborators: ["hoa.board-packet-preparation", "hoa.reserve-study-tracking", "hoa.owner-and-member-account", "finance.charge-posting-preparation"],
  },
  {
    id: "hoa.association-delinquency",
    name: "Association Delinquency",
    domain: "hoa",
    boundary: "Moves each delinquent owner account through the steps of the association's adopted collection policy (reminders, policy late charges, payment plans) and prepares lien or collections referral items for a board decision. Stops at the prepared step; the board decides liens and referrals.",
    notThis: { specialist: "receivables.delinquency-detection", because: "Rent delinquency follows a lease and landlord-tenant rules; this follows the association's collection policy, the governing documents and association statutes, with lien steps reserved to the board." },
    triggers: ["unpaid dues", "delinquent owner", "lien", "collection policy", "past due assessment"],
    inputs: ["owner ledger", "adopted collection policy version", "prior notices and plans"],
    outputs: ["current policy step per account", "prepared notices", "lien or referral items for the board"],
    capabilities: ["assessment.read", "ledger.read", "collections.prepare", "notice.prepare", "board.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Each delinquent account is at the step the adopted policy prescribes, and any lien or referral has a recorded board decision.", notDoneWhen: "A lien or referral was prepared, but the board has not decided or the owner's required notice period has not run." },
    forbidden: ["apply late charges or interest beyond the adopted policy", "refer an account to collections or lien without a recorded board decision"],
    approvals: ["collection-policy notices", "lien or collections referral"],
    collaborators: ["hoa.assessment-coordination", "hoa.board-packet-preparation", "receivables.payment-plan-coordination"],
  },
  {
    id: "hoa.architectural-request",
    name: "Architectural Request",
    domain: "hoa",
    boundary: "Runs an owner's request to change their lot or home from completeness check through governing documents and design guidelines, required reviews and neighbor notices, and the committee or board packet, to the decision notice and post-work inspection. Prepares every step; the committee or board decides.",
    notThis: { specialist: "hoa.association-violation", because: "An architectural request asks permission before a change; a violation deals with a change or condition already made against the rules." },
    triggers: ["architectural request", "arc", "modification request", "design review", "fence", "paint color"],
    inputs: ["owner's application and plans", "governing documents and design guidelines", "committee membership and meeting dates"],
    outputs: ["completeness result", "review packet citing the applicable provisions", "decision notice draft", "follow-up inspection task"],
    capabilities: ["architectural_request.prepare", "association.read", "document.read", "board.prepare"],
    execution: "child_run",
    completion: { doneWhen: "The committee or board decision is recorded, a person sent the decision notice, and approved work has a completion inspection recorded before close.", notDoneWhen: "The request was approved but the post-work inspection never happened, or the notice went out before the decision was recorded." },
    forbidden: ["signal likely approval or denial to the owner", "treat a request as deemed approved by lapse of time without the governing documents' clause and dates"],
    approvals: ["decision notice to the owner"],
    collaborators: ["hoa.board-packet-preparation", "hoa.association-violation", "hoa.community-communication", "inspections.exterior-and-common-area-inspection"],
  },
  {
    id: "hoa.association-violation",
    name: "Association Violation",
    domain: "hoa",
    boundary: "Records an alleged breach of the governing documents with dated evidence and the rule cited, checks prior notices, and prepares courtesy, violation and hearing notices in the order the documents and statute require. Stops at a hearing packet or a verified cure; only a recorded board decision closes or fines.",
    notThis: { specialist: "lease-admin.lease-violation-workflow", because: "A lease violation enforces a residential lease against a resident under the manager's authority; this enforces governing documents against a member under board authority and due-process steps." },
    triggers: ["violation", "cc&r", "rules violation", "hearing", "fine", "courtesy notice"],
    inputs: ["report and dated evidence", "governing document provision", "prior notices for the lot", "enforcement policy"],
    outputs: ["violation record", "notices in required sequence", "hearing packet for the board"],
    capabilities: ["violation.prepare", "notice.prepare", "association.read", "document.read", "board.prepare"],
    execution: "child_run",
    completion: { doneWhen: "The violation carries the rule and dated evidence, each required notice was sent in sequence, and it ends with a recorded board decision or a verified cure.", notDoneWhen: "The violation was closed because the owner said it was fixed, with no verification or board decision." },
    forbidden: ["prepare a fine before the notice and hearing steps the governing documents require", "pursue one owner while an identical logged condition elsewhere is left without a recorded reason"],
    approvals: ["violation and hearing notices", "any fine"],
    collaborators: ["hoa.board-packet-preparation", "hoa.architectural-request", "inspections.exterior-and-common-area-inspection", "risk-compliance.reasonable-accommodation-workflow"],
  },
  {
    id: "hoa.board-packet-preparation",
    name: "Board Packet Preparation",
    domain: "hoa",
    boundary: "Assembles the board meeting packet (agenda, financials, delinquency summary, architectural requests, violations for hearing, bids, management report), stating for each item the decision requested and its supporting documents, and delivers it by the documents' deadline. Stops at delivery to directors.",
    notThis: { specialist: "hoa.meeting-and-minutes-preparation", because: "The packet prepares what the board will decide; meeting preparation handles the notice before and the minutes of what was decided." },
    triggers: ["board packet", "board meeting", "agenda items", "management report", "board materials"],
    inputs: ["open items needing decision", "financial statements", "bids and proposals", "meeting date"],
    outputs: ["board packet with a decision request per item", "open and executive-session sections separated"],
    capabilities: ["board.prepare", "association.read", "financial.statement.read", "document.read", "report.prepare"],
    execution: "child_run",
    completion: { doneWhen: "Every director received the packet by the governing documents' deadline, and each agenda item states the decision requested with supporting documents.", notDoneWhen: "The packet was assembled, but items needing a decision do not state the motion or the options." },
    forbidden: ["put executive-session or privileged material in the open-session packet", "include an individual owner's delinquency or violation detail in material members can see"],
    approvals: ["packet release to the board"],
    collaborators: ["hoa.meeting-and-minutes-preparation", "hoa.association-delinquency", "hoa.architectural-request", "hoa.association-vendor-and-project-coordination", "finance.budget-vs-actual"],
  },
  {
    id: "hoa.meeting-and-minutes-preparation",
    name: "Meeting & Minutes Preparation",
    domain: "hoa",
    boundary: "Prepares the meeting notice to the governing documents' timing, method and quorum rules, and drafts minutes from notes or a recording with each motion, mover, vote and action item. Stops at draft minutes awaiting board approval.",
    notThis: { specialist: "hoa.board-packet-preparation", because: "The packet carries the material for decisions; this makes the meeting valid through notice and records what was decided." },
    triggers: ["meeting notice", "minutes", "annual meeting", "quorum", "motion"],
    inputs: ["meeting type and date", "notice rules from the governing documents", "notes or recording"],
    outputs: ["meeting notice draft", "draft minutes with motions and votes", "action items with owners"],
    capabilities: ["board.prepare", "association.read", "communication.read", "document.read"],
    execution: "expertise",
    completion: { doneWhen: "Notice was issued within the required period, and draft minutes recording every motion, mover and vote await board approval with action items assigned.", notDoneWhen: "Minutes were drafted, but a motion's outcome is missing or inferred from discussion." },
    forbidden: ["record a vote or decision absent from the notes or recording", "put executive-session deliberations in open minutes"],
    approvals: ["meeting notice", "minutes approval by the board"],
    collaborators: ["hoa.board-packet-preparation", "hoa.community-communication", "hoa.owner-and-member-account"],
  },
  {
    id: "hoa.reserve-study-tracking",
    name: "Reserve Study Tracking",
    domain: "hoa",
    boundary: "Tracks the association's reserve study: each component's remaining life and cost, the funding plan against actual contributions, components coming due, and the study's update date, flagging shortfalls by the study's own measure. Stops at the variance report.",
    notThis: { specialist: "owner-services.property-reserve-monitor", because: "The property reserve monitor watches a rental owner's operating reserve balance; this tracks an association's component reserve study and its funding plan." },
    triggers: ["reserve study", "reserve funding", "percent funded", "component replacement", "reserve contribution"],
    inputs: ["reserve study and components", "reserve account balances", "adopted contribution schedule"],
    outputs: ["component schedule with due years", "funding plan variance", "study update alert"],
    capabilities: ["association.read", "budget.read", "financial.statement.read", "report.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Each component carries its study life and cost, contributions are compared with the funding plan, and the study update date has an alert.", notDoneWhen: "The reserve balance was reported without comparing it with the study's funding plan." },
    forbidden: ["change a component's life or cost without a new study or professional report", "describe reserves as adequate without the study's own funding measure"],
    approvals: [],
    collaborators: ["hoa.board-packet-preparation", "hoa.assessment-coordination", "hoa.association-vendor-and-project-coordination", "portfolio-strategy.capex-planning"],
  },
  {
    id: "hoa.association-vendor-and-project-coordination",
    name: "Association Vendor & Project Coordination",
    domain: "hoa",
    boundary: "Carries a common-area contract or capital project from scope (often a reserve component) through bids, board award under the association's contracting authority, progress and change orders, to verified completion and final invoice match. Stops at prepared awards and verified completion.",
    notThis: { specialist: "spend-vendor.bid-solicitation", because: "Bid solicitation runs the bid process itself; this carries the whole association project, including the board award and completion, under limits the governing documents set." },
    triggers: ["common area project", "roof replacement", "landscaping contract", "association vendor", "change order"],
    inputs: ["project scope", "bids", "management's delegated spend limit", "board decisions"],
    outputs: ["award item for the board", "project tracker", "completion verification and invoice match"],
    capabilities: ["vendor.read", "association.read", "board.prepare", "purchase_order.prepare", "work_order.read"],
    execution: "child_run",
    completion: { doneWhen: "The project has a board-approved contract, and completion is verified against the scope with the final invoice matched.", notDoneWhen: "A vendor was engaged on management's authority for spend the governing documents reserve to the board." },
    forbidden: ["commit the association above management's delegated limit", "split a project to stay under an approval threshold"],
    approvals: ["contract award", "change orders"],
    collaborators: ["spend-vendor.bid-solicitation", "spend-vendor.bid-comparison", "spend-vendor.vendor-insurance-and-coi-compliance", "hoa.reserve-study-tracking", "hoa.board-packet-preparation"],
  },
  {
    id: "hoa.community-communication",
    name: "Community Communication",
    domain: "hoa",
    boundary: "Prepares member-wide messages (rule changes, project disruptions, meeting notices, emergencies, newsletters) and delivers each approved message by the method every member is entitled to, recording delivery and re-sending failures. Stops at recorded delivery.",
    notThis: { specialist: "owner-services.owner-communication", because: "Owner communication speaks to one management client about their rental property; this addresses an association's members as a body under the governing documents' notice rules." },
    triggers: ["community notice", "newsletter", "all members", "rule change", "water shutoff", "announcement"],
    inputs: ["approved message", "member records with notice methods", "governing documents' notice rules"],
    outputs: ["delivery record per member", "failed deliveries re-sent by another permitted method"],
    capabilities: ["association.read", "communication.channels.read", "communication.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The approved message reached every entitled member by a permitted method, with failures re-sent and recorded.", notDoneWhen: "The message was posted or emailed, but members entitled to mailed notice were not reached." },
    forbidden: ["announce a board decision before it is recorded", "disclose an individual owner's violation, delinquency or dispute in a community message"],
    approvals: ["member-wide communication"],
    collaborators: ["hoa.owner-and-member-account", "hoa.meeting-and-minutes-preparation", "risk-compliance.fair-housing-guard"],
  },
];
