/** Inspections & Property Condition — 10 Aval Specialists, coordinated by Inspections & Property Condition Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "inspections.move-in-inspection",
    name: "Move-In Inspection",
    domain: "inspections",
    boundary: "Prepares and records the move-in condition report for a unit, room by room, with photos, and collects the resident's acknowledgement and any items they dispute. Stops at a signed or acknowledged baseline; it does not fix the defects it records.",
    notThis: { specialist: "inspections.move-out-inspection", because: "Move-in sets the baseline condition at the start of a tenancy; move-out compares the unit against that baseline at the end." },
    triggers: ["move-in inspection", "move-in checklist", "condition report", "walkthrough", "new resident"],
    inputs: ["unit and lease start", "workspace move-in checklist", "photos from the walkthrough", "resident's noted items"],
    outputs: ["room-by-room move-in condition report with photos", "resident acknowledgement and disputed items"],
    capabilities: ["unit.read", "lease.read", "inspection.read", "inspection.prepare", "document.read"],
    execution: "expertise",
    completion: { doneWhen: "The condition report is stored against the lease with photos for each room and the resident's acknowledgement or recorded refusal.", notDoneWhen: "The checklist was filled in but photos are missing for rooms or the resident never acknowledged it." },
    forbidden: ["mark an item as good condition where no photo or note supports it", "alter a report after the resident has acknowledged it without recording a revision"],
    approvals: [],
    collaborators: ["inspections.inspection-photo-and-document-review", "property-operations.move-in-move-out-coordination", "inspections.inspection-deficiency-triage"],
  },
  {
    id: "inspections.move-out-inspection",
    name: "Move-Out Inspection",
    domain: "inspections",
    boundary: "Records the unit's condition at move-out and compares it line by line with the move-in baseline, separating likely normal wear from damage for a person to decide. Stops at the compared report; deposit deductions and turn scope are other specialists' work.",
    notThis: { specialist: "turns.move-out-scope-intake", because: "Move-out scope intake turns the findings into make-ready work; this specialist produces the compared condition record those findings come from." },
    triggers: ["move-out inspection", "move out walkthrough", "damage", "wear and tear", "vacated"],
    inputs: ["move-in condition report", "move-out photos and notes", "lease and move-out date"],
    outputs: ["move-out report compared to the move-in baseline", "items flagged as possible damage versus wear, for review"],
    capabilities: ["unit.read", "lease.read", "inspection.read", "inspection.prepare", "document.read"],
    execution: "expertise",
    completion: { doneWhen: "Each move-in line item has a move-out condition with photo evidence and a wear-or-damage flag for review.", notDoneWhen: "Move-out photos were collected but not compared against the move-in baseline." },
    forbidden: ["decide that an item is chargeable damage", "compare against a baseline from a different tenancy"],
    approvals: ["classification of items as damage rather than normal wear"],
    collaborators: ["turns.move-out-scope-intake", "receivables.move-out-receivable-and-deposit-withholding", "lease-admin.move-out-obligation-review"],
  },
  {
    id: "inspections.periodic-property-inspection",
    name: "Periodic Property Inspection",
    domain: "inspections",
    boundary: "Runs the workspace's routine occupied-unit inspection, such as an annual or semi-annual check, against its checklist, and records findings with photos. Stops at the completed inspection record; entry basis, scheduling and repair of findings are handed to their owners.",
    notThis: { specialist: "inspections.exterior-and-common-area-inspection", because: "Periodic inspection covers the inside of occupied units; the exterior specialist covers grounds, roofs, parking and shared spaces." },
    triggers: ["annual inspection", "unit inspection", "routine inspection", "semi-annual", "housekeeping check"],
    inputs: ["units due for inspection", "workspace periodic checklist", "photos and notes from the visit", "entry basis on record"],
    outputs: ["completed inspection record per unit", "findings passed to deficiency triage"],
    capabilities: ["unit.read", "inspection.read", "inspection.prepare", "document.read"],
    execution: "expertise",
    completion: { doneWhen: "Every checklist item for the unit has a result with evidence and every failed item has been passed to deficiency triage.", notDoneWhen: "The visit happened but failed items were noted without being passed on." },
    forbidden: ["record an inspection of an occupied unit that has no recorded entry basis", "note a resident's belongings or lifestyle beyond what the checklist requires"],
    approvals: [],
    collaborators: ["inspections.inspection-scheduling", "inspections.inspection-deficiency-triage", "maintenance.permission-to-enter-coordination"],
  },
  {
    id: "inspections.exterior-and-common-area-inspection",
    name: "Exterior & Common Area Inspection",
    domain: "inspections",
    boundary: "Inspects grounds, building envelope, roofs, parking, lighting, stairs, amenities and other shared spaces against the property's exterior checklist, and records hazards and defects. Stops at the recorded findings; life-safety systems are coordinated separately.",
    notThis: { specialist: "inspections.periodic-property-inspection", because: "Periodic inspection covers the inside of individual units; this covers the parts of the property no single resident controls." },
    triggers: ["common area", "grounds", "exterior", "parking lot", "lighting", "trip hazard", "roof"],
    inputs: ["property and its common-area inventory", "exterior checklist", "photos and notes from the walk"],
    outputs: ["exterior and common-area findings with location and photos", "immediate hazards flagged for escalation"],
    capabilities: ["property.read", "inspection.read", "inspection.prepare", "document.read"],
    execution: "expertise",
    completion: { doneWhen: "Every checklist area has a result, and each hazard has been passed to triage or escalation with its location.", notDoneWhen: "A walk was logged but hazards were described without a location or were not passed on." },
    forbidden: ["leave a trip, fall or lighting hazard off the escalation list because it is minor-looking"],
    approvals: [],
    collaborators: ["inspections.inspection-deficiency-triage", "property-operations.property-incident-escalation", "inspections.life-safety-inspection-coordination"],
  },
  {
    id: "inspections.life-safety-inspection-coordination",
    name: "Life-Safety Inspection Coordination",
    domain: "inspections",
    boundary: "Tracks required life-safety inspections, such as fire alarms, sprinklers, extinguishers, elevators, backflow and smoke and CO detectors, arranges the licensed inspector, and files the certificate. Stops at coordination and record-keeping; the licensed inspector certifies.",
    notThis: { specialist: "inspections.inspection-scheduling", because: "Inspection scheduling books Aval's own inspections; this one tracks code-required inspections that a licensed outside inspector must perform and certify." },
    triggers: ["fire alarm", "sprinkler", "extinguisher", "elevator certificate", "backflow", "smoke detector", "fire marshal"],
    inputs: ["life-safety systems by property", "required inspection intervals for the jurisdiction", "licensed inspector vendors", "prior certificates"],
    outputs: ["due and overdue life-safety inspections", "inspector booking request", "filed certificates and reported deficiencies"],
    capabilities: ["property.read", "inspection.read", "compliance.read", "vendor.read", "document.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "Each required inspection has a current certificate from a licensed inspector filed, or an overdue alert routed to a named owner.", notDoneWhen: "An inspector was booked but no certificate has been received and filed." },
    forbidden: ["record a system as passed without a licensed inspector's certificate", "extend a due date the jurisdiction sets"],
    approvals: [],
    collaborators: ["risk-compliance.regulatory-calendar", "spend-vendor.vendor-search", "maintenance.preventive-maintenance", "inspections.inspection-deficiency-triage"],
  },
  {
    id: "inspections.inspection-deficiency-triage",
    name: "Inspection Deficiency Triage",
    domain: "inspections",
    boundary: "Sorts every failed inspection item by severity, such as life-safety, habitability, program-required or cosmetic, with a correction deadline, and routes it to maintenance, turns or a responsible party. Stops at routing; it does not open the repair itself or close the deficiency.",
    notThis: { specialist: "maintenance.emergency-maintenance-triage", because: "Emergency triage classifies incoming reports; deficiency triage classifies findings from an inspection and sets correction deadlines, often under program rules." },
    triggers: ["failed item", "deficiency", "finding", "correction needed", "failed inspection"],
    inputs: ["inspection findings", "severity rules and correction deadlines, including program rules such as NSPIRE", "property and unit"],
    outputs: ["deficiency records with severity and correction deadline", "routing to maintenance, turns or a named owner"],
    capabilities: ["inspection.read", "compliance.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "Each failed item is a deficiency record with severity, deadline and an owner who has received it.", notDoneWhen: "Findings were grouped by severity but no owner was assigned or notified." },
    forbidden: ["class a life-safety finding as cosmetic", "set a correction deadline later than the program or jurisdiction allows"],
    approvals: [],
    collaborators: ["maintenance.work-order-creation", "inspections.correction-follow-up", "affordable.nspire-and-inspection-readiness", "turns.turn-scope-creation"],
  },
  {
    id: "inspections.inspection-photo-and-document-review",
    name: "Inspection Photo & Document Review",
    domain: "inspections",
    boundary: "Checks that an inspection's evidence is complete and usable: each item has a legible photo or document, dated and tied to the right unit and item. Stops at an evidence-completeness result; it does not judge the condition shown.",
    notThis: { specialist: "inspections.inspection-deficiency-triage", because: "Deficiency triage decides how serious a failed item is; this only checks that the evidence behind every item exists and matches it." },
    triggers: ["missing photo", "evidence", "photos", "blurry", "inspection report upload"],
    inputs: ["inspection record and its items", "attached photos and documents with metadata"],
    outputs: ["evidence-completeness result per item", "list of items lacking or mismatched evidence"],
    capabilities: ["inspection.read", "document.read", "document.extract"],
    execution: "deterministic",
    completion: { doneWhen: "Every inspection item has a pass or fail evidence check and gaps are listed back to the inspector.", notDoneWhen: "Items without a photo were left unmarked, so they read as passed." },
    forbidden: ["treat an item without evidence as passed", "attach a photo from another unit or date to fill a gap"],
    approvals: [],
    collaborators: ["inspections.move-in-inspection", "inspections.move-out-inspection", "data-integrations.document-ingestion"],
  },
  {
    id: "inspections.correction-follow-up",
    name: "Correction Follow-Up",
    domain: "inspections",
    boundary: "Tracks each open deficiency to correction by its deadline, collects correction evidence, and closes the deficiency only when the evidence shows it corrected. Stops at closing or escalating the deficiency; the repair work belongs to maintenance or turns.",
    notThis: { specialist: "maintenance.completion-verification", because: "Completion verification closes maintenance work orders; correction follow-up closes inspection deficiencies, which may need re-inspection or program evidence rather than a work-order photo." },
    triggers: ["follow up deficiency", "correction deadline", "reinspection", "open findings", "cure period"],
    inputs: ["open deficiencies with deadlines", "linked work orders and their status", "correction photos or re-inspection results"],
    outputs: ["deficiencies closed with evidence", "escalations for deficiencies near or past deadline"],
    capabilities: ["inspection.read", "work_order.read", "document.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "Each deficiency is closed with correction evidence attached, or escalated to a named owner before its deadline passes.", notDoneWhen: "The linked work order was closed and the deficiency was closed with it, without its own correction evidence." },
    forbidden: ["close a deficiency because its work order is closed", "extend a correction deadline without recorded authority"],
    approvals: ["deadline extensions where the program or policy allows them"],
    collaborators: ["inspections.inspection-deficiency-triage", "maintenance.completion-verification", "inspections.inspection-scheduling"],
  },
  {
    id: "inspections.inspection-scheduling",
    name: "Inspection Scheduling",
    domain: "inspections",
    boundary: "Books Aval-run inspections and re-inspections, such as move-in, move-out, periodic and correction visits, against inspector availability, unit access and notice rules. Stops at a confirmed booking with its entry basis; it does not perform the inspection.",
    notThis: { specialist: "inspections.life-safety-inspection-coordination", because: "Life-safety coordination arranges outside licensed inspectors for code-required systems; this books the workspace's own inspection visits." },
    triggers: ["schedule inspection", "book inspection", "reinspection date", "inspection due"],
    inputs: ["inspections due by type", "inspector availability", "unit access and occupancy", "jurisdiction entry-notice rule"],
    outputs: ["confirmed inspection booking", "entry notice request where the unit is occupied"],
    capabilities: ["inspection.read", "unit.read", "occupancy.read", "staff.read", "inspection.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The inspection has a confirmed date, an assigned inspector and, for an occupied unit, a recorded entry basis.", notDoneWhen: "A date was proposed but the inspector did not confirm or no entry notice was arranged." },
    forbidden: ["book an occupied-unit inspection inside the jurisdiction's entry-notice period"],
    approvals: [],
    collaborators: ["maintenance.permission-to-enter-coordination", "property-operations.property-calendar", "inspections.periodic-property-inspection"],
  },
  {
    id: "inspections.property-condition-trend",
    name: "Property Condition Trend",
    domain: "inspections",
    boundary: "Reads inspection results for a property or portfolio over time and reports how condition scores and deficiency counts are moving, by system and category, with the inspections behind each figure. Stops at the trend report; capital decisions belong to portfolio strategy.",
    notThis: { specialist: "maintenance.repeat-issue-analysis", because: "Repeat-issue analysis reads work-order history for recurring faults; condition trend reads inspection results for how the property's condition is changing." },
    triggers: ["condition trend", "getting worse", "inspection history", "deficiency rate", "property condition"],
    inputs: ["inspection records across periods", "deficiency records by category", "reporting window"],
    outputs: ["condition trend by property, system and category", "list of inspections behind each figure"],
    capabilities: ["inspection.read", "analytics.read", "report.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The report names its window and inspection sources, and each trend figure traces to specific inspections.", notDoneWhen: "A trend was described from a single inspection or from periods with incomparable checklists." },
    forbidden: ["present a trend across checklists that changed without noting the change", "project a condition forecast as fact"],
    approvals: [],
    collaborators: ["portfolio-strategy.capex-planning", "maintenance.repeat-issue-analysis", "data-integrations.dashboard-and-kpi"],
  },
];
