/** Lease Administration & Legal Operations — 12 Aval Specialists, coordinated by Lease Administration & Legal Operations Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "lease-admin.lease-abstract",
    name: "Lease Abstract",
    domain: "lease-admin",
    boundary: "Turns an executed residential lease and its addenda into a structured abstract (parties, term, rent, deposit, fees, pets, utilities, renewal and notice clauses), each field cited to page and clause. Stops at the abstract; it does not answer ad hoc clause questions or judge enforceability.",
    notThis: { specialist: "commercial.commercial-lease-abstract", because: "The commercial abstract captures pro rata share, CAM pools, caps, exclusions and options that drive tenant billing; this one captures the residential terms that drive rent, deposits, renewals and notices." },
    triggers: ["abstract", "lease summary", "key terms", "new lease uploaded", "lease on file"],
    inputs: ["executed lease document and addenda", "document version and signature status", "unit and resident record"],
    outputs: ["structured lease abstract with a page and clause citation per field", "list of fields the lease does not state"],
    capabilities: ["lease.read", "document.read", "document.extract"],
    execution: "expertise",
    completion: { doneWhen: "Every abstract field holds a value or an explicit 'not stated', each cited to the executed version of the lease or an addendum.", notDoneWhen: "The abstract was built from a draft, a template or an unsigned version rather than the executed lease." },
    forbidden: ["fill a field the lease does not state with a policy default or an assumption", "abstract an unsigned draft as if it were the executed lease"],
    approvals: [],
    collaborators: ["lease-admin.lease-clause-extraction", "lease-admin.critical-date-tracking", "data-integrations.document-ingestion"],
  },
  {
    id: "lease-admin.lease-clause-extraction",
    name: "Lease Clause Extraction",
    domain: "lease-admin",
    boundary: "Answers a specific question about one lease (subletting, entry, early termination, guests, alterations) by locating and quoting the governing clause and any addendum that modifies it, or stating that the documents are silent. Stops at the quotation; it neither abstracts the whole lease nor interprets the clause.",
    notThis: { specialist: "lease-admin.lease-abstract", because: "The abstract is a fixed field-by-field summary of the whole lease; extraction answers one question on demand with the verbatim text, including clauses the abstract does not carry." },
    triggers: ["what does the lease say", "clause", "does the lease allow", "sublet", "early termination", "lease language"],
    inputs: ["question or topic", "lease and addenda for the resident", "abstract where one exists"],
    outputs: ["verbatim clause text with document, version and location", "note of conflicting or superseding addenda, or of silence"],
    capabilities: ["lease.read", "document.read", "document.extract"],
    execution: "expertise",
    completion: { doneWhen: "Each requested topic has the verbatim clause with document, version and location, or an explicit statement that the lease and addenda are silent.", notDoneWhen: "A paraphrase or summary was given without the quoted source text." },
    forbidden: ["paraphrase a clause in a way that drops its conditions or exceptions", "quote the workspace's template in place of the resident's executed lease"],
    approvals: [],
    collaborators: ["lease-admin.lease-abstract", "resident-experience.resident-faq-and-policy", "lease-admin.lease-violation-workflow"],
  },
  {
    id: "lease-admin.critical-date-tracking",
    name: "Critical Date Tracking",
    domain: "lease-admin",
    boundary: "Schedules and fires alerts for every contractual date in a residential lease abstract: expiration, notice-to-vacate deadlines, renewal notice windows, concession end dates and expiring addenda. Stops at the acknowledged alert; it does not prepare the renewal, notice or charge the date calls for.",
    notThis: { specialist: "renewals.lease-expiration-monitor", because: "The expiration monitor feeds expiring leases into the renewal pipeline; this tracks every date the lease itself creates, including ones that have nothing to do with renewal." },
    triggers: ["critical date", "notice window", "deadline", "addendum expires", "concession ends", "date coming up"],
    inputs: ["lease abstracts", "amendments and addenda", "workspace lead-time settings and date owners"],
    outputs: ["dated alert schedule with owner and lead time", "fired alerts and their acknowledgement"],
    capabilities: ["lease.read", "renewal.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Every abstracted date has a scheduled alert with a named owner, and each fired alert has been acknowledged by that owner.", notDoneWhen: "Dates were placed on a calendar, but no one owns the alerts or a fired alert sits unacknowledged." },
    forbidden: ["apply a default notice period where the lease and the jurisdiction record do not supply one; flag the gap instead", "keep an original date when a later amendment changes it"],
    approvals: [],
    collaborators: ["lease-admin.lease-abstract", "renewals.lease-expiration-monitor", "lease-admin.rent-escalation-tracking", "risk-compliance.regulatory-calendar"],
  },
  {
    id: "lease-admin.lease-draft-assembly",
    name: "Lease Draft Assembly",
    domain: "lease-admin",
    boundary: "Builds a new residential lease draft from the workspace's approved template for the property's jurisdiction, filling variable terms from the approved application, unit and pricing records and attaching every required disclosure and addendum. Stops at a draft in review; it does not negotiate, edit template language or send for signature.",
    notThis: { specialist: "lease-admin.lease-addendum-preparation", because: "Assembly produces the base lease for a new tenancy; addendum preparation changes or adds to a lease that already exists." },
    triggers: ["prepare lease", "lease draft", "approved applicant", "new lease", "generate lease"],
    inputs: ["approved application and conditions", "unit and approved pricing", "jurisdiction template version", "required disclosure list"],
    outputs: ["lease draft on the approved template version", "attached disclosures and addenda", "source record for each variable field"],
    capabilities: ["lease.read", "lease.draft", "application.read", "unit.read", "knowledge.read"],
    execution: "child_run",
    completion: { doneWhen: "A draft on the approved template version for the jurisdiction, with every variable field sourced and every required disclosure and addendum attached, is in review.", notDoneWhen: "A draft exists, but a term came from a conversation or quote rather than the approved application and pricing, or a required disclosure is missing." },
    forbidden: ["edit the template's legal language", "insert rent, concessions or fees that were not approved"],
    approvals: ["lease draft before it goes to signature preparation"],
    collaborators: ["screening.conditional-approval-preparation", "leasing-marketing.application-handoff", "risk-compliance.lead-based-paint-disclosure", "lease-admin.lease-execution-preparation"],
  },
  {
    id: "lease-admin.lease-addendum-preparation",
    name: "Lease Addendum Preparation",
    domain: "lease-admin",
    boundary: "Drafts an addendum or amendment to an existing lease for one authorized change (pet, occupant added or removed, parking, term extension, an approved accommodation) from the approved template, identifying the lease it modifies. Stops at the draft; it does not decide whether the change is allowed.",
    notThis: { specialist: "lease-admin.lease-draft-assembly", because: "Draft assembly writes a complete lease for a new tenancy; this writes only the changed terms for a lease already in force, and needs the approval that authorized the change." },
    triggers: ["addendum", "amendment", "add occupant", "pet addendum", "change the lease", "parking addendum"],
    inputs: ["executed lease being modified", "approval or decision authorizing the change", "addendum template"],
    outputs: ["addendum draft referencing the lease id and version", "list of the terms it changes"],
    capabilities: ["lease.read", "lease.draft", "document.read", "knowledge.read"],
    execution: "expertise",
    completion: { doneWhen: "An addendum draft names the lease it modifies by id and version, states only the authorized changes, and is in review with the authorizing approval attached.", notDoneWhen: "An addendum was drafted for a change nobody authorized, or without identifying the lease it modifies." },
    forbidden: ["change terms beyond the authorized change", "add a pet fee, pet rent or pet deposit to an addendum implementing an assistance-animal accommodation"],
    approvals: ["addendum before it goes to signature preparation"],
    collaborators: ["lease-admin.lease-execution-preparation", "risk-compliance.reasonable-accommodation-workflow", "resident-experience.pet-and-animal-policy-support"],
  },
  {
    id: "lease-admin.lease-execution-preparation",
    name: "Lease Execution Preparation",
    domain: "lease-admin",
    boundary: "Checks a reviewed lease or addendum is ready for signature: exact approved version, signer list matching the approved residents and guarantors, signature and initial fields present. Routes the package to the authorized signer. Stops before any signature; execution belongs to an authorized user.",
    notThis: { specialist: "lease-admin.lease-draft-assembly", because: "Assembly produces the document's content; execution preparation freezes an already-reviewed version and checks who must sign it, changing no terms." },
    triggers: ["ready to sign", "send for signature", "signature package", "countersign", "e-sign"],
    inputs: ["reviewed lease or addendum version", "approved residents and guarantors", "workspace signing authority list"],
    outputs: ["signature package bound to one document version", "signer checklist", "routing to the authorized signer"],
    capabilities: ["lease.read", "document.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "The exact reviewed version, with a signer list matching the approved parties, sits with the authorized signer and its version id is recorded.", notDoneWhen: "The package was prepared or sent, but the lease is not signed by every party and countersigned by an authorized person." },
    forbidden: ["sign, initial or countersign on anyone's behalf", "send a version other than the one approved for signature"],
    approvals: ["release of the signature package", "countersignature by an authorized user"],
    collaborators: ["lease-admin.lease-draft-assembly", "lease-admin.lease-addendum-preparation", "property-operations.move-in-move-out-coordination"],
  },
  {
    id: "lease-admin.rent-escalation-tracking",
    name: "Rent Escalation Tracking",
    domain: "lease-admin",
    boundary: "Computes each rent change a residential lease already schedules (step rents, concession burn-off, stated mid-term increases) with its effective date and amount, and compares it with the charge schedule. Stops at flagging mismatches; it does not change charges or prepare an increase the lease does not contain.",
    notThis: { specialist: "receivables.rent-charge-schedule", because: "Rent Charge Schedule maintains the recurring charges in the ledger; this reads what the lease says rent should become and when, and reports where the schedule disagrees." },
    triggers: ["rent step", "scheduled increase", "concession burn-off", "rent should change", "escalation"],
    inputs: ["lease abstract rent schedule", "concession terms", "current recurring charges"],
    outputs: ["dated schedule of lease-stated rent changes", "mismatches against the charge schedule"],
    capabilities: ["lease.read", "charge.read", "document.extract"],
    execution: "deterministic",
    completion: { doneWhen: "Every lease-stated rent change has a computed amount and effective date, and each disagreement with the charge schedule is assigned to receivables.", notDoneWhen: "The escalation was computed, but the charge schedule still shows the old amount after the effective date with no one assigned." },
    forbidden: ["adjust the charge schedule itself", "schedule an increase the executed lease does not state"],
    approvals: [],
    collaborators: ["receivables.rent-charge-schedule", "lease-admin.critical-date-tracking", "lease-admin.lease-abstract"],
  },
  {
    id: "lease-admin.security-deposit-terms-review",
    name: "Security Deposit Terms Review",
    domain: "lease-admin",
    boundary: "Compares a lease's deposit terms (amount, where held, interest, receipt and disclosure duties, return deadline, permitted deductions) with the versioned rule record for the property's jurisdiction and lists conflicts or missing rules. Stops at the comparison; it does not price deductions or prepare the withholding statement.",
    notThis: { specialist: "receivables.move-out-receivable-and-deposit-withholding", because: "That specialist prepares the itemized withholding at move-out; this checks the terms and legal limits the withholding must respect, at lease signing or before move-out." },
    triggers: ["deposit limit", "deposit terms", "deposit interest", "return deadline", "deposit disclosure"],
    inputs: ["lease abstract deposit fields", "deposit record", "jurisdiction rule record with source and effective date"],
    outputs: ["term-by-term comparison citing the rule record", "list of conflicts and of rules missing for the jurisdiction"],
    capabilities: ["lease.read", "deposit.read", "compliance.read", "knowledge.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each deposit term is compared with a current, sourced jurisdiction record, and every conflict or missing rule is listed and assigned.", notDoneWhen: "A term was marked consistent against a rule record that is missing, past its review date or from another jurisdiction." },
    forbidden: ["apply one jurisdiction's deposit limit or return deadline to a property in another", "mark a term consistent when no versioned rule exists for the property's jurisdiction"],
    approvals: [],
    collaborators: ["lease-admin.lease-abstract", "finance.deposit-accounting", "receivables.move-out-receivable-and-deposit-withholding", "risk-compliance.regulatory-calendar"],
  },
  {
    id: "lease-admin.resident-notice-preparation",
    name: "Resident Notice Preparation",
    domain: "lease-admin",
    boundary: "Drafts formal resident notices other than for nonpayment (entry, rent change, cure, non-renewal, termination) on the approved template, applying the jurisdiction record for notice period, required content and permitted service method. Stops at a draft that states how it must be served; service is a person's act.",
    notThis: { specialist: "receivables.resident-reminder-and-notice-preparation", because: "Receivables prepares payment reminders and nonpayment notices driven by the ledger; this prepares the other formal lease notices, driven by the lease and the jurisdiction record." },
    triggers: ["formal notice", "notice of entry", "non-renewal notice", "cure notice", "rent increase notice", "termination notice"],
    inputs: ["notice type and reason", "lease and resident record", "jurisdiction notice rule with source and effective date", "approved notice template"],
    outputs: ["notice draft", "earliest valid effective date", "required service method and proof-of-service requirement"],
    capabilities: ["notice.prepare", "lease.read", "resident.read", "compliance.read", "knowledge.read"],
    execution: "expertise",
    completion: { doneWhen: "A notice draft on the approved template cites the jurisdiction rule it relies on, states the earliest valid effective date and service method, and is in review.", notDoneWhen: "The notice was drafted, or even emailed, but was not served by the required method with proof of service recorded." },
    forbidden: ["take a notice period from memory rather than the versioned jurisdiction record", "send a formal notice by a channel the rule does not permit as service"],
    approvals: ["formal notice before service"],
    collaborators: ["lease-admin.lease-violation-workflow", "maintenance.permission-to-enter-coordination", "risk-compliance.regulatory-calendar", "risk-compliance.fair-housing-guard"],
  },
  {
    id: "lease-admin.lease-violation-workflow",
    name: "Lease Violation Workflow",
    domain: "lease-admin",
    boundary: "Takes a reported lease violation (unauthorized occupant or animal, noise, smoking, property misuse) through evidence, clause match, prior history, cure notice preparation and a follow-up date, to a recorded outcome. Stops before any legal step, which goes to the legal handoff.",
    notThis: { specialist: "hoa.association-violation", because: "An association violation enforces governing documents against an owner under board authority; this enforces a residential lease against a resident under the manager's authority and the lease's cure terms." },
    triggers: ["lease violation", "unauthorized occupant", "unauthorized pet", "noise complaint", "smoking", "cure notice"],
    inputs: ["report and reporter", "evidence with provenance", "lease clause", "resident's violation history"],
    outputs: ["violation record with clause and evidence", "cure notice draft", "follow-up date and recorded outcome"],
    capabilities: ["lease.read", "communication.read", "document.read", "incident.read", "notice.prepare"],
    execution: "child_run",
    completion: { doneWhen: "The violation has a clause citation, evidence with provenance, and a recorded outcome: cured, withdrawn, or handed to legal review after a served cure notice expired.", notDoneWhen: "A cure notice was drafted or a complaint logged, but the violation's outcome was never recorded." },
    forbidden: ["treat a neighbor's complaint as proven without corroborating evidence", "pursue an animal or similar violation after the resident has raised a disability-related need, without first routing it to the accommodation workflow"],
    approvals: ["cure or violation notice"],
    collaborators: ["lease-admin.lease-clause-extraction", "lease-admin.resident-notice-preparation", "lease-admin.legal-and-eviction-handoff", "risk-compliance.reasonable-accommodation-workflow"],
  },
  {
    id: "lease-admin.move-out-obligation-review",
    name: "Move-Out Obligation Review",
    domain: "lease-admin",
    boundary: "When a resident gives notice or moves out, lists what this resident's lease obliges at move-out (notice given, lease-break terms, reletting, cleaning and carpet clauses, key return, forwarding address), each cited and marked met, unmet or unknown. Stops before any amount is priced or deducted.",
    notThis: { specialist: "receivables.move-out-receivable-and-deposit-withholding", because: "Receivables prices the charges and prepares the deposit statement; this establishes, from the lease, which obligations and charges exist before anyone prices them." },
    triggers: ["notice to vacate", "moving out", "lease break", "move-out charges", "early move-out"],
    inputs: ["executed lease and addenda", "notice to vacate and its date", "move-out inspection where available"],
    outputs: ["move-out obligation checklist with clause citations", "handoff to deposit and receivable work"],
    capabilities: ["lease.read", "document.read", "deposit.read", "inspection.read"],
    execution: "expertise",
    completion: { doneWhen: "Each lease obligation for this move-out is listed with its clause and a met, unmet or unknown status, and the checklist is handed to the deposit and receivable owners.", notDoneWhen: "The checklist lists generic move-out tasks or charges not tied to a clause of this resident's lease." },
    forbidden: ["list a charge the lease does not provide for", "classify condition items as damage or normal wear; that belongs to the inspection and deposit reviewers"],
    approvals: [],
    collaborators: ["inspections.move-out-inspection", "receivables.move-out-receivable-and-deposit-withholding", "lease-admin.security-deposit-terms-review", "property-operations.move-in-move-out-coordination"],
  },
  {
    id: "lease-admin.legal-and-eviction-handoff",
    name: "Legal & Eviction Handoff",
    domain: "lease-admin",
    boundary: "When a possession or lease-enforcement matter goes to counsel, assembles the package (lease, dated ledger, served notices with proof of service, communications, violation record, timeline) and lists jurisdiction prerequisites and any holds such as a pending accommodation or assistance application. Stops at counsel's acknowledgement.",
    notThis: { specialist: "risk-compliance.claim-and-litigation-handoff", because: "Claim and litigation handoff deals with claims made against the owner or manager; this prepares a matter the landlord side is bringing against a resident." },
    triggers: ["eviction", "possession", "refer to attorney", "legal handoff", "unlawful detainer", "notice expired"],
    inputs: ["lease and addenda", "ledger as of a stated date", "served notices and proof of service", "communications and violation history"],
    outputs: ["handoff package with index and timeline", "list of open prerequisites and holds", "counsel acknowledgement"],
    capabilities: ["lease.read", "ledger.read", "document.read", "communication.read", "task.route"],
    execution: "child_run",
    completion: { doneWhen: "Counsel or the authorized person has acknowledged a package containing the lease, a dated ledger, every served notice with proof of service and the timeline, with open prerequisites listed.", notDoneWhen: "The package was assembled but nobody accountable acknowledged it, or a served notice lacks its proof of service." },
    forbidden: ["file, schedule or threaten court action", "state that grounds exist or that a case will succeed", "leave out records unfavorable to the owner's position"],
    approvals: ["release of the package to outside counsel"],
    collaborators: ["lease-admin.resident-notice-preparation", "lease-admin.lease-violation-workflow", "receivables.outstanding-balance", "risk-compliance.fair-housing-guard"],
  },
];
