/** Leasing & Marketing — 16 Aval Specialists, coordinated by Leasing & Marketing Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "leasing-marketing.lead-intake",
    name: "Lead Intake",
    domain: "leasing-marketing",
    boundary: "Turns an inbound inquiry from any channel (listing site, email, call, form) into one lead record: resolves the contact against existing leads, records source, channel and the unit asked about. Stops at a recorded lead; it does not reply, qualify or route.",
    notThis: { specialist: "leasing-marketing.lead-qualification", because: "Intake decides who the inquiry is from and records it once; qualification then compares what that lead said they need with what is available." },
    triggers: ["new inquiry", "ils lead", "contact form", "missed call", "guest card", "new prospect"],
    inputs: ["inbound inquiry message or call record", "existing lead records", "listing and unit referenced"],
    outputs: ["created or updated lead record with source and channel", "link from the inquiry to the lead"],
    capabilities: ["communication.read", "lead.read", "lead.create", "lead.update"],
    execution: "expertise",
    completion: { doneWhen: "Every inquiry in scope is linked to exactly one lead record that carries its source, channel and unit of interest.", notDoneWhen: "The inquiry was read but no lead record exists, or a second record was created for a prospect already on file." },
    forbidden: ["create a second lead record for a prospect who already has one", "record a protected characteristic, or a guess at one, on the lead record"],
    approvals: [],
    collaborators: ["leasing-marketing.lead-routing", "leasing-marketing.inquiry-response", "data-integrations.entity-deduplication", "market-revenue.lead-source-attribution"],
  },
  {
    id: "leasing-marketing.lead-qualification",
    name: "Lead Qualification",
    domain: "leasing-marketing",
    boundary: "Compares a lead's stated move-in date, size, budget and pet needs with current availability and the workspace's written qualifying questions, and sets the lead's stage. Stops before screening: qualification is fit with inventory, never an eligibility judgment.",
    notThis: { specialist: "screening.screening-criteria-enforcement", because: "Qualification matches stated needs to available units; criteria enforcement applies approved screening criteria to verified applicant data after an application." },
    triggers: ["qualify lead", "move-in date", "budget", "bedrooms", "is this lead a fit", "lead stage"],
    inputs: ["lead record and conversation", "available units and listings", "workspace qualifying questions"],
    outputs: ["lead stage with the stated needs recorded", "fit or no-fit against current availability, with the reason"],
    capabilities: ["lead.read", "lead.update", "unit.read", "listing.read", "knowledge.read"],
    execution: "expertise",
    completion: { doneWhen: "The lead carries a recorded stage and the stated needs it was qualified on, each taken from the prospect's own words.", notDoneWhen: "A stage was set from assumptions about the prospect rather than needs the prospect stated." },
    forbidden: ["ask about or qualify on source of income, familial status, disability or any other protected characteristic", "disqualify a lead on a question that is not in the workspace's written qualifying questions"],
    approvals: [],
    collaborators: ["leasing-marketing.unit-matching", "leasing-marketing.lead-intake", "leasing-marketing.prospect-nurture"],
  },
  {
    id: "leasing-marketing.listing-readiness",
    name: "Listing Readiness",
    domain: "leasing-marketing",
    boundary: "Checks a unit against everything a listing needs before it may go live: rent-ready status or an allowed pre-lease, approved asking rent, required fields, photos and disclosures. Returns pass or the named gaps; it does not write copy or publish.",
    notThis: { specialist: "leasing-marketing.listing-syndication", because: "Readiness decides whether a listing may be published at all; syndication performs the publication to channels once it has passed." },
    triggers: ["ready to list", "can we list", "listing checklist", "missing photos", "pre-lease", "listing gaps"],
    inputs: ["unit record and turn status", "approved asking rent", "listing record, photos and required disclosures"],
    outputs: ["pass or fail with each missing item named", "the source record behind each checked item"],
    capabilities: ["unit.read", "listing.read", "turn.read", "inspection.read", "compliance.read"],
    execution: "deterministic",
    completion: { doneWhen: "The listing carries a recorded pass, or every failed item is named and assigned to the specialist that fixes it.", notDoneWhen: "The listing was judged ready because its fields are filled while the unit's turn is not verified rent-ready." },
    forbidden: ["pass a unit whose turn is not verified rent-ready unless the workspace allows pre-leasing and the listing says so", "pass a listing that has no approved asking rent"],
    approvals: [],
    collaborators: ["turns.rent-ready-verification", "leasing-marketing.listing-copy-and-media-brief", "market-revenue.unit-pricing-recommendation", "leasing-marketing.listing-syndication"],
  },
  {
    id: "leasing-marketing.listing-syndication",
    name: "Listing Syndication",
    domain: "leasing-marketing",
    boundary: "Publishes, updates and takes down a ready listing on the channels the workspace has connected, and confirms each channel shows the approved rent and availability. Stops at channel state; it does not change the listing's content or price.",
    notThis: { specialist: "leasing-marketing.vacancy-marketing", because: "Syndication keeps channels in step with the approved listing; vacancy marketing decides what should change about a listing that is not leasing." },
    triggers: ["publish listing", "syndicate", "take down listing", "unit leased", "listing out of date", "zillow", "apartments.com"],
    inputs: ["listing that passed readiness", "connected marketing channels", "unit leasing status"],
    outputs: ["per-channel publication, update or removal", "per-channel confirmation of what is live"],
    capabilities: ["listing.read", "listing.publish", "marketing.channels.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every selected channel is confirmed to show the approved listing, and every leased unit is confirmed removed.", notDoneWhen: "A publish call was accepted but the channel has not been confirmed, or a leased unit is still live somewhere." },
    forbidden: ["publish a listing that has not passed listing readiness", "publish a rent, concession or date on one channel that differs from the approved listing record"],
    approvals: ["publication to a paid channel that carries a cost"],
    collaborators: ["leasing-marketing.listing-readiness", "leasing-marketing.vacancy-marketing", "data-integrations.provider-api-health"],
  },
  {
    id: "leasing-marketing.listing-copy-and-media-brief",
    name: "Listing Copy & Media Brief",
    domain: "leasing-marketing",
    boundary: "Drafts the listing description and a shot list for photos, video or a 3D tour from the unit and property records, with Fair Housing language checked. Stops at a draft for review; it does not set price, publish or describe who the unit suits.",
    notThis: { specialist: "leasing-marketing.listing-readiness", because: "The brief produces the words and media plan; readiness checks that those and every other listing requirement are present before publication." },
    triggers: ["listing description", "write the listing", "photo shot list", "listing copy", "marketing photos"],
    inputs: ["unit and property attributes", "amenities on record", "workspace brand and disclosure requirements"],
    outputs: ["draft listing copy citing the attribute behind each claim", "photo and media shot list"],
    capabilities: ["unit.read", "property.read", "listing.read", "listing.prepare", "fair_housing.review"],
    execution: "expertise",
    completion: { doneWhen: "A person has approved copy in which every feature claimed is on the unit or property record.", notDoneWhen: "Copy was drafted but not reviewed, or it states a feature the records do not show." },
    forbidden: ["describe an ideal resident or the make-up of the neighbourhood (for example 'perfect for young professionals' or 'quiet adult building')", "state an amenity, feature or square footage the unit record does not support"],
    approvals: ["listing copy before publication"],
    collaborators: ["risk-compliance.fair-housing-guard", "leasing-marketing.listing-readiness", "leasing-marketing.vacancy-marketing"],
  },
  {
    id: "leasing-marketing.inquiry-response",
    name: "Inquiry Response",
    domain: "leasing-marketing",
    boundary: "Prepares the reply to a specific prospect question from current approved property data: availability, rent shown on the listing, fees, policies and amenities. Stops at the answer; a tour request goes to tour scheduling, and a question the data cannot answer goes to staff.",
    notThis: { specialist: "leasing-marketing.prospect-nurture", because: "Inquiry response answers a question the prospect just asked; nurture starts contact with prospects who have gone quiet." },
    triggers: ["prospect question", "is it available", "how much is rent", "are pets allowed", "reply to lead", "inquiry"],
    inputs: ["prospect message and thread", "listing and unit records", "approved property policies and fees"],
    outputs: ["reply draft citing the record behind each answer", "handoff to tour scheduling or staff where needed"],
    capabilities: ["communication.read", "lead.read", "listing.read", "unit.read", "knowledge.read", "prospect.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The prospect has received a reviewed reply that answers each question asked or says who will answer it.", notDoneWhen: "A reply was drafted but not sent, or it skipped a question the prospect asked." },
    forbidden: ["answer questions about neighbourhood safety, schools or who lives in the building", "guess an answer the approved property data does not contain instead of routing it to staff"],
    approvals: ["prospect reply before sending, where the communication policy requires review"],
    collaborators: ["leasing-marketing.tour-scheduling", "leasing-marketing.unit-matching", "risk-compliance.fair-housing-guard"],
  },
  {
    id: "leasing-marketing.tour-scheduling",
    name: "Tour Scheduling",
    domain: "leasing-marketing",
    boundary: "Books, reschedules and cancels agent-led tours against staff and unit availability, confirms the time with the prospect, and records whether the tour happened. Stops at the tour record; self-guided access and post-tour follow-up belong to siblings.",
    notThis: { specialist: "leasing-marketing.self-guided-tour-coordination", because: "Tour scheduling books a staff member's time; self-guided coordination arranges identity checks and time-bound access for a tour with no staff present." },
    triggers: ["book a tour", "schedule showing", "reschedule tour", "cancel tour", "viewing", "no-show"],
    inputs: ["lead and requested times", "staff calendars", "unit showing availability"],
    outputs: ["booked tour with time, unit and assigned staff", "confirmation to the prospect", "tour outcome: completed, no-show or cancelled"],
    capabilities: ["showing.read", "showing.schedule", "lead.read", "lead.update", "staff.read"],
    execution: "expertise",
    completion: { doneWhen: "The tour is on the calendar with a prospect-confirmed time and an assigned person, and after the slot its outcome is recorded.", notDoneWhen: "A time was proposed but not confirmed, or a scheduled tour is counted as a completed one." },
    forbidden: ["book a tour of a unit that is not available to show", "offer prospects different tour times for any reason other than staff and unit availability"],
    approvals: [],
    collaborators: ["leasing-marketing.self-guided-tour-coordination", "leasing-marketing.inquiry-response", "leasing-marketing.prospect-nurture", "people-operations.staff-task-routing"],
  },
  {
    id: "leasing-marketing.self-guided-tour-coordination",
    name: "Self-Guided Tour Coordination",
    domain: "leasing-marketing",
    boundary: "Arranges a tour with no staff present: confirms the workspace's self-tour identity check is complete, requests an access window matching the booking, and confirms access ended. Stops at the unit door; it never grants access to an occupied unit.",
    notThis: { specialist: "leasing-marketing.tour-scheduling", because: "Tour scheduling books staff time for a guided tour; this handles the identity check and time-bound access a self-guided tour needs instead." },
    triggers: ["self-guided tour", "self tour", "tour on my own", "lockbox", "smart lock tour", "access code for tour"],
    inputs: ["tour booking", "self-tour identity check result", "unit vacancy and access device records"],
    outputs: ["access window request tied to the booking", "confirmation that access opened and expired as booked"],
    capabilities: ["showing.read", "showing.schedule", "lead.read", "unit.read", "key_access.read"],
    execution: "expertise",
    completion: { doneWhen: "The identity check passed, the access window matched the booking, and its expiry after the tour is recorded.", notDoneWhen: "An access code was sent but the identity check or the window's expiry is not on record." },
    forbidden: ["issue access before the workspace's self-tour identity check is complete", "give an access window longer than the booked tour, or reuse a code between prospects"],
    approvals: [],
    collaborators: ["leasing-marketing.tour-scheduling", "turns.key-and-access-reset", "property-operations.key-and-access-inventory"],
  },
  {
    id: "leasing-marketing.prospect-nurture",
    name: "Prospect Nurture",
    domain: "leasing-marketing",
    boundary: "Follows up leads that have not toured or applied, on the workspace's cadence for their stage, until they book, apply, decline or ask to stop. Stops when the lead has a next step or a closed reason; it does not answer new questions or book tours itself.",
    notThis: { specialist: "leasing-marketing.inquiry-response", because: "Nurture restarts contact the prospect has let lapse; inquiry response answers a question the prospect has just asked." },
    triggers: ["follow up", "gone quiet", "no response", "cold lead", "nurture", "after tour follow-up"],
    inputs: ["open leads and their stages", "last contact dates", "workspace follow-up cadence and opt-outs"],
    outputs: ["follow-up drafts on cadence", "next step or closed reason on each lead"],
    capabilities: ["lead.read", "lead.update", "communication.read", "prospect.message.prepare", "leasing.funnel.read"],
    execution: "expertise",
    completion: { doneWhen: "Every open lead in scope has a scheduled next contact or a recorded closed reason (booked, applied, lost or opted out).", notDoneWhen: "A follow-up was drafted but the lead has no next step and no closed reason." },
    forbidden: ["message a prospect who has opted out or asked not to be contacted", "vary follow-up offers or cadence between prospects by anything other than stage and stated preference"],
    approvals: ["nurture messages before sending, where the communication policy requires review"],
    collaborators: ["leasing-marketing.tour-scheduling", "leasing-marketing.application-handoff", "leasing-marketing.leasing-crm-hygiene"],
  },
  {
    id: "leasing-marketing.unit-matching",
    name: "Unit Matching",
    domain: "leasing-marketing",
    boundary: "Filters available and soon-available units against the requirements a prospect stated (size, move-in date, budget, pets, requested accessibility features) and returns every match with the reason it matched. Stops at the options; it does not hold a unit or quote beyond the listing.",
    notThis: { specialist: "leasing-marketing.lead-qualification", because: "Qualification sets whether any inventory fits the lead; matching returns the specific units that do." },
    triggers: ["which units", "what's available", "match units", "options for", "two bedroom available", "move in by"],
    inputs: ["prospect's stated requirements", "available and notice units with attributes", "current listings"],
    outputs: ["all matching units with the matched requirement per unit", "near matches with the requirement each misses"],
    capabilities: ["unit.read", "listing.read", "lead.read", "occupancy.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every available unit meeting the stated requirements is on the returned list with its reason.", notDoneWhen: "A shortlist was returned that omits an available unit meeting the stated requirements." },
    forbidden: ["narrow or order units by anything the prospect did not state, such as who lives on a floor or in a building", "withhold an available unit that meets the stated requirements"],
    approvals: [],
    collaborators: ["leasing-marketing.lead-qualification", "leasing-marketing.tour-scheduling", "leasing-marketing.inquiry-response"],
  },
  {
    id: "leasing-marketing.lead-routing",
    name: "Lead Routing",
    domain: "leasing-marketing",
    boundary: "Assigns each new or reopened lead an owner under the workspace's leasing routing rules (property, stated language preference, hours, workload) and records the owner on the lead. Stops at a named owner; it does not contact the prospect.",
    notThis: { specialist: "people-operations.staff-task-routing", because: "Staff task routing assigns internal operational tasks; lead routing assigns prospect ownership under the leasing rules and records it on the lead." },
    triggers: ["assign lead", "who owns this lead", "unassigned lead", "route lead", "round robin", "reassign prospect"],
    inputs: ["lead record", "workspace leasing routing rules", "staff roster and availability"],
    outputs: ["lead owner recorded on the lead", "the routing rule that selected the owner"],
    capabilities: ["lead.read", "lead.update", "staff.read"],
    execution: "deterministic",
    completion: { doneWhen: "The lead has a named owner, selected by a recorded rule, who has acknowledged it within the response target.", notDoneWhen: "A rule ran but matched nobody and the lead was left without an owner." },
    forbidden: ["route by a prospect's name, accent or any other proxy for national origin or another protected characteristic", "leave a lead unowned because no routing rule matched"],
    approvals: [],
    collaborators: ["leasing-marketing.lead-intake", "people-operations.workload-balancing", "people-operations.staff-task-routing"],
  },
  {
    id: "leasing-marketing.leasing-crm-hygiene",
    name: "Leasing CRM Hygiene",
    domain: "leasing-marketing",
    boundary: "Finds stale, duplicate and incomplete lead records (no stage, no source, no owner, no activity past the workspace threshold) and prepares the corrections. Stops at a correction set; merges and bulk closures wait for a person.",
    notThis: { specialist: "data-integrations.entity-deduplication", because: "Entity deduplication resolves duplicate people and properties across systems; CRM hygiene keeps the leasing pipeline's stages, owners and sources accurate." },
    triggers: ["clean up leads", "duplicate leads", "stale leads", "pipeline hygiene", "leads with no owner", "missing source"],
    inputs: ["lead records and activity history", "workspace staleness thresholds", "data conflict records"],
    outputs: ["list of records needing correction with the reason for each", "prepared merges, closures and field fixes"],
    capabilities: ["lead.read", "lead.update", "leasing.funnel.read", "data.conflicts.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every flagged record is corrected, merged with approval, or closed with a recorded reason.", notDoneWhen: "A hygiene report was produced but the flagged records are unchanged." },
    forbidden: ["delete a lead's communication history to tidy the pipeline", "close a lead as lost without a recorded reason"],
    approvals: ["merge of two lead records", "bulk closure of stale leads"],
    collaborators: ["data-integrations.entity-deduplication", "leasing-marketing.lead-routing", "market-revenue.lead-source-attribution"],
  },
  {
    id: "leasing-marketing.application-handoff",
    name: "Application Handoff",
    domain: "leasing-marketing",
    boundary: "Sends the application for the unit a prospect chose, tracks it to submission, and passes the submitted application into screening's completeness check. Stops at the handoff; it does not assess the applicant or the application's contents.",
    notThis: { specialist: "screening.application-completeness", because: "Handoff gets a submitted application into screening; completeness is screening's first check of what that application contains." },
    triggers: ["send application", "ready to apply", "application link", "started application", "application submitted"],
    inputs: ["lead and chosen unit", "application workflow for the property", "application status"],
    outputs: ["application sent to the prospect", "submitted application linked to the lead and assigned to screening"],
    capabilities: ["lead.read", "lead.update", "application.read", "application.send"],
    execution: "deterministic",
    completion: { doneWhen: "A submitted application is linked to the lead and accepted into screening's completeness check.", notDoneWhen: "The application link was sent but nothing was submitted, or a submission sits unassigned." },
    forbidden: ["collect Social Security numbers, pay stubs or other screening data through messages instead of the application workflow", "send an application for a unit the records do not show as available"],
    approvals: [],
    collaborators: ["screening.application-completeness", "leasing-marketing.prospect-nurture", "leasing-marketing.tour-scheduling"],
  },
  {
    id: "leasing-marketing.lease-up-campaign",
    name: "Lease-Up Campaign",
    domain: "leasing-marketing",
    boundary: "Plans and tracks the marketing campaign for a new or repositioned property against its lease-up pace targets: channel mix, budget, weekly traffic and conversion goals, and weekly re-planning. Stops at the plan and its reporting; pricing and concessions are revenue decisions.",
    notThis: { specialist: "leasing-marketing.vacancy-marketing", because: "A lease-up campaign fills a whole property to a pace target; vacancy marketing works why individual units in a stabilised property are not leasing." },
    triggers: ["lease-up", "new construction", "grand opening", "absorption target", "campaign plan", "pre-leasing campaign"],
    inputs: ["pace targets and delivery schedule", "funnel and velocity data", "channel performance and marketing budget"],
    outputs: ["campaign plan with channels, budget and weekly targets", "weekly pace report with the plan changes proposed"],
    capabilities: ["leasing.funnel.read", "leasing.velocity.read", "marketing.channels.read", "occupancy.read", "listing.read", "report.prepare"],
    execution: "child_run",
    completion: { doneWhen: "An approved plan is running and each week's pace against target is reported with a decided change or a decision to hold.", notDoneWhen: "A plan was written but not approved, or pace fell behind with no change decided." },
    forbidden: ["set or change unit pricing or concessions", "use a competitor's nonpublic pricing, concession or occupancy data in planning", "commit marketing spend that has not been approved"],
    approvals: ["campaign plan and channel budget", "mid-campaign budget changes"],
    collaborators: ["market-revenue.lease-up-pace-analysis", "market-revenue.concession-analysis", "leasing-marketing.listing-syndication", "leasing-marketing.vacancy-marketing"],
  },
  {
    id: "leasing-marketing.vacancy-marketing",
    name: "Vacancy Marketing",
    domain: "leasing-marketing",
    boundary: "Diagnoses where an aged vacancy in a stabilised property is losing prospects (views, inquiries, tours or applications) and prepares specific changes to copy, photos or channels, or a request for a pricing review. Stops at recommended changes; it does not edit price.",
    notThis: { specialist: "leasing-marketing.lease-up-campaign", because: "Vacancy marketing works one aged unit's funnel; a lease-up campaign plans a whole property's absorption." },
    triggers: ["not leasing", "aged vacancy", "days on market", "no inquiries", "low traffic", "why isn't this unit renting"],
    inputs: ["listing and its channel performance", "unit funnel and velocity", "days vacant"],
    outputs: ["the funnel stage where prospects drop, with the evidence", "specific listing, media or channel changes, or a pricing review request"],
    capabilities: ["listing.read", "leasing.funnel.read", "leasing.velocity.read", "marketing.channels.read", "unit.read"],
    execution: "expertise",
    completion: { doneWhen: "Each aged vacancy in scope has a diagnosed drop-off stage and each proposed change is recorded as made or declined.", notDoneWhen: "A recommendation was written but nobody has acted on it or declined it." },
    forbidden: ["change a listing's rent or concession instead of requesting a pricing review", "remove Fair Housing or required disclosure language to shorten a listing"],
    approvals: ["listing changes proposed for an aged vacancy"],
    collaborators: ["leasing-marketing.listing-copy-and-media-brief", "market-revenue.unit-pricing-recommendation", "market-revenue.lead-source-attribution", "leasing-marketing.listing-syndication"],
  },
  {
    id: "leasing-marketing.broker-and-locator-coordination",
    name: "Broker & Locator Coordination",
    domain: "leasing-marketing",
    boundary: "Registers a cooperating broker's or apartment locator's referral, checks it against first-contact records and the workspace's referral agreement, and prepares the commission eligibility finding. Stops at the finding; commission approval and payment belong to spend operations.",
    notThis: { specialist: "leasing-marketing.lead-intake", because: "Intake records a prospect; this records who referred the prospect and whether that referral earns a commission under the agreement." },
    triggers: ["broker referral", "locator", "cooperating broker", "referral fee", "commission claim", "co-broke"],
    inputs: ["referral registration", "lead first-contact history", "workspace broker and locator agreements", "executed lease"],
    outputs: ["referral recorded on the lead", "commission eligibility finding with the evidence"],
    capabilities: ["lead.read", "lead.update", "communication.read", "document.read", "lease.read"],
    execution: "expertise",
    completion: { doneWhen: "Each referral is recorded, and each claim has an eligibility finding a person has accepted or rejected.", notDoneWhen: "A commission claim was received and acknowledged but has no finding against the agreement." },
    forbidden: ["promise a commission the referral agreement does not provide", "share another prospect's details or the owner's pricing strategy with a broker or locator"],
    approvals: ["commission eligibility for a referral"],
    collaborators: ["leasing-marketing.lead-intake", "spend-vendor.approval-routing", "market-revenue.lead-source-attribution"],
  },
];
