/** Maintenance & Facilities — 18 Aval Specialists, coordinated by Maintenance & Facilities Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "maintenance.service-request-intake",
    name: "Service Request Intake",
    domain: "maintenance",
    boundary: "Turns a maintenance report from any channel into one structured service request: unit, location in the unit, symptom, photos, access notes and reporter. Stops once the request is recorded and handed to triage; it does not classify urgency or open a work order.",
    notThis: { specialist: "resident-experience.maintenance-request-intake", because: "The resident-experience intake owns the conversation with the resident; this one owns the structured maintenance record that the conversation, a staff note or an inspection finding produces." },
    triggers: ["service request", "something broke", "not working", "repair", "leak", "maintenance request"],
    inputs: ["report text, photos or call notes", "property and unit context", "reporter identity and contact channel"],
    outputs: ["structured service request with unit, location, symptom and access notes", "list of missing details still to collect"],
    capabilities: ["maintenance.request.read", "communication.read", "unit.read", "maintenance.request.create"],
    execution: "expertise",
    completion: { doneWhen: "A service request exists with unit, symptom and reporter recorded, and it has been passed to emergency triage.", notDoneWhen: "The report was acknowledged to the resident but no request record exists, or the request skipped triage." },
    forbidden: ["record a request against a unit the reporter was not tied to without flagging the mismatch", "discard photos or wording the reporter supplied"],
    approvals: [],
    collaborators: ["maintenance.emergency-maintenance-triage", "resident-experience.maintenance-request-intake", "maintenance.work-order-creation"],
  },
  {
    id: "maintenance.emergency-maintenance-triage",
    name: "Emergency Maintenance Triage",
    domain: "maintenance",
    boundary: "Decides whether an incoming maintenance report is an emergency under the workspace's emergency categories and routes it to the emergency procedure. Stops at classification and routing; it does not diagnose the fault or schedule the repair.",
    notThis: { specialist: "maintenance.work-order-prioritization", because: "Prioritization ranks non-emergency work already in the queue; triage decides, first, whether the report leaves the normal queue at all." },
    triggers: ["gas", "smoke", "flood", "no heat", "sparking", "lockout", "emergency"],
    inputs: ["maintenance report text", "unit and property", "workspace emergency categories and SOP"],
    outputs: ["emergency or non-emergency classification with the matched category", "routing to on-call person or emergency service"],
    capabilities: ["maintenance.request.read", "communication.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "The report carries a recorded classification and, if an emergency, a named person or service has acknowledged it.", notDoneWhen: "A classification was suggested but nobody accountable has acknowledged an emergency." },
    forbidden: ["tell a resident to investigate or repair a gas, electrical or structural hazard", "downgrade a report the SOP classes as an emergency"],
    approvals: [],
    collaborators: ["maintenance.work-order-creation", "people-operations.on-call-schedule", "risk-compliance.incident-intake"],
  },
  {
    id: "maintenance.resident-troubleshooting",
    name: "Resident Troubleshooting",
    domain: "maintenance",
    boundary: "Walks a resident through the workspace's approved, safe self-checks for non-emergency issues, such as a tripped GFCI reset, a thermostat setting or a clogged disposal reset, to resolve or sharpen the request. Stops at the approved checklist and hands anything unresolved to a work order.",
    notThis: { specialist: "maintenance.emergency-maintenance-triage", because: "Triage decides whether a report is an emergency; troubleshooting only starts after triage has cleared it as non-emergency, and never on a hazard." },
    triggers: ["tripped breaker", "thermostat", "garbage disposal", "reset", "pilot light", "no hot water", "toilet running"],
    inputs: ["non-emergency service request", "workspace-approved troubleshooting steps for the symptom", "resident replies"],
    outputs: ["resolved note, or refined symptom with steps already tried", "recommendation to open a work order"],
    capabilities: ["maintenance.request.read", "knowledge.read", "sop.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The resident confirmed the issue is resolved, or the request records the steps tried and has moved to work order creation.", notDoneWhen: "Steps were sent to the resident but nobody confirmed the result and the request was left open without a work order." },
    forbidden: ["suggest a step that is not in the workspace's approved troubleshooting list", "ask a resident to open a panel, relight gas equipment or handle wiring", "close a request because the resident stopped replying"],
    approvals: [],
    collaborators: ["maintenance.work-order-creation", "resident-experience.resident-inbox", "people-operations.sop-and-knowledge-operations"],
  },
  {
    id: "maintenance.work-order-creation",
    name: "Work Order Creation",
    domain: "maintenance",
    boundary: "Creates the work order from a triaged service request in Aval or the connected PMS, with property, unit, category, description, priority and permission-to-enter status. Stops once the work order exists and is linked to the request; it does not pick who does the work.",
    notThis: { specialist: "maintenance.service-request-intake", because: "Intake records what was reported; creation turns a triaged request into the actionable work order that staff or a vendor can be assigned to." },
    triggers: ["create work order", "open a ticket", "log the repair", "work order"],
    inputs: ["triaged service request", "property and unit scope", "workspace work-order categories", "PMS capability for work-order writes"],
    outputs: ["work order id in Aval or the PMS", "link between request and work order"],
    capabilities: ["maintenance.request.read", "work_order.read", "work_order.create"],
    execution: "expertise",
    completion: { doneWhen: "A work order id exists in the system of record, linked to the request, with category and priority set.", notDoneWhen: "A maintenance request exists but no work order was written, or the PMS write failed and was reported as created." },
    forbidden: ["create a duplicate work order when an open one covers the same unit and symptom", "write a work order into a property outside the caller's scope"],
    approvals: [],
    collaborators: ["maintenance.work-order-prioritization", "maintenance.permission-to-enter-coordination", "data-integrations.pms-synchronization"],
  },
  {
    id: "maintenance.work-order-prioritization",
    name: "Work Order Prioritization",
    domain: "maintenance",
    boundary: "Ranks open non-emergency work orders by habitability impact, SLA due time, resident vulnerability flags the workspace records and resource availability, and sets the priority field. Stops at ordering the queue; it does not assign or schedule.",
    notThis: { specialist: "maintenance.maintenance-sla-monitor", because: "The SLA monitor reports which orders are breaching; prioritization decides the order of work, using SLA status as one input among several." },
    triggers: ["priority", "what first", "backlog", "queue", "urgent but not emergency"],
    inputs: ["open work orders", "workspace priority rules and SLA targets", "habitability categories"],
    outputs: ["ranked queue with a stated reason per order", "priority updates on work orders"],
    capabilities: ["work_order.read", "maintenance.read", "sop.read", "work_order.update"],
    execution: "expertise",
    completion: { doneWhen: "Every open work order in scope carries a priority and a recorded reason.", notDoneWhen: "A ranked list was produced in chat but the work orders' priority fields were not updated." },
    forbidden: ["rank by protected characteristics or anything that proxies for them", "lower the priority of a habitability issue to clear a backlog"],
    approvals: [],
    collaborators: ["maintenance.maintenance-sla-monitor", "maintenance.technician-assignment", "risk-compliance.fair-housing-guard"],
  },
  {
    id: "maintenance.technician-assignment",
    name: "Technician Assignment",
    domain: "maintenance",
    boundary: "Assigns a prioritized work order to an in-house technician by trade, certification, property coverage and current load. Stops at the assignment and the technician's acceptance; when no qualified in-house technician is available it hands off to vendor dispatch.",
    notThis: { specialist: "maintenance.vendor-dispatch", because: "Technician assignment uses the workspace's own staff; vendor dispatch sends an outside company and carries insurance and spend checks staff assignment does not." },
    triggers: ["assign tech", "who can take this", "in-house", "technician", "maintenance staff"],
    inputs: ["prioritized work order", "technician roster with trades and certifications", "current workloads and on-call schedule"],
    outputs: ["work order assigned to a named technician", "handoff to vendor dispatch when no qualified technician is free"],
    capabilities: ["work_order.read", "staff.read", "work_order.update", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "The work order names an assigned technician who has accepted it, or it has been handed to vendor dispatch with the reason.", notDoneWhen: "A technician was named on the order but has not accepted it." },
    forbidden: ["assign licensed-trade work to a technician without the required licence or certification on record"],
    approvals: [],
    collaborators: ["maintenance.vendor-dispatch", "people-operations.workload-balancing", "people-operations.on-call-schedule", "maintenance.maintenance-scheduling"],
  },
  {
    id: "maintenance.vendor-dispatch",
    name: "Vendor Dispatch",
    domain: "maintenance",
    boundary: "Sends a work order to an outside vendor after confirming the vendor is approved, insured for the trade and within the spend limit, then tracks the vendor's acceptance. Stops at vendor acceptance; the repair itself and its verification belong to later steps.",
    notThis: { specialist: "maintenance.technician-assignment", because: "Dispatch sends outside vendors and must clear insurance, approval and spend checks; technician assignment routes to the workspace's own staff." },
    triggers: ["dispatch", "send a vendor", "call the plumber", "vendor", "contractor"],
    inputs: ["work order", "approved vendor list", "vendor insurance status", "spend threshold and estimate"],
    outputs: ["dispatch sent to the vendor", "vendor acceptance or decline recorded on the work order"],
    capabilities: ["work_order.read", "vendor.read", "vendor.insurance.read", "vendor.dispatch", "work_order.update"],
    execution: "expertise",
    completion: { doneWhen: "The vendor has accepted the dispatch and the acceptance is recorded on the work order.", notDoneWhen: "The dispatch was sent but the vendor has not accepted it, or acceptance was treated as the repair being done." },
    forbidden: ["dispatch a vendor that is not on the approved list for the property", "dispatch when the estimate exceeds the spend threshold without a recorded approval"],
    approvals: ["dispatch where the estimate exceeds the workspace's spend threshold"],
    collaborators: ["spend-vendor.vendor-insurance-and-coi-compliance", "spend-vendor.vendor-search", "maintenance.spend-approval-preparation", "maintenance.maintenance-scheduling"],
  },
  {
    id: "maintenance.maintenance-scheduling",
    name: "Maintenance Scheduling",
    domain: "maintenance",
    boundary: "Fixes the appointment window for an assigned work order by matching the technician's or vendor's availability to the resident's access preferences and any entry-notice lead time. Stops at a confirmed window on the work order; it does not send the resident the notice itself.",
    notThis: { specialist: "maintenance.resident-coordination", because: "Scheduling settles the time slot; resident coordination carries the messages to and from the resident about that slot and the job." },
    triggers: ["schedule", "appointment", "time slot", "reschedule", "when can they come"],
    inputs: ["assigned work order", "technician or vendor availability", "resident access preferences", "entry-notice lead time for the jurisdiction"],
    outputs: ["confirmed appointment window on the work order", "reschedule reason when a window is missed"],
    capabilities: ["work_order.read", "staff.read", "vendor.read", "work_order.update"],
    execution: "expertise",
    completion: { doneWhen: "The work order carries an appointment window that the assignee has confirmed and that respects the entry-notice lead time.", notDoneWhen: "A proposed time was offered but the technician or vendor never confirmed it." },
    forbidden: ["schedule an entry sooner than the jurisdiction's notice period allows without a recorded resident waiver or emergency"],
    approvals: [],
    collaborators: ["maintenance.permission-to-enter-coordination", "maintenance.resident-coordination", "maintenance.vendor-dispatch"],
  },
  {
    id: "maintenance.resident-coordination",
    name: "Resident Coordination",
    domain: "maintenance",
    boundary: "Keeps the resident informed through a work order's life: acknowledgement, appointment, delays, arrival and outcome, in the resident's channel. Stops at communication about the job; it does not grant entry permission or change the schedule.",
    notThis: { specialist: "maintenance.permission-to-enter-coordination", because: "Permission-to-enter records the legal basis for entry; resident coordination sends status updates and collects replies about the job." },
    triggers: ["update the resident", "status", "running late", "any update", "resident follow-up"],
    inputs: ["work order and its status history", "resident contact channel and preferences", "workspace message templates"],
    outputs: ["status messages sent or prepared for the resident", "resident replies attached to the work order"],
    capabilities: ["work_order.read", "communication.read", "resident.message.prepare", "resident.message.send"],
    execution: "expertise",
    completion: { doneWhen: "The resident has received an update for each status change on the work order and replies are attached to it.", notDoneWhen: "The work order changed status but the resident was not told, or a message was drafted and never sent." },
    forbidden: ["promise a completion date the assignee has not confirmed", "share a vendor's or technician's personal contact details without workspace policy allowing it"],
    approvals: [],
    collaborators: ["maintenance.maintenance-scheduling", "resident-experience.resident-inbox", "resident-experience.resident-complaint-resolution"],
  },
  {
    id: "maintenance.permission-to-enter-coordination",
    name: "Permission-to-Enter Coordination",
    domain: "maintenance",
    boundary: "Establishes and records the basis for entering an occupied unit: the resident's permission, or a notice of entry timed to the jurisdiction's rules, and any pet or presence instructions. Stops at a recorded entry basis; it does not schedule the visit.",
    notThis: { specialist: "maintenance.resident-coordination", because: "Resident coordination sends job updates; this specialist records the legal and policy basis that lets anyone enter the unit at all." },
    triggers: ["permission to enter", "pte", "entry notice", "can we go in", "access the unit"],
    inputs: ["work order and appointment window", "resident's recorded entry preferences", "jurisdiction entry-notice rule", "lease entry clause"],
    outputs: ["recorded permission or prepared notice of entry", "pet and presence instructions for the assignee"],
    capabilities: ["work_order.read", "lease.read", "compliance.read", "notice.prepare", "work_order.update"],
    execution: "expertise",
    completion: { doneWhen: "The work order records either the resident's permission or a notice of entry delivered within the required lead time.", notDoneWhen: "A notice was drafted but not delivered, or delivered later than the jurisdiction requires before the visit." },
    forbidden: ["treat silence from the resident as permission to enter", "apply one jurisdiction's notice period to a unit in another"],
    approvals: ["notice of entry where the workspace requires staff review before delivery"],
    collaborators: ["maintenance.maintenance-scheduling", "lease-admin.resident-notice-preparation", "property-operations.key-and-access-inventory"],
  },
  {
    id: "maintenance.parts-and-materials-coordination",
    name: "Parts & Materials Coordination",
    domain: "maintenance",
    boundary: "Identifies the parts a work order needs, checks on-hand inventory and prepares a purchase request when stock is short, then tracks the part to arrival. Stops at the part being available for the job; it does not compare vendor quotes for the repair.",
    notThis: { specialist: "spend-vendor.purchase-order-preparation", because: "Purchase order preparation builds the PO document for any spend; this specialist decides which parts a repair needs and whether stock already covers them." },
    triggers: ["parts", "materials", "back ordered", "need a part", "inventory", "waiting on parts"],
    inputs: ["work order and technician's parts list", "inventory on hand", "preferred suppliers"],
    outputs: ["parts reserved from inventory or a prepared purchase request", "expected arrival recorded on the work order"],
    capabilities: ["work_order.read", "inventory.read", "purchase_order.prepare", "work_order.update"],
    execution: "expertise",
    completion: { doneWhen: "Every required part is either reserved from inventory or has a confirmed arrival date on the work order.", notDoneWhen: "A purchase request was prepared but not approved or ordered, and the work order shows no arrival date." },
    forbidden: ["place an order with a supplier directly", "substitute a part the technician specified without recording the change"],
    approvals: ["purchase requests for parts"],
    collaborators: ["spend-vendor.purchase-order-preparation", "maintenance.maintenance-scheduling", "maintenance.technician-assignment"],
  },
  {
    id: "maintenance.repair-quote-comparison",
    name: "Repair Quote Comparison",
    domain: "maintenance",
    boundary: "Compares the quotes already received for a single repair on scope, exclusions, warranty, lead time and price, and flags scope gaps. Stops at a side-by-side comparison with a stated recommendation; it does not solicit the quotes or approve the spend.",
    notThis: { specialist: "spend-vendor.bid-comparison", because: "Bid comparison evaluates formal bids for projects and contracts; this compares repair quotes for one work order, where the scope comes from the diagnosis." },
    triggers: ["compare quotes", "which quote", "estimate", "two quotes", "repair estimate"],
    inputs: ["quotes received for the work order", "diagnosed scope", "vendor compliance status"],
    outputs: ["side-by-side comparison with scope differences", "recommended quote with the reason"],
    capabilities: ["work_order.read", "document.read", "document.extract", "vendor.read"],
    execution: "expertise",
    completion: { doneWhen: "Each quote is normalized to the same scope with gaps listed and a recommendation recorded on the work order.", notDoneWhen: "The cheapest quote was picked without checking that it covers the diagnosed scope." },
    forbidden: ["recommend a quote from a vendor whose insurance is lapsed or unverified"],
    approvals: [],
    collaborators: ["maintenance.spend-approval-preparation", "spend-vendor.vendor-insurance-and-coi-compliance", "spend-vendor.bid-solicitation"],
  },
  {
    id: "maintenance.spend-approval-preparation",
    name: "Spend Approval Preparation",
    domain: "maintenance",
    boundary: "Prepares the approval request for repair spend that exceeds the workspace or owner threshold: amount, chosen quote, urgency, alternatives and the approver the policy names. Stops when the request reaches the approver; the decision and payment are not its job.",
    notThis: { specialist: "spend-vendor.approval-routing", because: "Approval routing moves any bill or PO through the approval chain; this one writes the maintenance case, why the repair is needed and why this quote, that the approver reads." },
    triggers: ["needs approval", "over threshold", "owner approval", "authorize repair", "not to exceed"],
    inputs: ["work order and recommended quote", "workspace and owner spend thresholds", "urgency and habitability context"],
    outputs: ["approval request with amount, rationale and alternatives", "named approver per policy"],
    capabilities: ["work_order.read", "budget.read", "owner.read", "purchase_order.prepare", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "The approval request is with the approver the policy names and the work order records that it is awaiting approval.", notDoneWhen: "The request was drafted but never reached an approver, or the work proceeded before approval came back." },
    forbidden: ["split one repair into smaller requests to stay under a threshold", "mark spend as approved on an approver's behalf"],
    approvals: ["repair spend above the workspace or owner threshold"],
    collaborators: ["maintenance.repair-quote-comparison", "spend-vendor.approval-routing", "owner-services.owner-approval-coordination"],
  },
  {
    id: "maintenance.preventive-maintenance",
    name: "Preventive Maintenance",
    domain: "maintenance",
    boundary: "Builds and keeps the preventive maintenance plan for building systems and equipment, such as HVAC filters, water heaters, roofs and fire equipment servicing, from manufacturer intervals and workspace policy. Stops at the plan and its due tasks; recurring task generation is handed on.",
    notThis: { specialist: "maintenance.recurring-maintenance", because: "Preventive maintenance decides what equipment needs servicing and how often; recurring maintenance turns a set cadence into work orders on schedule." },
    triggers: ["preventive", "pm schedule", "hvac service", "filter change", "equipment", "seasonal"],
    inputs: ["equipment and system inventory by property", "manufacturer and policy intervals", "service history"],
    outputs: ["preventive maintenance plan per property", "list of overdue or unplanned equipment"],
    capabilities: ["property.read", "maintenance.read", "work_order.read", "sop.read"],
    execution: "expertise",
    completion: { doneWhen: "Every recorded system at the property has a service interval and a next due date in the plan.", notDoneWhen: "A plan was written but equipment in the inventory has no interval or next due date." },
    forbidden: ["set a service interval longer than the manufacturer or code requires"],
    approvals: ["changes to a property's preventive maintenance plan"],
    collaborators: ["maintenance.recurring-maintenance", "inspections.life-safety-inspection-coordination", "utilities.energy-and-water-usage-analysis"],
  },
  {
    id: "maintenance.recurring-maintenance",
    name: "Recurring Maintenance",
    domain: "maintenance",
    boundary: "Generates work orders on a fixed cadence from the approved preventive plan and standing service contracts, and checks that each cycle's order was created and not skipped. Stops at creating the cycle's work orders; it does not change the plan.",
    notThis: { specialist: "maintenance.preventive-maintenance", because: "Preventive maintenance sets what is serviced and how often; this specialist only produces each cycle's work orders from that plan." },
    triggers: ["recurring", "monthly", "quarterly", "every year", "standing order", "pest control"],
    inputs: ["approved preventive plan and service contracts", "calendar and last generated cycle"],
    outputs: ["work orders for the due cycle", "list of skipped or missed cycles"],
    capabilities: ["maintenance.read", "work_order.read", "work_order.create"],
    execution: "deterministic",
    completion: { doneWhen: "A work order exists for every task due in the cycle, each linked to its plan item.", notDoneWhen: "The cycle was marked generated but one or more due tasks have no work order." },
    forbidden: ["generate a cycle twice for the same period", "generate orders for a plan item that has been retired"],
    approvals: [],
    collaborators: ["maintenance.preventive-maintenance", "maintenance.technician-assignment", "spend-vendor.contract-expiration-monitor"],
  },
  {
    id: "maintenance.maintenance-sla-monitor",
    name: "Maintenance SLA Monitor",
    domain: "maintenance",
    boundary: "Measures each open work order against the workspace's response and completion targets by priority and flags orders at risk or in breach. Stops at the measurement and the alert; it does not reprioritize or reassign.",
    notThis: { specialist: "maintenance.work-order-prioritization", because: "Prioritization orders the work; the SLA monitor only computes elapsed time against targets and raises an alert when a threshold is crossed." },
    triggers: ["sla", "overdue", "response time", "aging work orders", "breach"],
    inputs: ["open work orders with timestamps and priority", "workspace SLA targets"],
    outputs: ["at-risk and breached work orders with elapsed time", "alert routed to the responsible person"],
    capabilities: ["work_order.read", "maintenance.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Every open work order has a computed SLA status and every breach has an alert routed to a named owner.", notDoneWhen: "Breaches were listed in a report but no owner was alerted." },
    forbidden: ["reset a work order's timestamps to clear a breach", "pause an SLA clock without a recorded reason the policy allows"],
    approvals: [],
    collaborators: ["maintenance.work-order-prioritization", "people-operations.staff-task-routing", "data-integrations.dashboard-and-kpi"],
  },
  {
    id: "maintenance.completion-verification",
    name: "Completion Verification",
    domain: "maintenance",
    boundary: "Checks that a work order reported complete is actually complete: evidence photos, technician or vendor notes, resident confirmation or a staff check where the policy requires one. Closes the work order only once the evidence meets policy; otherwise it returns it with what is missing.",
    notThis: { specialist: "inspections.correction-follow-up", because: "Correction follow-up tracks inspection deficiencies to correction; this verifies a maintenance work order before it is closed." },
    triggers: ["completed", "done", "vendor says finished", "close work order", "verify repair"],
    inputs: ["work order reported complete", "completion photos and notes", "resident confirmation", "workspace verification policy by category"],
    outputs: ["verified closure of the work order", "or return to the assignee with the missing evidence listed"],
    capabilities: ["work_order.read", "document.read", "communication.read", "work_order.close", "work_order.update"],
    execution: "expertise",
    completion: { doneWhen: "The work order is closed with the evidence its category requires attached.", notDoneWhen: "The vendor or technician said it was done and the order was closed without the required evidence or confirmation." },
    forbidden: ["close a work order on the assignee's word alone where the policy requires evidence", "accept a resident's silence as confirmation of a safety-related repair"],
    approvals: [],
    collaborators: ["maintenance.resident-coordination", "spend-vendor.invoice-work-order-matching", "maintenance.repeat-issue-analysis"],
  },
  {
    id: "maintenance.repeat-issue-analysis",
    name: "Repeat-Issue Analysis",
    domain: "maintenance",
    boundary: "Finds units, systems and equipment with repeated work orders for the same symptom within a window and states the pattern with the orders behind it. Stops at the finding and a recommendation for a root-cause visit, replacement review or preventive change; it does not diagnose the cause.",
    notThis: { specialist: "inspections.property-condition-trend", because: "Property condition trend reads inspection results over time; repeat-issue analysis reads the work-order history for recurring faults." },
    triggers: ["again", "keeps happening", "third time", "repeat", "callback", "same issue"],
    inputs: ["closed and open work orders by unit, system and category", "analysis window"],
    outputs: ["repeat-issue list with the linked work orders", "recommendation for root-cause visit or replacement review"],
    capabilities: ["work_order.read", "maintenance.read", "analytics.read", "report.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Each repeat pattern is listed with its work orders and a recommended next step routed to the Lead.", notDoneWhen: "A count of repeats was produced but no next step was recorded or routed." },
    forbidden: ["attribute a repeat fault to a resident's conduct without evidence in the work orders", "state a root cause the work-order history does not support"],
    approvals: [],
    collaborators: ["maintenance.preventive-maintenance", "spend-vendor.vendor-performance", "portfolio-strategy.capex-planning"],
  },
];
