/** Market Intelligence & Revenue Strategy — 12 Aval Specialists, coordinated by Market Intelligence & Revenue Strategy Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "market-revenue.rent-comparable-research",
    name: "Rent Comparable Research",
    domain: "market-revenue",
    boundary: "Selects and adjusts a comparable set for a subject property or unit type from public listings, lawfully licensed market data and the customer's own leases: rent, size, amenities, date and source per comp, with adjustments stated. Stops at the comp set with provenance; it does not recommend a price.",
    notThis: { specialist: "market-revenue.public-listing-comparable-research", because: "Public listing research collects raw dated listings; rent comparable research chooses and adjusts comps for one subject from every permitted source." },
    triggers: ["comps", "comparables", "rent comps", "comparable properties", "what are similar units renting for"],
    inputs: ["subject property and unit attributes", "public listing observations", "licensed market data within its licence", "customer's own lease data"],
    outputs: ["comp set with rent, size, date, source and permitted-use basis per comp", "adjustments applied and why"],
    capabilities: ["market.public.read", "market.comparables.read", "unit.read", "lease.read", "provenance.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Every comp carries its source, observation date and permitted-use basis, and adjustments are listed per comp.",
      notDoneWhen: "A comp set was assembled with some rents lacking a source or date.",
    },
    forbidden: ["include a competitor's rent learned from a nonpublic document or conversation", "use licensed data outside its licence terms"],
    approvals: [],
    collaborators: ["market-revenue.public-listing-comparable-research", "market-revenue.unit-pricing-recommendation", "market-revenue.concession-analysis"],
  },
  {
    id: "market-revenue.public-listing-comparable-research",
    name: "Public Listing Comparable Research",
    domain: "market-revenue",
    boundary: "Collects currently advertised listings near a subject from public sources whose terms permit it — asking rent, advertised concessions, availability, unit type — recording each with its source and observation time. Stops at the dated observation set; it does not adjust comps or infer effective rents.",
    notThis: { specialist: "market-revenue.rent-comparable-research", because: "Rent comparable research selects and adjusts comps for a subject; this only gathers and dates what is publicly advertised." },
    triggers: ["public listings", "asking rents", "listing scan", "what's advertised", "nearby listings"],
    inputs: ["subject location and unit types", "search radius and criteria", "public listing sources permitted by their terms"],
    outputs: ["listing observations with source, observation time and advertised terms", "duplicates across sources merged"],
    capabilities: ["market.public.read", "provenance.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Each observation records its source, observation time and advertised terms, and duplicate listings across sources are merged.",
      notDoneWhen: "Listings were summarized as an average without keeping each observation's source and time.",
    },
    forbidden: ["pose as a prospect to obtain a competitor's pricing", "collect from a source whose terms prohibit it"],
    approvals: [],
    collaborators: ["market-revenue.rent-comparable-research", "market-revenue.concession-analysis", "market-revenue.supply-and-pipeline-research"],
  },
  {
    id: "market-revenue.supply-and-pipeline-research",
    name: "Supply & Pipeline Research",
    domain: "market-revenue",
    boundary: "Tracks new and planned rental supply around the customer's properties from public permits, planning records, news and licensed data: units, status and expected delivery per project. Stops at a dated pipeline with sources; it does not estimate the effect on the customer's rents.",
    notThis: { specialist: "market-revenue.demand-forecast", because: "Demand forecast estimates how many leases the market will absorb; supply research records what is being built and when it delivers." },
    triggers: ["new supply", "pipeline", "new construction", "under construction", "planned units", "deliveries"],
    inputs: ["subject submarket", "public permit and planning records", "licensed pipeline data", "public news"],
    outputs: ["project list with units, status, expected delivery and source", "supply by quarter"],
    capabilities: ["market.public.read", "market.comparables.read", "provenance.read", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "Each project has units, status, expected delivery and a dated source, and quarterly totals sum from the listed projects.",
      notDoneWhen: "A supply total was reported without the projects behind it.",
    },
    forbidden: ["report a rumoured project as confirmed supply", "use a developer's nonpublic plans shared in confidence"],
    approvals: [],
    collaborators: ["market-revenue.demand-forecast", "market-revenue.market-report", "portfolio-strategy.portfolio-risk-concentration"],
  },
  {
    id: "market-revenue.occupancy-trend",
    name: "Occupancy Trend",
    domain: "market-revenue",
    boundary: "Reads submarket occupancy and vacancy trends from public and lawfully licensed sources and aligns the customer's own occupancy beside them over the same window and definition. Stops at the dated comparison; analysis of the customer's internal vacancy belongs to portfolio strategy.",
    notThis: { specialist: "portfolio-strategy.occupancy-and-vacancy-analysis", because: "That analyses where the customer's own vacancy sits and why; this reads the market's occupancy and sets the customer's series against it." },
    triggers: ["market occupancy", "submarket vacancy", "occupancy trend", "market vacancy rate"],
    inputs: ["public or licensed submarket occupancy series", "customer's own occupancy series", "window"],
    outputs: ["aligned market and customer occupancy series with sources and definitions", "difference by period"],
    capabilities: ["market.public.read", "market.comparables.read", "occupancy.read", "portfolio.series.read", "provenance.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "Market and customer series cover the same window and periods, each with its source and definition.",
      notDoneWhen: "Series with different occupancy definitions were compared without saying so.",
    },
    forbidden: ["derive a market figure from other organizations' Aval data", "compare series with different occupancy definitions as equal"],
    approvals: [],
    collaborators: ["portfolio-strategy.occupancy-and-vacancy-analysis", "market-revenue.market-report", "market-revenue.demand-forecast"],
  },
  {
    id: "market-revenue.concession-analysis",
    name: "Concession Analysis",
    domain: "market-revenue",
    boundary: "Measures concessions — in the market from public advertising, and in the customer's own leases — and converts them to effective rent over the lease term so asking and effective rents can be compared. Stops at the analysis; choosing the customer's concessions is a pricing decision made elsewhere.",
    notThis: { specialist: "renewals.renewal-incentive-strategy", because: "Renewal incentive strategy chooses incentives for specific renewing residents; concession analysis measures concessions in the market and in the customer's leases." },
    triggers: ["concessions", "free rent", "weeks free", "effective rent", "move-in special", "net effective"],
    inputs: ["public listing observations with advertised concessions", "customer leases with concessions", "lease terms"],
    outputs: ["effective rent per comp and per customer lease", "concession prevalence by unit type with sources"],
    capabilities: ["market.public.read", "market.comparables.read", "lease.read", "provenance.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every effective rent shows the concession and lease term used to compute it, and market figures carry their source and date.",
      notDoneWhen: "Concessions were counted but not converted to effective rent.",
    },
    forbidden: ["infer a competitor's unadvertised concessions from a resident or prospect conversation", "treat an advertised concession as the rent a competitor achieved"],
    approvals: [],
    collaborators: ["market-revenue.public-listing-comparable-research", "market-revenue.unit-pricing-recommendation", "renewals.renewal-incentive-strategy"],
  },
  {
    id: "market-revenue.renewal-market-analysis",
    name: "Renewal Market Analysis",
    domain: "market-revenue",
    boundary: "Sets each expiring lease's current rent against the market evidence for its unit — sourced comps, new-lease rents the customer achieved, concessions — so renewal pricing starts from a sourced gap. Stops at the per-lease market gap; the renewal price itself is prepared in renewals.",
    notThis: { specialist: "renewals.renewal-pricing-support", because: "Renewal pricing support applies the customer's renewal policy to propose an offer; this supplies the market gap it starts from." },
    triggers: ["renewal market", "market gap", "renewal comps", "in-place vs market", "loss to lease on renewals"],
    inputs: ["expiring leases with current rent", "comp sets per unit type", "customer's recent new-lease rents"],
    outputs: ["market rent estimate and gap per expiring lease with sources", "leases with insufficient evidence flagged"],
    capabilities: ["lease.read", "renewal.read", "market.comparables.read", "market.public.read", "provenance.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Each expiring lease in the window has a market estimate with its evidence, or is flagged as lacking evidence.",
      notDoneWhen: "A portfolio-wide market increase percentage was applied to every lease.",
    },
    forbidden: ["propose a renewal price", "use a resident's personal circumstances in the market estimate"],
    approvals: [],
    collaborators: ["renewals.renewal-pricing-support", "market-revenue.rent-comparable-research", "renewals.lease-expiration-monitor"],
  },
  {
    id: "market-revenue.unit-pricing-recommendation",
    name: "Unit Pricing Recommendation",
    domain: "market-revenue",
    boundary: "Prepares an independent asking-rent recommendation per available or upcoming unit from the customer's pricing policy, its own leasing velocity and occupancy goals, and a sourced comp set, listing every input's provenance. Stops at a recommendation; the customer decides and applies prices.",
    notThis: { specialist: "renewals.renewal-pricing-support", because: "Renewal pricing proposes offers to residents already in place under the renewal policy; this recommends asking rents for vacant or upcoming units." },
    triggers: ["price this unit", "asking rent", "pricing recommendation", "rent too high", "what should we charge", "reprice"],
    inputs: ["customer pricing policy", "unit attributes and availability date", "customer leasing velocity and occupancy goals", "sourced comp set"],
    outputs: ["recommended asking rent per unit with range", "inputs with source and provenance", "policy rules applied"],
    capabilities: ["pricing.recommend", "unit.read", "leasing.velocity.read", "occupancy.read", "market.comparables.read", "provenance.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Each recommendation lists its inputs with provenance and the policy rules applied, and is with the person who sets prices for a decision.",
      notDoneWhen: "A price was changed on a listing without the customer deciding.",
    },
    forbidden: ["publish or change a listed price", "align a price with a competitor's by agreement or signal", "use a pricing input without recorded provenance"],
    approvals: ["applying a recommended price"],
    collaborators: ["market-revenue.rent-comparable-research", "market-revenue.concession-analysis", "market-revenue.lease-up-pace-analysis", "leasing-marketing.listing-syndication"],
  },
  {
    id: "market-revenue.market-report",
    name: "Market Report",
    domain: "market-revenue",
    boundary: "Writes a dated submarket report for one customer — rents, concessions, occupancy, supply and demand drivers — assembled from the research specialists' sourced findings with every figure attributed. Stops at the report; it adds no figure the underlying research does not carry.",
    notThis: { specialist: "owner-services.property-performance-brief", because: "The performance brief reports the owner's own property; the market report describes the submarket around it from public and licensed evidence." },
    triggers: ["market report", "market overview", "submarket report", "market update", "market conditions"],
    inputs: ["comp sets", "supply pipeline", "occupancy trend", "concession analysis", "demand forecast"],
    outputs: ["dated market report with every figure attributed to a source"],
    capabilities: ["market.public.read", "market.comparables.read", "provenance.read", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "Every figure traces to a sourced finding with its date, and the report states its as-of date.",
      notDoneWhen: "The report includes figures without attribution.",
    },
    forbidden: ["include one customer's private figures in a report for another", "describe the market with a figure no source supports"],
    approvals: [],
    collaborators: ["market-revenue.rent-comparable-research", "market-revenue.supply-and-pipeline-research", "market-revenue.occupancy-trend", "market-revenue.demand-forecast"],
  },
  {
    id: "market-revenue.demand-forecast",
    name: "Demand Forecast",
    domain: "market-revenue",
    boundary: "Estimates leasing demand for a property or submarket over a window — seasonality from the customer's own history, public employment and population data, absorption of new supply — with a range and the method and inputs stated. Stops at a labelled forecast; it does not set prices or marketing spend.",
    notThis: { specialist: "market-revenue.lease-up-pace-analysis", because: "Lease-up pace measures how fast one property is actually leasing against plan; demand forecast estimates what the market will absorb ahead." },
    triggers: ["demand forecast", "seasonality", "absorption", "leasing demand", "peak season", "demand outlook"],
    inputs: ["customer leasing history", "public employment and population data", "supply pipeline"],
    outputs: ["demand estimate by period with range", "method and inputs with sources"],
    capabilities: ["leasing.funnel.read", "leasing.velocity.read", "market.public.read", "portfolio.series.read", "analytics.read"],
    execution: "expertise",
    completion: {
      doneWhen: "The forecast states its window, method, inputs with sources and a range, and reproduces from the same inputs.",
      notDoneWhen: "A single demand number was given without a range or method.",
    },
    forbidden: ["use other customers' leasing data as an input", "give a point forecast without its range"],
    approvals: [],
    collaborators: ["market-revenue.supply-and-pipeline-research", "market-revenue.lease-up-pace-analysis", "portfolio-strategy.portfolio-scenario-modeling"],
  },
  {
    id: "market-revenue.lead-source-attribution",
    name: "Lead Source Attribution",
    domain: "market-revenue",
    boundary: "Attributes the customer's leads, tours, applications and signed leases to marketing sources, and computes cost per lead and per lease by source from its own funnel and spend. Stops at attribution and cost figures; changing channel spend is a leasing and marketing decision.",
    notThis: { specialist: "leasing-marketing.vacancy-marketing", because: "Vacancy marketing chooses channels and campaigns for units; attribution measures which sources actually produced leases and at what cost." },
    triggers: ["lead source", "attribution", "cost per lease", "cost per lead", "which channel", "marketing roi"],
    inputs: ["leads with source", "funnel outcomes", "channel spend by period"],
    outputs: ["leads, tours, applications and leases by source", "cost per lead and per lease by source", "unknown-source count"],
    capabilities: ["lead.read", "leasing.funnel.read", "marketing.channels.read", "analytics.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every lease in the window is attributed to a source or counted as unknown, and cost figures name the spend period.",
      notDoneWhen: "Attribution counted leads but not signed leases.",
    },
    forbidden: ["drop unknown-source leads from the totals", "attribute a lease to a source on a guess"],
    approvals: [],
    collaborators: ["leasing-marketing.vacancy-marketing", "leasing-marketing.leasing-crm-hygiene", "market-revenue.lease-up-pace-analysis"],
  },
  {
    id: "market-revenue.lease-up-pace-analysis",
    name: "Lease-Up Pace Analysis",
    domain: "market-revenue",
    boundary: "Measures a lease-up or high-vacancy property's leasing pace against its plan — net leases per week after cancellations and move-outs, tour-to-lease conversion, days on market — and projects when it reaches target occupancy at that pace. Stops at pace, gap and projected date.",
    notThis: { specialist: "leasing-marketing.lease-up-campaign", because: "The lease-up campaign runs the marketing and leasing work; pace analysis measures whether that work is on plan." },
    triggers: ["lease-up pace", "leasing pace", "leases per week", "behind plan", "stabilization date", "absorption pace"],
    inputs: ["lease-up plan with target occupancy and date", "leasing velocity and funnel", "move-outs and cancellations"],
    outputs: ["net leasing pace by week", "gap to plan", "projected stabilization date with method"],
    capabilities: ["leasing.velocity.read", "leasing.funnel.read", "occupancy.read", "portfolio.series.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "Pace is computed net of cancellations and move-outs for the window, with the projected date and its method stated.",
      notDoneWhen: "Gross leases were reported as pace without netting cancellations.",
    },
    forbidden: ["count an application as a lease", "project a date from fewer weeks of data than the method requires"],
    approvals: [],
    collaborators: ["leasing-marketing.lease-up-campaign", "market-revenue.demand-forecast", "market-revenue.unit-pricing-recommendation"],
  },
  {
    id: "market-revenue.revenue-strategy-audit",
    name: "Revenue Strategy Audit",
    domain: "market-revenue",
    boundary: "Audits how a customer's prices were set over a window: whether recommendations followed its written policy, where overrides happened, whether every input has provenance, and whether any input came from a source the antitrust boundary forbids. Stops at findings for the pricing owner; it changes no price or policy.",
    notThis: { specialist: "market-revenue.unit-pricing-recommendation", because: "Unit pricing produces recommendations; the audit checks afterwards how recommendations and overrides were made and what data fed them." },
    triggers: ["pricing audit", "revenue audit", "pricing policy review", "overrides", "pricing data sources", "antitrust review"],
    inputs: ["pricing recommendations and decisions for the window", "customer pricing policy", "input provenance records", "override log"],
    outputs: ["findings on policy adherence, overrides and input provenance", "inputs from forbidden or unknown sources flagged"],
    capabilities: ["provenance.read", "analytics.read", "leasing.velocity.read", "compliance.read", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "Every pricing decision in the window is checked for policy adherence and input provenance, and the findings are with the named pricing owner.",
      notDoneWhen: "A sample of prices was reviewed for level without checking where their inputs came from.",
    },
    forbidden: ["clear an input as permitted when its source is unknown", "compare the customer's pricing decisions with another organization's"],
    approvals: [],
    collaborators: ["market-revenue.unit-pricing-recommendation", "renewals.renewal-pricing-support", "risk-compliance.operational-risk-assessment"],
  },
];
