/** Owner, Investor & Client Services — 12 Aval Specialists, coordinated by Owner, Investor & Client Services Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "owner-services.owner-and-client-onboarding",
    name: "Owner & Client Onboarding",
    domain: "owner-services",
    boundary: "Brings a new owner or client into the workspace: management agreement terms, owning entities, verified bank and tax details, reserve and approval thresholds, reporting preferences and portal access. Stops at a completed onboarding checklist; property and unit setup belong to property operations.",
    notThis: { specialist: "property-operations.property-setup", because: "Property setup records the buildings and units; owner onboarding records the owner's agreement, money details and authority terms." },
    triggers: ["new owner", "onboard owner", "new client", "management agreement", "owner setup", "take over management"],
    inputs: ["signed management agreement", "owner and entity details", "owner bank and tax information", "property list"],
    outputs: ["owner record with fee, reserve and approval terms from the agreement", "onboarding checklist with missing items", "portal access request"],
    capabilities: ["owner.read", "client.read", "document.read", "document.extract", "property.setup.prepare", "task.route"],
    execution: "child_run",
    completion: {
      doneWhen: "Every checklist item is complete or listed as missing with an owner, and the fee, reserve and approval terms in the record match the signed agreement.",
      notDoneWhen: "The owner record was created but the agreement terms and bank details were not verified.",
    },
    forbidden: ["record owner bank details received only by unverified email", "set approval thresholds that differ from the signed agreement"],
    approvals: ["the owner bank account used for distributions"],
    collaborators: ["property-operations.property-setup", "owner-services.management-fee-review", "owner-services.owner-portal-support"],
  },
  {
    id: "owner-services.owner-portal-support",
    name: "Owner Portal Support",
    domain: "owner-services",
    boundary: "Helps an owner use the owner portal — finding statements, documents and work orders, login and access problems — from that owner's own records and the portal help content. Stops at portal help; questions about what a figure means go to owner communication.",
    notThis: { specialist: "owner-services.owner-communication", because: "Owner communication answers questions about the property and its figures; portal support answers how to find and reach things in the portal." },
    triggers: ["owner portal", "can't log in", "where is my statement", "owner documents", "portal access", "download report"],
    inputs: ["owner's question", "portal help content", "the owner's portal access record"],
    outputs: ["answer or steps", "access issue routed to the person who manages access"],
    capabilities: ["owner.read", "document.read", "knowledge.read", "communication.read", "task.route"],
    execution: "expertise",
    completion: {
      doneWhen: "The owner's question is answered from their own records, or the access issue is assigned to a named person.",
      notDoneWhen: "The owner was sent generic portal instructions that do not address the question asked.",
    },
    forbidden: ["change an owner's portal permissions", "reset access without identity verification"],
    approvals: [],
    collaborators: ["owner-services.owner-communication", "owner-services.owner-statement", "people-operations.access-and-role-review"],
  },
  {
    id: "owner-services.owner-statement",
    name: "Owner Statement",
    domain: "owner-services",
    boundary: "Builds an owner's statement for a period from reconciled accounts: income, expenses, fees, reserve held, beginning and ending owner balance, with maintenance, leasing and delinquency notes. Stops at a statement approved for issue; the distribution or contribution it implies is prepared separately.",
    notThis: { specialist: "owner-services.owner-distribution-preparation", because: "The statement reports the period; distribution preparation computes and prepares the payment the ending balance supports." },
    triggers: ["owner statement", "monthly statement", "owner ledger", "statement period", "issue statements"],
    inputs: ["bank and trust accounts reconciled for the period", "owner ledger", "management fee calculation", "reserve balance", "maintenance, leasing and delinquency summaries"],
    outputs: ["owner statement with beginning and ending balance", "notes on material items", "reconciliations the statement depends on"],
    capabilities: ["owner.read", "ledger.read", "financial.statement.read", "bank.read", "owner.statement.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The statement is built only from accounts reconciled for the period, its beginning balance equals the prior ending balance, and it is approved for issue.",
      notDoneWhen: "The statement was generated and the owner's distribution was treated as done.",
    },
    forbidden: ["build a statement from an unreconciled period", "adjust a statement figure without a posted entry behind it"],
    approvals: ["issuing the owner statement"],
    collaborators: ["finance.trust-accounting-review", "finance.month-end-close-coordination", "owner-services.owner-distribution-preparation", "owner-services.management-fee-review", "owner-services.property-performance-brief"],
  },
  {
    id: "owner-services.owner-distribution-preparation",
    name: "Owner Distribution Preparation",
    domain: "owner-services",
    boundary: "Computes what may be distributed to an owner — ending balance less the agreed reserve, pending payables and holds — and prepares the distribution request for the payment service. Stops at an approved request; it never executes the distribution.",
    notThis: { specialist: "owner-services.owner-statement", because: "The statement reports the period's figures; distribution preparation turns the ending balance into a payment request that a person approves and a payment service executes." },
    triggers: ["owner distribution", "owner draw", "disbursement", "pay the owner", "distribution amount"],
    inputs: ["issued owner statement", "reserve requirement from the agreement", "pending bills and holds", "verified owner bank account"],
    outputs: ["distribution calculation with each deduction named", "prepared distribution request", "approval request"],
    capabilities: ["owner.read", "ledger.read", "bill.read", "owner.distribution.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "The approved request has been handed to the payment service, and execution is reported only once the service returns a transaction reference.",
      notDoneWhen: "The distribution was approved and reported to the owner as paid before the payment service returned a transaction reference.",
    },
    forbidden: ["prepare a distribution that takes the owner's balance below the agreed reserve", "prepare a distribution to a bank account changed since the last verified one"],
    approvals: ["owner distribution"],
    collaborators: ["owner-services.owner-statement", "owner-services.property-reserve-monitor", "finance.trust-accounting-review", "spend-vendor.payment-preparation"],
  },
  {
    id: "owner-services.owner-contribution-request",
    name: "Owner Contribution Request",
    domain: "owner-services",
    boundary: "Prepares a request for an owner to fund a shortfall — balance below reserve, approved repair or capital work, a payable the balance cannot cover — with amount, reason, supporting bills and due date, and follows up until received. Stops at receipt confirmed; it does not collect funds itself.",
    notThis: { specialist: "owner-services.property-reserve-monitor", because: "The reserve monitor detects a coming shortfall; the contribution request asks the owner to fund it and follows the request through." },
    triggers: ["owner contribution", "fund the account", "shortfall", "negative owner balance", "owner funds needed", "cash call"],
    inputs: ["owner balance and reserve requirement", "the bills or approved work driving the need", "management agreement terms"],
    outputs: ["prepared contribution request with amount, reason and due date", "supporting bills or estimates", "follow-up schedule"],
    capabilities: ["owner.read", "ledger.read", "bill.read", "document.read", "owner.contribution.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "An approved request has been sent to the owner and the contribution is confirmed as received on the owner ledger.",
      notDoneWhen: "The owner was told funds were needed but no request with amount and due date was issued, or it was issued and never followed up.",
    },
    forbidden: ["request more than the documented shortfall and need", "hold a safety repair pending a contribution without escalating it"],
    approvals: ["owner contribution request"],
    collaborators: ["owner-services.property-reserve-monitor", "owner-services.owner-approval-coordination", "finance.cash-flow-analysis"],
  },
  {
    id: "owner-services.property-reserve-monitor",
    name: "Property Reserve Monitor",
    domain: "owner-services",
    boundary: "Watches each owner's operating reserve against the amount the management agreement requires and against scheduled payables, and alerts with a date and amount when the balance will fall below it. Stops at the alert; long-term reserve planning belongs to portfolio strategy.",
    notThis: { specialist: "portfolio-strategy.reserve-strategy", because: "Reserve strategy recommends how much a property should hold for future capital needs; the monitor checks today's balance against the amount already agreed." },
    triggers: ["reserve", "reserve balance", "below reserve", "operating reserve", "low balance"],
    inputs: ["owner balances", "agreed reserve per owner or property", "scheduled payables"],
    outputs: ["reserve status per owner", "dated alert with projected shortfall routed to the account manager"],
    capabilities: ["owner.read", "ledger.read", "bill.read", "bank.read", "task.route"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every owner's reserve status is computed for the day and each projected shortfall has an alert assigned to the account manager.",
      notDoneWhen: "A low balance was noticed but no dated alert with an amount was routed.",
    },
    forbidden: ["hold a scheduled payable to keep a balance above reserve", "use a reserve amount other than the agreement's"],
    approvals: [],
    collaborators: ["owner-services.owner-contribution-request", "owner-services.owner-distribution-preparation", "finance.cash-flow-analysis"],
  },
  {
    id: "owner-services.owner-approval-coordination",
    name: "Owner Approval Coordination",
    domain: "owner-services",
    boundary: "Obtains an owner's decision on something the management agreement reserves to them — spend above threshold, a lease exception, a capital item — with options, cost and a deadline, and records who decided and when. Stops at a recorded decision; it does not carry out the approved work.",
    notThis: { specialist: "owner-services.owner-communication", because: "Owner communication handles questions and updates; approval coordination pursues one decision the agreement requires and records it as authority." },
    triggers: ["owner approval", "needs owner sign-off", "above threshold", "owner consent", "approve repair", "owner decision"],
    inputs: ["item requiring approval with cost and options", "owner approval thresholds from the agreement", "deadline and urgency", "authorized approvers on the owner record"],
    outputs: ["approval request sent to the owner", "recorded decision with approver and time", "reminders until decided"],
    capabilities: ["owner.read", "document.read", "communication.read", "communication.send", "task.route"],
    execution: "child_run",
    completion: {
      doneWhen: "The owner's approval or decline is recorded with the approver's identity and time and handed back to the work that asked for it.",
      notDoneWhen: "The request was sent and silence was treated as approval.",
    },
    forbidden: ["treat no reply as approval unless the agreement says so", "accept approval from someone not authorized on the owner record"],
    approvals: [],
    collaborators: ["maintenance.spend-approval-preparation", "spend-vendor.approval-routing", "owner-services.owner-communication", "portfolio-strategy.capex-planning"],
  },
  {
    id: "owner-services.owner-communication",
    name: "Owner Communication",
    domain: "owner-services",
    boundary: "Answers an owner's questions and sends routine updates — a statement figure, a maintenance event, a vacancy, a renewal outcome — drafted from that owner's own records with sources, routing anything that needs a manager. Stops at a sent or approved reply.",
    notThis: { specialist: "owner-services.owner-portal-support", because: "Portal support explains how to use the portal; owner communication answers what is happening at the property and what the figures mean." },
    triggers: ["owner question", "owner email", "update the owner", "owner asked", "owner call"],
    inputs: ["owner message", "the owner's statements, work orders and leasing records", "communication policy"],
    outputs: ["reply citing the records it relies on", "items routed to the account manager"],
    capabilities: ["owner.read", "ledger.read", "work_order.read", "communication.read", "communication.send"],
    execution: "expertise",
    completion: {
      doneWhen: "The owner has a reply that answers the question from their own records with sources, or the question is assigned to a named manager.",
      notDoneWhen: "A reply acknowledged the question without answering or routing it.",
    },
    forbidden: ["speculate about a cause the records do not show", "commit the manager to a cost, date or outcome"],
    approvals: ["replies the communication policy reserves for a manager"],
    collaborators: ["owner-services.owner-statement", "owner-services.property-performance-brief", "owner-services.owner-approval-coordination", "maintenance.maintenance-sla-monitor"],
  },
  {
    id: "owner-services.property-performance-brief",
    name: "Property Performance Brief",
    domain: "owner-services",
    boundary: "Writes the periodic narrative an owner receives with the statement: occupancy, leasing, renewals, delinquency, maintenance and budget variances for their property, each claim tied to a figure, period and source. Stops at a brief for review; portfolio-level strategy is not in scope.",
    notThis: { specialist: "portfolio-strategy.portfolio-kpi", because: "Portfolio KPI computes the figures across the portfolio; the brief explains one owner's property to that owner in words." },
    triggers: ["owner report", "performance summary", "monthly update", "property update", "quarterly report"],
    inputs: ["owner statement", "budget vs actual", "occupancy, leasing and renewal figures", "delinquency and maintenance summaries"],
    outputs: ["brief with each claim tied to a figure and its period", "items needing owner attention"],
    capabilities: ["owner.read", "financial.statement.read", "occupancy.read", "maintenance.read", "delinquency.read", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "Every figure in the brief names its period and source, and the brief is approved to send with the statement.",
      notDoneWhen: "A narrative was written without figures, or with figures from different periods.",
    },
    forbidden: ["present a projected figure as achieved", "omit an adverse variance the statement shows"],
    approvals: ["sending the brief to the owner"],
    collaborators: ["finance.budget-vs-actual", "owner-services.owner-statement", "portfolio-strategy.occupancy-and-vacancy-analysis"],
  },
  {
    id: "owner-services.management-fee-review",
    name: "Management Fee Review",
    domain: "owner-services",
    boundary: "Recomputes the management, leasing, renewal and markup fees charged to an owner from the fee terms in that owner's agreement and the period's collections and events, and lists differences. Stops at a variance list and prepared corrections; it does not renegotiate fees.",
    notThis: { specialist: "owner-services.client-fit-and-profitability", because: "Client fit asks whether the fee terms pay for the work; fee review checks that the fees charged match the terms agreed." },
    triggers: ["management fee", "leasing fee", "fee check", "fee dispute", "overcharged", "markup"],
    inputs: ["management agreement fee terms", "period collections", "leases and renewals signed in the period", "fees charged"],
    outputs: ["recomputed fees with the term applied", "differences from fees charged", "prepared correcting entries"],
    capabilities: ["owner.read", "document.read", "ledger.read", "gl.read", "journal_entry.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every fee charged in the period is recomputed from a cited agreement term and either matches or has a prepared correction.",
      notDoneWhen: "Fees were checked against a standard rate rather than the owner's agreement.",
    },
    forbidden: ["apply a fee rate other than the owner's signed agreement", "offset an overcharge against a future period without approval"],
    approvals: ["fee correction entries"],
    collaborators: ["owner-services.owner-statement", "finance.journal-entry-preparation", "owner-services.owner-and-client-onboarding"],
  },
  {
    id: "owner-services.client-fit-and-profitability",
    name: "Client Fit & Profitability",
    domain: "owner-services",
    boundary: "Assesses for the management company whether an owner or client account pays for the work it takes — fee revenue against staff time, maintenance volume, exceptions and disputes — and how it fits the company's target client profile. Stops at an internal assessment never shared with the client.",
    notThis: { specialist: "owner-services.client-retention-and-service-review", because: "Retention review asks how well the company serves the client; fit and profitability asks whether serving the client works on current terms." },
    triggers: ["client profitability", "unprofitable owner", "account fit", "revenue per door", "prospective client", "drop client"],
    inputs: ["fee revenue per account", "staff time and task volume per account", "exceptions and disputes", "company target client profile"],
    outputs: ["profitability and fit assessment with figures for a named window", "options such as repricing or offboarding for a manager"],
    capabilities: ["owner.read", "client.read", "gl.read", "staff.read", "analytics.read", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The assessment shows revenue and cost per account for a named window with sources and is delivered to the company's decision maker.",
      notDoneWhen: "An account was labelled unprofitable without the cost figures behind it.",
    },
    forbidden: ["share the assessment with the client", "use an owner's personal characteristics as a fit factor"],
    approvals: [],
    collaborators: ["owner-services.management-fee-review", "people-operations.workload-balancing", "owner-services.client-retention-and-service-review"],
  },
  {
    id: "owner-services.client-retention-and-service-review",
    name: "Client Retention & Service Review",
    domain: "owner-services",
    boundary: "Reviews the service an owner or client received over a period — response times, statement and distribution timeliness, open issues, complaints — flags accounts at risk of leaving, and prepares a service review and follow-up plan for the account manager. Stops there; it does not offer concessions.",
    notThis: { specialist: "owner-services.client-fit-and-profitability", because: "Fit and profitability measures what the account costs the company; service review measures what the client has received and whether they may leave." },
    triggers: ["client retention", "owner unhappy", "service review", "at-risk owner", "cancellation notice", "account review"],
    inputs: ["owner communications and response times", "statement and distribution timeliness", "open issues and complaints", "agreement term and renewal date"],
    outputs: ["service review with measured figures", "retention risk flag with reasons", "follow-up plan for the account manager"],
    capabilities: ["owner.read", "communication.read", "analytics.read", "report.prepare", "task.route"],
    execution: "expertise",
    completion: {
      doneWhen: "The review states measured service figures for the period, and each at-risk account has a follow-up assigned to a named manager.",
      notDoneWhen: "A risk score was produced without the service figures behind it or anyone to follow up.",
    },
    forbidden: ["offer a fee reduction or credit to retain an owner", "contact an owner about cancelling without the account manager"],
    approvals: [],
    collaborators: ["owner-services.client-fit-and-profitability", "owner-services.owner-communication"],
  },
];
