/** People & Internal Operations — 8 Aval Specialists, coordinated by People & Internal Operations Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "people-operations.staff-task-routing",
    name: "Staff Task Routing",
    domain: "people-operations",
    boundary: "Assigns each new work item to a person or team by property assignment, role, the authority the action needs and availability, and reassigns it if not accepted in time. Stops at acceptance; it does not rebalance existing queues.",
    notThis: { specialist: "people-operations.workload-balancing", because: "Routing places each new item as it arrives; workload balancing redistributes queues that already exist." },
    triggers: ["assign", "who should handle", "route to staff", "unassigned", "not accepted"],
    inputs: ["work item and required authority", "staff roles and property assignments", "availability"],
    outputs: ["assignment and acceptance record", "reassignment when unaccepted"],
    capabilities: ["task.route", "staff.read", "property.read"],
    execution: "expertise",
    completion: { doneWhen: "The item is accepted, within its response time, by a person whose role holds the authority it needs.", notDoneWhen: "The item was assigned but not accepted, or went to someone lacking authority for the action." },
    forbidden: ["assign work outside a person's permitted properties", "route by a staff member's personal characteristics"],
    approvals: [],
    collaborators: ["property-operations.property-staff-assignment", "people-operations.on-call-schedule", "people-operations.workload-balancing", "data-integrations.communication-ingestion"],
  },
  {
    id: "people-operations.on-call-schedule",
    name: "On-Call Schedule",
    domain: "people-operations",
    boundary: "Keeps on-call rotations per property and emergency category with backups and the escalation ladder, answers who is on call now, and raises coverage gaps ahead of time. Stops at a covered, accepted schedule; it does not handle the emergency itself.",
    notThis: { specialist: "people-operations.staff-task-routing", because: "Routing assigns everyday work by role and availability; the on-call schedule guarantees a named, accepting person for every hour of emergency coverage." },
    triggers: ["on call", "after hours", "who is on call", "coverage gap", "rotation"],
    inputs: ["rotations and shift acceptances", "emergency categories per property", "escalation SOP"],
    outputs: ["current on-call and backup per property and category", "coverage gap alerts"],
    capabilities: ["staff.read", "property.read", "sop.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Every property and emergency category has an accepted on-call person and backup for each hour of the schedule window, and gaps were raised ahead of time.", notDoneWhen: "The rotation was published with an uncovered hour, or escalation reached someone off shift." },
    forbidden: ["list someone on call without their recorded acceptance of the shift", "expose staff personal phone numbers beyond the escalation path"],
    approvals: [],
    collaborators: ["maintenance.emergency-maintenance-triage", "people-operations.staff-task-routing", "data-integrations.provider-api-health"],
  },
  {
    id: "people-operations.sop-and-knowledge-operations",
    name: "SOP & Knowledge Operations",
    domain: "people-operations",
    boundary: "Keeps the workspace's SOPs and knowledge articles versioned, owned and reviewed on schedule, finds conflicts between them and gaps shown by repeated questions, and drafts updates for the owner. Stops at an owner-approved version; it does not decide the process change.",
    notThis: { specialist: "people-operations.process-improvement", because: "Process improvement decides how the work should change; this keeps the written procedure current, versioned and consistent." },
    triggers: ["sop", "procedure", "knowledge article", "policy outdated", "conflicting instructions"],
    inputs: ["SOPs and articles with versions and owners", "repeated questions and escalations"],
    outputs: ["draft updates for owner approval", "conflict and review-due list"],
    capabilities: ["sop.read", "knowledge.read", "document.read"],
    execution: "expertise",
    completion: { doneWhen: "The SOP or article has a version, owner and next review date, and any change was approved by its owner before publishing.", notDoneWhen: "An edit was published without owner approval, or two active SOPs still conflict." },
    forbidden: ["publish a policy change without the owner's approval", "write a legal requirement into an SOP without the jurisdiction record it relies on"],
    approvals: ["SOP publication"],
    collaborators: ["people-operations.process-improvement", "people-operations.training-and-quality-assurance", "resident-experience.resident-faq-and-policy"],
  },
  {
    id: "people-operations.training-and-quality-assurance",
    name: "Training & Quality Assurance",
    domain: "people-operations",
    boundary: "Samples completed work (resident replies, work orders, notices, AI employee runs) against the SOP version and quality rubric, scores it, and assigns training for each coaching need. Stops at scores and assigned training; it does not change the procedure.",
    notThis: { specialist: "people-operations.process-improvement", because: "QA measures whether work followed the procedure; process improvement changes the procedure." },
    triggers: ["quality review", "qa", "audit replies", "coaching", "training"],
    inputs: ["sampled work items", "SOP versions and rubric", "staff roster"],
    outputs: ["rubric scores with SOP version", "training assignments with dates"],
    capabilities: ["sop.read", "communication.read", "work_order.read", "staff.read", "analytics.read"],
    execution: "expertise",
    completion: { doneWhen: "Each sampled item has a score against a named SOP version, and each coaching need has assigned training with a completion date.", notDoneWhen: "Scores were recorded, but failing items have no follow-up training." },
    forbidden: ["score people on message volume instead of outcomes", "share an individual's QA results beyond them and their manager"],
    approvals: [],
    collaborators: ["people-operations.sop-and-knowledge-operations", "people-operations.process-improvement", "risk-compliance.fair-housing-guard"],
  },
  {
    id: "people-operations.workload-balancing",
    name: "Workload Balancing",
    domain: "people-operations",
    boundary: "Computes each person's queue load weighted by effort, age and SLA, identifies overload and idle capacity, and proposes reassignments for a manager to accept. Stops at the manager's decision; new items are routed elsewhere.",
    notThis: { specialist: "people-operations.staff-task-routing", because: "Routing places each new item; balancing moves existing items between people when queues become uneven." },
    triggers: ["overloaded", "workload", "backlog", "rebalance", "too many tasks"],
    inputs: ["open queues with effort and SLA", "staff authority and availability"],
    outputs: ["load per person", "proposed reassignment set"],
    capabilities: ["staff.read", "analytics.read", "work_order.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "The manager accepted or declined each proposed reassignment, and afterwards no queue exceeds the configured threshold.", notDoneWhen: "Reassignments were proposed, but items stayed with an overloaded person past their SLA." },
    forbidden: ["reassign items without the manager's acceptance", "move work to someone without authority for it"],
    approvals: ["reassignment set"],
    collaborators: ["people-operations.staff-task-routing", "maintenance.maintenance-sla-monitor", "property-operations.daily-operations-queue"],
  },
  {
    id: "people-operations.access-and-role-review",
    name: "Access & Role Review",
    domain: "people-operations",
    boundary: "Reviews user access periodically: role against job, property scope, departed staff still active, excess privileges and shared accounts, producing a keep, change or remove list for an administrator. Stops at the reviewed list; an administrator makes every change.",
    notThis: { specialist: "risk-compliance.privacy-and-data-request", because: "A privacy request concerns what personal data a requester may see or remove; this concerns which staff accounts may reach which data." },
    triggers: ["access review", "role review", "departed employee", "permissions", "offboarding"],
    inputs: ["user accounts, roles and scopes", "staff roster and departures", "activity records"],
    outputs: ["keep, change or remove list", "read-back confirmation of changes applied"],
    capabilities: ["staff.read", "compliance.read"],
    execution: "deterministic",
    completion: { doneWhen: "An administrator marked every active user keep, change or remove, and each change was confirmed by read-back.", notDoneWhen: "The list was prepared, but departed users remain active." },
    forbidden: ["copy credentials or tokens into the review", "propose removal on anything but role and activity evidence"],
    approvals: ["access changes"],
    collaborators: ["property-operations.property-staff-assignment", "risk-compliance.privacy-and-data-request", "people-operations.internal-incident"],
  },
  {
    id: "people-operations.internal-incident",
    name: "Internal Incident",
    domain: "people-operations",
    boundary: "Records an internal operational failure (missed emergency escalation, wrong message sent, data exposure, automation misfire, outage that stopped work): timeline, affected records and people, containment, notification needs and corrective actions. Stops at an owned corrective-action list.",
    notThis: { specialist: "risk-compliance.incident-intake", because: "Incident intake records an event at a property such as an injury or fire; this records a failure in the team's own operation or systems." },
    triggers: ["we made a mistake", "sent to wrong person", "missed escalation", "automation error", "data exposure"],
    inputs: ["report of the failure", "audit and communication records", "affected systems"],
    outputs: ["incident timeline and impact", "containment confirmation", "corrective actions with owners"],
    capabilities: ["communication.read", "provenance.read", "staff.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "The incident has a timeline, affected records and people, confirmed containment, and each corrective action has an owner and date.", notDoneWhen: "The incident was contained, but a possible data exposure was not sent to the privacy owner." },
    forbidden: ["assign individual blame in the record before review", "delete or edit logs relevant to the incident"],
    approvals: [],
    collaborators: ["risk-compliance.privacy-and-data-request", "data-integrations.audit-and-provenance", "data-integrations.provider-api-health", "people-operations.process-improvement"],
  },
  {
    id: "people-operations.process-improvement",
    name: "Process Improvement",
    domain: "people-operations",
    boundary: "Analyzes a workflow's outcomes (cycle time, rework, SLA breaches, repeated escalations) to find its bottleneck, proposes one change with a baseline and measure, and measures the result after adoption. Stops at the owner's decision and the measured result.",
    notThis: { specialist: "people-operations.training-and-quality-assurance", because: "QA checks whether people followed the procedure; process improvement changes the procedure when following it still gives poor outcomes." },
    triggers: ["bottleneck", "too slow", "improve process", "rework", "cycle time"],
    inputs: ["workflow outcome data", "current SOP", "escalation history"],
    outputs: ["proposal with baseline and measure", "post-change result"],
    capabilities: ["analytics.read", "sop.read", "work_order.read", "staff.read", "report.prepare"],
    execution: "child_run",
    completion: { doneWhen: "The proposal has a baseline, an owner's decision, and if adopted, a measured result after the stated period.", notDoneWhen: "The change was adopted without a baseline, so its effect cannot be measured." },
    forbidden: ["propose removing a human approval step that policy or law requires", "measure success by activity counts instead of outcomes"],
    approvals: ["process change adoption"],
    collaborators: ["people-operations.sop-and-knowledge-operations", "people-operations.training-and-quality-assurance", "data-integrations.dashboard-and-kpi", "maintenance.repeat-issue-analysis"],
  },
];
