/** Portfolio & Asset Strategy — 12 Aval Specialists, coordinated by Portfolio & Asset Strategy Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "portfolio-strategy.portfolio-kpi",
    name: "Portfolio KPI",
    domain: "portfolio-strategy",
    boundary: "Computes the portfolio's standard KPIs — occupancy, leased percentage, collections rate, turn time, delinquency, renewal rate, NOI margin — for a named window, per property and in total, with each definition and source. Stops at the computed figures; interpretation belongs to the analysis specialists.",
    notThis: { specialist: "data-integrations.dashboard-and-kpi", because: "Dashboard & KPI maintains dashboards and their data feeds; Portfolio KPI computes the strategy figure set for a window with stated definitions." },
    triggers: ["portfolio kpis", "portfolio metrics", "how is the portfolio", "portfolio summary", "scorecard"],
    inputs: ["portfolio metrics and series", "KPI definitions", "the window requested"],
    outputs: ["KPI table per property and total with window, definition and source", "missing-data flags"],
    capabilities: ["portfolio.read", "portfolio.metrics.read", "portfolio.series.read", "occupancy.read", "provenance.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every KPI is computed for the named window with its definition and source, and properties with missing data are flagged rather than dropped.",
      notDoneWhen: "Totals were reported while properties with missing data were silently excluded.",
    },
    forbidden: ["mix KPI windows in one table", "change a KPI definition between periods without stating it"],
    approvals: [],
    collaborators: ["data-integrations.dashboard-and-kpi", "portfolio-strategy.property-benchmarking", "portfolio-strategy.noi-analysis"],
  },
  {
    id: "portfolio-strategy.noi-analysis",
    name: "NOI Analysis",
    domain: "portfolio-strategy",
    boundary: "Analyses net operating income across properties and periods: trend, the income and expense drivers behind it, margin by property, and one-off items that distort the run rate. Stops at the analysis with drivers named; it does not value properties or model scenarios.",
    notThis: { specialist: "finance.profit-and-loss-analysis", because: "P&L analysis explains one statement's lines from their entries; NOI analysis compares operating income across properties and time as a strategy input." },
    triggers: ["noi", "net operating income", "noi trend", "operating margin", "run rate", "noi decline"],
    inputs: ["operating statements by property and period", "portfolio series", "known one-off items"],
    outputs: ["NOI by property and period", "drivers of change with figures", "normalized run rate with each adjustment listed"],
    capabilities: ["financial.statement.read", "accounting.read", "portfolio.series.read", "analytics.read"],
    execution: "expertise",
    completion: {
      doneWhen: "NOI for the window reconciles to the operating statements, and each driver cited has a figure and a source line.",
      notDoneWhen: "A trend was described from two periods without reconciling to the statements.",
    },
    forbidden: ["normalize out an expense without listing it", "compare NOI across properties on different reporting bases without saying so"],
    approvals: [],
    collaborators: ["finance.profit-and-loss-analysis", "portfolio-strategy.property-benchmarking", "portfolio-strategy.hold-sell-reinvest-analysis"],
  },
  {
    id: "portfolio-strategy.occupancy-and-vacancy-analysis",
    name: "Occupancy & Vacancy Analysis",
    domain: "portfolio-strategy",
    boundary: "Analyses the customer's own physical and economic occupancy: vacancy by property and unit type, days vacant, loss to lease and concessions, notice exposure, and where vacancy concentrates. Stops at the analysis; pricing and marketing responses belong to their own domains.",
    notThis: { specialist: "market-revenue.occupancy-trend", because: "Occupancy Trend reads the market's occupancy from public and licensed data; this analyses the customer's own units." },
    triggers: ["vacancy", "occupancy", "economic occupancy", "days vacant", "loss to lease", "notice exposure"],
    inputs: ["occupancy and unit status", "rent roll with market and actual rents", "notices to vacate", "turn status"],
    outputs: ["physical and economic occupancy by property and unit type", "vacancy concentration findings", "forward exposure from notices"],
    capabilities: ["occupancy.read", "unit.read", "portfolio.series.read", "lease.read", "turn.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Physical and economic occupancy are both computed for the window with definitions, and each concentration finding cites its units.",
      notDoneWhen: "Only physical occupancy was reported and called occupancy.",
    },
    forbidden: ["count a leased-not-moved-in unit as occupied without saying so", "count a unit down for renovation as available vacancy"],
    approvals: [],
    collaborators: ["market-revenue.occupancy-trend", "leasing-marketing.vacancy-marketing", "turns.turn-timeline", "property-operations.occupancy-state-coordination"],
  },
  {
    id: "portfolio-strategy.capex-planning",
    name: "CapEx Planning",
    domain: "portfolio-strategy",
    boundary: "Builds a multi-year capital plan per property from condition data, equipment age and inspection findings: items, estimated cost, timing and priority, with the source of each estimate. Stops at a proposed plan for the owner or asset manager; it does not approve projects or solicit bids.",
    notThis: { specialist: "portfolio-strategy.reserve-strategy", because: "Reserve strategy decides how to fund future capital needs; CapEx planning decides what those needs are and when they fall." },
    triggers: ["capex", "capital plan", "roof replacement", "capital project", "equipment replacement", "capital budget"],
    inputs: ["property condition and inspection findings", "equipment age and useful life", "cost estimates or bids", "owner capital priorities"],
    outputs: ["capital plan by property and year with cost, source and priority", "items needing a bid or inspection before estimating"],
    capabilities: ["property.read", "inspection.read", "maintenance.read", "budget.read", "report.prepare"],
    execution: "child_run",
    completion: {
      doneWhen: "Every item has cost, timing, priority and the source of its estimate, and the plan is delivered to the named decision maker.",
      notDoneWhen: "A list of items was made without cost sources or timing.",
    },
    forbidden: ["present an unsourced cost as an estimate", "drop a life-safety item from the plan to fit a budget"],
    approvals: ["the capital plan"],
    collaborators: ["inspections.property-condition-trend", "portfolio-strategy.reserve-strategy", "spend-vendor.bid-solicitation", "owner-services.owner-approval-coordination"],
  },
  {
    id: "portfolio-strategy.reserve-strategy",
    name: "Reserve Strategy",
    domain: "portfolio-strategy",
    boundary: "Recommends how much each property should set aside for future capital needs and at what contribution rate, from the capital plan, current reserves and the owner's risk tolerance, showing the funding gap by year. Stops at a recommendation; the agreed reserve is the owner's to set.",
    notThis: { specialist: "owner-services.property-reserve-monitor", because: "The reserve monitor checks today's balance against the amount already agreed; reserve strategy recommends what that amount should be." },
    triggers: ["reserve strategy", "replacement reserve", "reserve funding", "capital reserve", "funding gap"],
    inputs: ["capital plan", "current reserve balances", "owner risk tolerance and hold period", "reserve study where one exists"],
    outputs: ["recommended reserve level and contribution rate", "funding gap by year"],
    capabilities: ["budget.read", "owner.read", "financial.statement.read", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The recommendation shows the funding schedule against the capital plan year by year and names every assumption.",
      notDoneWhen: "A reserve amount was suggested without the capital plan it should fund.",
    },
    forbidden: ["change an agreed reserve amount", "recommend a level that leaves plan items unfunded without stating the gap"],
    approvals: [],
    collaborators: ["portfolio-strategy.capex-planning", "owner-services.property-reserve-monitor", "hoa.reserve-study-tracking"],
  },
  {
    id: "portfolio-strategy.debt-and-maturity-analysis",
    name: "Debt & Maturity Analysis",
    domain: "portfolio-strategy",
    boundary: "Summarizes each property's debt from loan documents and statements — balance, rate, maturity, covenants such as DSCR — and tests covenants against current NOI using the loan's own definitions, flagging maturities and resets. Stops at the analysis; it does not contact lenders.",
    notThis: { specialist: "portfolio-strategy.hold-sell-reinvest-analysis", because: "Hold/sell/reinvest weighs decisions for an asset; debt analysis supplies the loan terms, maturities and covenant results those decisions must respect." },
    triggers: ["debt", "loan maturity", "dscr", "covenant", "refinance", "rate reset", "mortgage"],
    inputs: ["loan documents and statements", "NOI by property", "covenant definitions from the loan documents"],
    outputs: ["debt schedule by property citing documents", "covenant test results with the loan clause cited", "maturity and reset calendar"],
    capabilities: ["document.read", "document.extract", "financial.statement.read", "portfolio.read"],
    execution: "expertise",
    completion: {
      doneWhen: "Each loan's terms cite the document they came from, and each covenant is tested with the loan's own definition against current figures.",
      notDoneWhen: "Covenants were tested with a generic definition instead of the loan document's.",
    },
    forbidden: ["compute a covenant with a definition other than the loan document's", "fill a missing loan term with a typical market value"],
    approvals: [],
    collaborators: ["portfolio-strategy.noi-analysis", "portfolio-strategy.hold-sell-reinvest-analysis", "portfolio-strategy.portfolio-scenario-modeling"],
  },
  {
    id: "portfolio-strategy.portfolio-scenario-modeling",
    name: "Portfolio Scenario Modeling",
    domain: "portfolio-strategy",
    boundary: "Models what-if scenarios across the whole portfolio — rent growth, vacancy, expense inflation, rate changes, capital spend — from stated assumptions, showing the effect on NOI and cash flow per scenario. Stops at labelled scenarios with inputs named; it does not recommend a decision.",
    notThis: { specialist: "portfolio-strategy.hold-sell-reinvest-analysis", because: "Hold/sell/reinvest compares decision paths for one asset; scenario modeling stresses the whole portfolio under assumptions without choosing a path." },
    triggers: ["scenario", "what if", "stress test", "sensitivity", "downside case", "model the portfolio"],
    inputs: ["baseline operating figures and series", "assumptions per scenario with their source", "debt schedule", "capital plan"],
    outputs: ["scenario results for NOI and cash flow with assumptions listed", "sensitivity of results to each assumption"],
    capabilities: ["portfolio.read", "portfolio.series.read", "financial.statement.read", "budget.read", "report.prepare"],
    execution: "child_run",
    completion: {
      doneWhen: "Each scenario is labelled a scenario, lists every assumption with its source or as a user choice, and reproduces from those inputs.",
      notDoneWhen: "One scenario's result was reported as the expected outcome.",
    },
    forbidden: ["show a scenario's result without its assumptions alongside it", "take market assumptions from a competitor's nonpublic data"],
    approvals: [],
    collaborators: ["portfolio-strategy.noi-analysis", "portfolio-strategy.debt-and-maturity-analysis", "market-revenue.demand-forecast", "finance.cash-flow-analysis"],
  },
  {
    id: "portfolio-strategy.acquisition-due-diligence",
    name: "Acquisition Due Diligence",
    domain: "portfolio-strategy",
    boundary: "Works a prospective acquisition's diligence: seller rent roll tied to leases, trailing financials tied to bank records, estoppels, service contracts, condition and capital needs, listing discrepancies and open items. Stops at a findings report; it does not value the property or advise on price.",
    notThis: { specialist: "portfolio-strategy.disposition-analysis", because: "Disposition analysis prepares a property the customer owns for sale; due diligence tests a property someone else is selling to the customer." },
    triggers: ["acquisition", "due diligence", "rent roll audit", "estoppel", "buying a property", "t12"],
    inputs: ["seller rent roll and leases", "trailing twelve-month financials and bank statements", "service contracts", "property condition report"],
    outputs: ["discrepancies between rent roll, leases and financials", "open diligence items with owner and due date", "capital needs found"],
    capabilities: ["document.read", "document.extract", "lease.read", "market.public.read", "report.prepare"],
    execution: "child_run",
    completion: {
      doneWhen: "Every unit in the rent roll is tied to a lease document or listed as missing, and every open item has an owner and a date.",
      notDoneWhen: "The seller's rent roll totals were accepted without tying units to leases.",
    },
    forbidden: ["state a value or offer price", "treat seller-provided figures as verified without source documents"],
    approvals: [],
    collaborators: ["lease-admin.lease-abstract", "portfolio-strategy.capex-planning", "market-revenue.rent-comparable-research", "risk-compliance.property-insurance-monitor"],
  },
  {
    id: "portfolio-strategy.disposition-analysis",
    name: "Disposition Analysis",
    domain: "portfolio-strategy",
    boundary: "Prepares the case for selling a property the owner is considering: trailing and normalized NOI, rent roll quality, deferred capital, loan payoff and prepayment terms, and readiness of the documents a buyer will request. Stops at a package for the owner and advisers; it does not price or market the property.",
    notThis: { specialist: "portfolio-strategy.hold-sell-reinvest-analysis", because: "Hold/sell/reinvest decides whether to sell; disposition analysis prepares the property's case once a sale is under consideration." },
    triggers: ["sell the property", "disposition", "sale prep", "offering memorandum", "buyer diligence", "exit"],
    inputs: ["operating statements", "rent roll and leases", "capital plan", "loan payoff and prepayment terms"],
    outputs: ["disposition package with sources", "buyer diligence items marked ready or missing"],
    capabilities: ["financial.statement.read", "lease.read", "document.read", "portfolio.read", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The package's figures reconcile to the operating statements, adjustments to NOI are listed, and every expected diligence item is marked ready or missing.",
      notDoneWhen: "A summary normalized NOI without listing the adjustments.",
    },
    forbidden: ["include resident personal data in a disposition package", "state a sale price or cap rate as the property's value"],
    approvals: [],
    collaborators: ["portfolio-strategy.noi-analysis", "portfolio-strategy.debt-and-maturity-analysis", "portfolio-strategy.hold-sell-reinvest-analysis"],
  },
  {
    id: "portfolio-strategy.property-benchmarking",
    name: "Property Benchmarking",
    domain: "portfolio-strategy",
    boundary: "Ranks the customer's own properties against one another on normalized measures — expense per unit or square foot, turn cost, delinquency, maintenance response — within peer groups, and names outliers. Uses only the workspace's own data; comparison with the external market belongs to market intelligence.",
    notThis: { specialist: "portfolio-strategy.portfolio-kpi", because: "Portfolio KPI reports each figure; benchmarking normalizes them so unlike properties can be ranked and outliers named." },
    triggers: ["benchmark", "compare properties", "worst performing", "cost per unit", "outlier property", "rank properties"],
    inputs: ["portfolio metrics by property", "unit counts and square footage", "property attributes for peer grouping"],
    outputs: ["normalized ranking by measure", "outliers with the figure behind each"],
    capabilities: ["portfolio.metrics.read", "property.read", "unit.read", "analytics.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every property in each peer group is ranked on each measure with the normalization named, and each outlier cites its figure.",
      notDoneWhen: "Raw totals were ranked without normalizing for size.",
    },
    forbidden: ["benchmark against another organization's data", "rank properties on different reporting bases as if comparable"],
    approvals: [],
    collaborators: ["portfolio-strategy.portfolio-kpi", "portfolio-strategy.noi-analysis", "market-revenue.market-report"],
  },
  {
    id: "portfolio-strategy.hold-sell-reinvest-analysis",
    name: "Hold/Sell/Reinvest Analysis",
    domain: "portfolio-strategy",
    boundary: "Compares, for one property over the owner's horizon, holding as is, selling, or reinvesting in capital work: cash flow and capital by year, debt constraints, and the assumptions each path depends on. Stops at a side-by-side comparison; the decision and any valuation are the owner's and their advisers'.",
    notThis: { specialist: "portfolio-strategy.portfolio-scenario-modeling", because: "Scenario modeling stresses the whole portfolio under assumptions; hold/sell/reinvest compares three decision paths for one asset." },
    triggers: ["hold or sell", "should we sell", "reinvest", "renovate or sell", "exit strategy", "hold period"],
    inputs: ["NOI and cash flow history", "capital plan", "debt terms", "owner horizon and objectives", "assumptions with their source"],
    outputs: ["hold, sell and reinvest paths with cash flow and capital by year", "assumptions list with the ones results depend on most"],
    capabilities: ["financial.statement.read", "portfolio.series.read", "budget.read", "market.public.read", "report.prepare"],
    execution: "child_run",
    completion: {
      doneWhen: "All three paths show cash flow and capital by year over the owner's horizon with assumptions named, and the comparison is delivered to the owner.",
      notDoneWhen: "One path was recommended without the others computed.",
    },
    forbidden: ["present one path as the answer instead of comparing", "use a sale price without its source and date"],
    approvals: [],
    collaborators: ["portfolio-strategy.noi-analysis", "portfolio-strategy.capex-planning", "portfolio-strategy.debt-and-maturity-analysis", "portfolio-strategy.disposition-analysis"],
  },
  {
    id: "portfolio-strategy.portfolio-risk-concentration",
    name: "Portfolio Risk Concentration",
    domain: "portfolio-strategy",
    boundary: "Measures where portfolio exposure concentrates — one submarket, major tenant, loan maturity year, building age, insurance carrier or lease-expiration month — as shares of revenue or units, and flags concentrations above the owner's limits. Stops there; operational risk at a single property belongs to risk and compliance.",
    notThis: { specialist: "risk-compliance.operational-risk-assessment", because: "Operational risk assessment looks at hazards and practices at a property; concentration measures how exposure is distributed across the portfolio." },
    triggers: ["concentration", "exposure", "diversification", "lease expiration concentration", "tenant concentration", "maturity wall"],
    inputs: ["property attributes and locations", "lease expirations and major tenants", "debt maturities", "insurance policies", "owner concentration limits"],
    outputs: ["exposure by dimension as shares of revenue or units", "concentrations above limit"],
    capabilities: ["portfolio.read", "property.read", "lease.read", "insurance.read", "risk.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "Each dimension shows its shares with the data's as-of date, and every share above the owner's limit is flagged.",
      notDoneWhen: "Concentrations were described without the shares or limits behind them.",
    },
    forbidden: ["use residents' protected characteristics as a concentration dimension", "set concentration limits on the owner's behalf"],
    approvals: [],
    collaborators: ["portfolio-strategy.debt-and-maturity-analysis", "risk-compliance.property-insurance-monitor", "commercial.commercial-option-and-notice-date"],
  },
];
