/** Property Operations — 12 Aval Specialists, coordinated by Property Operations Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "property-operations.property-setup",
    name: "Property Setup",
    domain: "property-operations",
    boundary: "Builds a new property's record: legal and display name, address, ownership entity, buildings, property type, jurisdiction, amenities and management start date, from the management agreement and owner documents. Stops at a complete property record ready for units; unit records are separate.",
    notThis: { specialist: "property-operations.unit-setup", because: "Property setup builds the property and its buildings; unit setup builds each rentable unit inside them." },
    triggers: ["new property", "onboard property", "add a building", "property record", "management start"],
    inputs: ["management agreement", "owner and entity documents", "address and building list", "jurisdiction"],
    outputs: ["property record with buildings, entity and jurisdiction", "list of missing setup fields"],
    capabilities: ["property.read", "owner.read", "document.read", "document.extract", "property.setup.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The property record has every required field, including ownership entity and jurisdiction, and is approved for unit setup.", notDoneWhen: "The property was created with its jurisdiction or ownership entity blank." },
    forbidden: ["guess a property's jurisdiction from a mailing address without checking the physical location", "attach the property to an owner entity the documents do not name"],
    approvals: ["the completed property record"],
    collaborators: ["property-operations.unit-setup", "owner-services.owner-and-client-onboarding", "data-integrations.property-data-quality"],
  },
  {
    id: "property-operations.unit-setup",
    name: "Unit Setup",
    domain: "property-operations",
    boundary: "Creates each unit under a property with its identifier, building, floor plan, bedrooms, bathrooms, square footage, features, program designation and rentable status, checking for duplicates and conflicts with the PMS. Stops at complete unit records; it does not set occupancy.",
    notThis: { specialist: "property-operations.property-setup", because: "Property setup creates the property and buildings; unit setup creates the rentable units and their attributes inside them." },
    triggers: ["unit setup", "add units", "unit list", "floor plan", "rent roll import", "unit attributes"],
    inputs: ["property record", "unit list or rent roll", "floor plans", "PMS unit data where connected"],
    outputs: ["unit records with attributes", "duplicate and conflict list against the PMS"],
    capabilities: ["property.read", "unit.read", "data.conflicts.read", "unit.setup.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Every unit in the source list has a record, and each conflict with the PMS has been resolved or listed for review.", notDoneWhen: "Units were imported with duplicates or PMS conflicts left unflagged." },
    forbidden: ["merge two units that the source lists separately without review", "mark a unit rentable that the source lists as down or non-revenue"],
    approvals: ["the unit batch for a property"],
    collaborators: ["property-operations.property-setup", "data-integrations.entity-deduplication", "property-operations.occupancy-state-coordination"],
  },
  {
    id: "property-operations.occupancy-state-coordination",
    name: "Occupancy State Coordination",
    domain: "property-operations",
    boundary: "Keeps each unit's occupancy state, such as occupied, notice given, vacant, down or model, consistent with its source records: executed lease, notice, move-out and turn status. Stops at flagging and proposing changes that a source record supports; it does not create those records.",
    notThis: { specialist: "property-operations.move-in-move-out-coordination", because: "Move-in/move-out coordination runs the occupancy change itself; this keeps the recorded state correct against the source records afterwards." },
    triggers: ["occupancy status", "vacant or occupied", "unit status", "rent roll mismatch", "notice to vacate"],
    inputs: ["unit occupancy states", "leases, notices and move-out records", "turn status", "PMS occupancy data"],
    outputs: ["units whose state disagrees with a source record", "state changes proposed with the source record cited"],
    capabilities: ["unit.read", "occupancy.read", "lease.read", "turn.read", "data.conflicts.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every unit's occupancy state matches a cited source record, or its mismatch is on the review list.", notDoneWhen: "A state was changed because a person said so in a message, with no source record behind it." },
    forbidden: ["mark a unit occupied without an executed lease or recorded move-in"],
    approvals: ["occupancy state changes that the PMS does not already reflect"],
    collaborators: ["data-integrations.pms-synchronization", "turns.rent-ready-verification", "property-operations.move-in-move-out-coordination"],
  },
  {
    id: "property-operations.property-staff-assignment",
    name: "Property Staff Assignment",
    domain: "property-operations",
    boundary: "Records who covers each property in each role, such as manager, leasing, maintenance and on-site, with backups, from the staff roster, and flags properties with an uncovered role. Stops at the coverage map; hiring, schedules and individual task routing belong to people operations.",
    notThis: { specialist: "people-operations.workload-balancing", because: "Workload balancing spreads tasks across people; staff assignment records which people are responsible for which property and role." },
    triggers: ["who manages", "property manager for", "coverage", "assign staff to property", "backup"],
    inputs: ["staff roster with roles", "properties and their role requirements", "leave and vacancies"],
    outputs: ["coverage map by property and role with backups", "properties with an uncovered role"],
    capabilities: ["property.read", "staff.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "Every property has a named primary and backup for each role the workspace requires, or an uncovered-role alert has an owner.", notDoneWhen: "A primary is named but the backup is blank and nobody was told." },
    forbidden: ["assign a person to a property outside their organization's access scope"],
    approvals: ["changes to a property's primary manager"],
    collaborators: ["people-operations.workload-balancing", "people-operations.access-and-role-review", "people-operations.on-call-schedule"],
  },
  {
    id: "property-operations.daily-operations-queue",
    name: "Daily Operations Queue",
    domain: "property-operations",
    boundary: "Assembles a property's working queue for the day from open work across domains: work orders, move-ins, inspections, deliveries, vendor visits and follow-ups, ordered by due time. Stops at the queue for the property team; it does not do the work in it.",
    notThis: { specialist: "people-operations.staff-task-routing", because: "Staff task routing sends individual tasks to people; the daily queue gathers everything due at one property so its team sees the day." },
    triggers: ["today", "daily queue", "what's due", "morning list", "site agenda"],
    inputs: ["open tasks, work orders and appointments for the property", "property calendar", "staff coverage"],
    outputs: ["ordered daily queue per property with owner and due time", "items with no owner"],
    capabilities: ["property.read", "work_order.read", "inspection.read", "staff.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "The queue lists every item due that day at the property with an owner, and ownerless items are routed.", notDoneWhen: "The queue was produced but items without an owner were left on it unrouted." },
    forbidden: ["drop an overdue item from the queue because it rolled past its date"],
    approvals: [],
    collaborators: ["property-operations.property-calendar", "people-operations.staff-task-routing", "maintenance.maintenance-sla-monitor"],
  },
  {
    id: "property-operations.key-and-access-inventory",
    name: "Key & Access Inventory",
    domain: "property-operations",
    boundary: "Keeps the register of keys, fobs, codes and lockbox entries by unit and common area: who holds each, when it was issued and returned, and which are missing. Stops at an accurate register and missing-key alerts; rekeying during a turn is the turns specialist's work.",
    notThis: { specialist: "turns.key-and-access-reset", because: "Key and access reset rekeys and recodes a unit during a turn; this maintains the standing register of who holds what access at any time." },
    triggers: ["keys", "fob", "lockbox", "access code", "key log", "missing key"],
    inputs: ["key and access register", "issue and return events", "vendor and staff access requests"],
    outputs: ["current key and access register by unit and area", "missing or unreturned access items"],
    capabilities: ["key_access.read", "unit.read", "staff.read", "vendor.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every issued access item has a holder and date, and every missing item has an alert with an owner.", notDoneWhen: "A key was handed out and noted in a message but not entered in the register." },
    forbidden: ["share an access code in a message to anyone not on the access record", "issue unit access to a vendor without a work order for that unit"],
    approvals: [],
    collaborators: ["turns.key-and-access-reset", "maintenance.permission-to-enter-coordination", "resident-experience.package-and-access-support"],
  },
  {
    id: "property-operations.parking-and-storage-coordination",
    name: "Parking & Storage Coordination",
    domain: "property-operations",
    boundary: "Assigns and tracks parking spaces, permits and storage units against leases and waitlists, and records vehicles and unauthorized-parking reports. Stops at assignments and reports; charges for spaces are prepared elsewhere and towing follows the workspace's procedure and jurisdiction rules.",
    notThis: { specialist: "resident-experience.amenity-and-reservation-coordination", because: "Amenity reservation books shared spaces for a time; parking and storage assigns spaces and units to residents for the length of a lease." },
    triggers: ["parking", "permit", "storage unit", "garage", "towing", "assigned space"],
    inputs: ["parking and storage inventory", "lease addenda for spaces", "waitlist", "vehicle and permit records"],
    outputs: ["space and storage assignments linked to leases", "waitlist order", "unauthorized-parking reports"],
    capabilities: ["property.read", "lease.read", "resident.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "Each assigned space or storage unit is linked to a lease or addendum, and each waitlist offer has a recorded outcome.", notDoneWhen: "A space was promised to a resident but no addendum or assignment was recorded." },
    forbidden: ["order a tow", "assign an accessible parking space against the workspace's accessible-space policy"],
    approvals: ["towing requests under the workspace's procedure"],
    collaborators: ["lease-admin.lease-addendum-preparation", "risk-compliance.reasonable-accommodation-workflow", "receivables.rent-charge-schedule"],
  },
  {
    id: "property-operations.move-in-move-out-coordination",
    name: "Move-In/Move-Out Coordination",
    domain: "property-operations",
    boundary: "Runs the checklist for an occupancy change at the property: move date, elevator or loading reservation, keys, inspection, utilities, parking and resident instructions, each assigned to its owner. Stops at every item confirmed done; it does not perform the inspection or utility transfer itself.",
    notThis: { specialist: "resident-experience.move-in-onboarding", because: "Move-in onboarding welcomes the resident and explains living there; this coordinates the operational tasks around the physical move." },
    triggers: ["move-in", "move-out", "moving day", "elevator reservation", "loading dock", "move date"],
    inputs: ["lease start or move-out date", "workspace move checklist", "unit and property details"],
    outputs: ["move checklist with each item's owner and status", "items at risk before the move date"],
    capabilities: ["lease.read", "unit.read", "key_access.read", "task.route"],
    execution: "child_run",
    completion: { doneWhen: "Every checklist item for the move is confirmed done by its owner, including inspection and key handover.", notDoneWhen: "The move date passed and the checklist shows items still open, such as the inspection or utilities." },
    forbidden: ["hand over keys before the lease is executed and move-in funds are recorded as the policy requires"],
    approvals: [],
    collaborators: ["inspections.move-in-inspection", "utilities.utility-move-in-move-out", "property-operations.key-and-access-inventory", "property-operations.occupancy-state-coordination"],
  },
  {
    id: "property-operations.property-policy-workflow",
    name: "Property Policy Workflow",
    domain: "property-operations",
    boundary: "Takes a proposed change to a property's rules or operating policy, such as quiet hours, amenity rules, smoking or pets, through review, approval, the notice period and publication. Stops at the adopted policy with its effective date; enforcing it on individual residents is not its job.",
    notThis: { specialist: "resident-experience.resident-faq-and-policy", because: "Resident FAQ and policy answers questions from the policies in force; this changes the policies themselves through review and approval." },
    triggers: ["new rule", "policy change", "community rules", "house rules", "update policy"],
    inputs: ["proposed policy text", "current property policies", "lease and jurisdiction rules on rule changes"],
    outputs: ["reviewed policy draft", "approval record and effective date", "resident notice prepared"],
    capabilities: ["property.read", "sop.read", "compliance.read", "fair_housing.review", "notice.prepare"],
    execution: "child_run",
    completion: { doneWhen: "The policy is approved, residents have been given the required notice, and it is published with an effective date.", notDoneWhen: "The policy was approved but no notice went to residents, or it took effect before the notice period ran." },
    forbidden: ["publish a rule that has not had fair-housing review", "make a rule effective before the required notice period"],
    approvals: ["the policy change", "the resident notice"],
    collaborators: ["risk-compliance.fair-housing-guard", "lease-admin.resident-notice-preparation", "people-operations.sop-and-knowledge-operations"],
  },
  {
    id: "property-operations.property-incident-escalation",
    name: "Property Incident Escalation",
    domain: "property-operations",
    boundary: "Escalates an on-site incident, such as a break-in, injury, fire, flood or disturbance, to the right people in the order the workspace procedure sets and keeps the escalation log. Stops at escalation and handoff to incident intake; it does not investigate, assign fault or close the incident.",
    notThis: { specialist: "risk-compliance.incident-intake", because: "Incident intake records the incident for risk, insurance and claims; escalation gets the right people involved quickly and logs who was told when." },
    triggers: ["incident", "break-in", "injury", "police", "fire", "disturbance", "vandalism"],
    inputs: ["incident report", "workspace escalation procedure", "on-call and property contacts"],
    outputs: ["escalation log with who was contacted and when", "handoff to incident intake"],
    capabilities: ["incident.read", "communication.read", "staff.read", "task.route", "incident.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Each person the procedure names has acknowledged the escalation and the incident is recorded in incident intake.", notDoneWhen: "Messages were sent but nobody acknowledged, or the incident never reached incident intake." },
    forbidden: ["admit fault or liability in any message", "close the incident"],
    approvals: [],
    collaborators: ["risk-compliance.incident-intake", "people-operations.on-call-schedule", "maintenance.emergency-maintenance-triage"],
  },
  {
    id: "property-operations.property-calendar",
    name: "Property Calendar",
    domain: "property-operations",
    boundary: "Keeps one calendar per property of dated operational events: inspections, vendor visits, moves, amenity closures, community events, service outages and regulatory dates received from risk. Stops at an accurate calendar and conflict flags; it does not book the events.",
    notThis: { specialist: "risk-compliance.regulatory-calendar", because: "The regulatory calendar tracks legal and compliance deadlines; the property calendar shows everything happening at the property, including those deadlines, so the site can plan around them." },
    triggers: ["calendar", "schedule conflict", "what's happening", "outage", "event", "closure"],
    inputs: ["scheduled events from each domain", "regulatory dates", "resident-facing closures"],
    outputs: ["property calendar", "conflicts such as a water outage on a move-in day"],
    capabilities: ["property.read", "inspection.read", "work_order.read", "compliance.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every scheduled event at the property is on the calendar and each conflict has been sent to the owners of the clashing events.", notDoneWhen: "A conflict was visible on the calendar but nobody was told." },
    forbidden: ["move or cancel an event another specialist booked"],
    approvals: [],
    collaborators: ["property-operations.daily-operations-queue", "risk-compliance.regulatory-calendar", "inspections.inspection-scheduling"],
  },
  {
    id: "property-operations.operating-checklist",
    name: "Operating Checklist",
    domain: "property-operations",
    boundary: "Runs the property's recurring operating checklists, such as opening and closing rounds, weekly vacant-unit walks and monthly common-area checks, and records each item's result. Stops at the completed checklist with failures passed on; the checklists themselves are set by SOP.",
    notThis: { specialist: "inspections.exterior-and-common-area-inspection", because: "The exterior inspection is a formal condition inspection with evidence; the operating checklist is the routine site round that catches day-to-day issues." },
    triggers: ["checklist", "rounds", "opening checklist", "vacant walk", "site check"],
    inputs: ["workspace operating checklists by property", "staff results and photos"],
    outputs: ["completed checklist with each item's result", "failed items passed to maintenance or the property team"],
    capabilities: ["property.read", "sop.read", "maintenance.request.create", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Every checklist item has a recorded result and each failed item has a request or task with an owner.", notDoneWhen: "The checklist was marked complete with items left blank." },
    forbidden: ["mark a checklist item passed when no result was entered"],
    approvals: [],
    collaborators: ["people-operations.sop-and-knowledge-operations", "maintenance.service-request-intake", "property-operations.daily-operations-queue"],
  },
];
