/** Rent & Receivables — 14 Aval Specialists, coordinated by Rent & Receivables Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "receivables.rent-charge-schedule",
    name: "Rent Charge Schedule",
    domain: "receivables",
    boundary: "Generates the recurring charge schedule from each active lease — rent, recurring fees, concessions, escalations, and proration at start or end — and compares it with what the ledger will bill. Stops at a schedule awaiting approval; one-off charges and late fees are handled elsewhere.",
    notThis: { specialist: "finance.charge-posting-preparation", because: "Charge posting preparation handles individual non-recurring charges that each need their own authority; the schedule generates the recurring charges the lease itself sets." },
    triggers: ["rent charges", "recurring charges", "charge schedule", "proration", "rent escalation", "monthly charges"],
    inputs: ["active leases with rent, fees and concessions", "escalation dates", "move-in and move-out dates", "recurring charges currently in the ledger"],
    outputs: ["recurring charge schedule per lease", "differences between lease terms and the ledger's recurring charges"],
    capabilities: ["lease.read", "charge.read", "ledger.read", "charge.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every active lease has a schedule matching its terms, and every difference from the ledger's recurring charges is listed for approval.",
      notDoneWhen: "The schedule was copied from last month's charges without checking the lease terms.",
    },
    forbidden: ["carry a concession past the end date the lease gives", "apply a rent increase with no executed lease or notice behind it"],
    approvals: ["changes to recurring charges"],
    collaborators: ["lease-admin.rent-escalation-tracking", "lease-admin.lease-abstract", "finance.charge-posting-preparation"],
  },
  {
    id: "receivables.payment-posting-and-reconciliation",
    name: "Payment Posting & Reconciliation",
    domain: "receivables",
    boundary: "Posts a payment already received — lockbox, portal, check, subsidy — to the right resident ledger and charges, and reconciles posted receipts to the deposit batch. Stops at a posted, reconciled receipt; it never initiates or collects a payment, and a resident saying they paid opens reconciliation, not a posting.",
    notThis: { specialist: "finance.bank-reconciliation", because: "Bank reconciliation ties the whole cash account to the bank statement; this applies each resident receipt to a ledger and ties the batch to its deposit." },
    triggers: ["post payment", "payment received", "i paid", "unapplied payment", "deposit batch", "lockbox", "payment not showing"],
    inputs: ["receipt record with amount, date, payer and reference", "resident ledger and open charges", "deposit batch or bank deposit"],
    outputs: ["payment posted with charges applied and an external transaction reference", "batch reconciliation", "unidentified receipts held for review"],
    capabilities: ["payment.read", "ledger.read", "charge.read", "bank.read", "payment.post", "reconciliation.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The receipt is posted to the identified ledger with its external transaction reference, and the batch total equals the bank deposit.",
      notDoneWhen: "The payment was posted but the batch was not reconciled to the deposit, or a resident's claim of payment was posted without a receipt.",
    },
    forbidden: ["post a payment on a resident's statement without a matching receipt", "post one receipt twice under different references", "apply an unidentified receipt to a guessed ledger"],
    approvals: ["posting a payment to the ledger"],
    collaborators: ["finance.bank-reconciliation", "receivables.autopay-exception", "receivables.nsf-and-returned-payment", "resident-experience.payment-question-resolution", "affordable.subsidy-payment-exception"],
  },
  {
    id: "receivables.autopay-exception",
    name: "Autopay Exception",
    domain: "receivables",
    boundary: "Works autopay runs that did not go as scheduled: declined or failed pulls, expired payment methods, amounts that differ from the balance, residents dropped from enrollment. Stops at a per-resident exception with a prepared message; it does not retry a pull against a payment method.",
    notThis: { specialist: "receivables.nsf-and-returned-payment", because: "NSF handles a payment that posted and was later returned by the bank; autopay exceptions are scheduled pulls that failed or were wrong before any money arrived." },
    triggers: ["autopay failed", "autopay", "declined payment", "expired card", "recurring payment", "auto-debit"],
    inputs: ["autopay run results", "resident payment method status", "resident balance"],
    outputs: ["exception list by resident with the cause", "prepared resident message for each exception"],
    capabilities: ["payment.read", "ledger.read", "resident.read", "resident.message.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "Every failed or mismatched pull in the run has a recorded cause and a prepared or sent resident message.",
      notDoneWhen: "The run was reported as mostly successful without listing the failures.",
    },
    forbidden: ["retry a pull against a resident's payment method", "change a resident's autopay amount or date"],
    approvals: [],
    collaborators: ["receivables.payment-posting-and-reconciliation", "resident-experience.resident-portal-support", "receivables.delinquency-detection"],
  },
  {
    id: "receivables.outstanding-balance",
    name: "Outstanding Balance",
    domain: "receivables",
    boundary: "States one resident's or tenant's current balance with a charge-by-charge breakdown, payments applied, pending receipts, and the as-of time and source of each figure. Stops at the stated balance; it does not classify delinquency or decide next steps.",
    notThis: { specialist: "receivables.delinquency-detection", because: "Delinquency detection applies the workspace's policy to classify accounts; outstanding balance only states what one account owes and why." },
    triggers: ["balance", "how much do i owe", "amount due", "account balance", "ledger statement", "what's owed"],
    inputs: ["resident ledger", "open charges and applied payments", "receipts not yet posted"],
    outputs: ["balance with charge breakdown and as-of time", "pending items that may change it"],
    capabilities: ["ledger.read", "charge.read", "payment.read", "provenance.read"],
    execution: "deterministic",
    completion: {
      doneWhen: "The balance is stated with its as-of time and source, itemized so charges less payments equal the total.",
      notDoneWhen: "A total was quoted from a cached figure without its as-of time.",
    },
    forbidden: ["quote a balance without its as-of time and source", "omit receipts the ledger shows as pending"],
    approvals: [],
    collaborators: ["resident-experience.payment-question-resolution", "receivables.payment-posting-and-reconciliation", "receivables.delinquency-detection"],
  },
  {
    id: "receivables.delinquency-detection",
    name: "Delinquency Detection",
    domain: "receivables",
    boundary: "Classifies each account against the workspace's delinquency policy once the grace period has passed — days past due, amount, stage — and opens delinquency work for accounts that qualify. Stops at classification and opened work; reminders, notices, plans and fees are separate steps.",
    notThis: { specialist: "receivables.outstanding-balance", because: "Outstanding balance states what one account owes; delinquency detection applies the policy across accounts and opens the work." },
    triggers: ["delinquency", "delinquent", "past due", "arrears", "grace period", "aging"],
    inputs: ["resident ledgers", "workspace delinquency policy and grace period", "open payment plans", "receipts not yet posted"],
    outputs: ["delinquency stage per account with the policy rule matched", "opened delinquency work with an owner"],
    capabilities: ["delinquency.read", "ledger.read", "payment.read", "task.route"],
    execution: "deterministic",
    completion: {
      doneWhen: "Every account past the grace period has a policy stage recorded and, where the policy requires it, open delinquency work with an owner.",
      notDoneWhen: "A delinquency report was generated but no work was opened for the accounts that need it.",
    },
    forbidden: ["classify an account on a plan in good standing as delinquent", "classify an account delinquent while a received payment for it is still unposted"],
    approvals: [],
    collaborators: ["receivables.resident-reminder-and-notice-preparation", "receivables.outstanding-balance", "receivables.payment-plan-coordination", "receivables.late-fee-policy-check"],
  },
  {
    id: "receivables.resident-reminder-and-notice-preparation",
    name: "Resident Reminder & Notice Preparation",
    domain: "receivables",
    boundary: "Prepares the rent reminder or, when the policy stage requires it, the formal balance notice for a delinquent account, using the jurisdiction's template, timing and delivery method, and checks it is legally timely. Stops at a prepared notice for review; it does not serve it.",
    notThis: { specialist: "lease-admin.resident-notice-preparation", because: "Lease-admin notices concern lease terms and violations; this prepares reminders and balance notices tied to a delinquency stage and a ledger amount." },
    triggers: ["rent reminder", "pay or quit", "demand notice", "late notice", "balance notice", "notice to pay"],
    inputs: ["delinquency stage and balance", "jurisdiction notice rule record with effective date", "lease notice clause", "resident contact and delivery preferences"],
    outputs: ["prepared reminder or formal notice with amount, dates and delivery method", "timeliness check against the jurisdiction rule"],
    capabilities: ["delinquency.read", "ledger.read", "lease.read", "compliance.read", "notice.prepare", "resident.message.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "A reminder is sent under the communication policy, or a formal notice with a passing timeliness check is awaiting authorized review.",
      notDoneWhen: "A formal notice was drafted and treated as served.",
    },
    forbidden: ["include in a formal notice an amount the jurisdiction does not allow it to demand", "state a legal consequence the approved template does not contain"],
    approvals: ["sending a formal balance notice"],
    collaborators: ["receivables.delinquency-detection", "lease-admin.resident-notice-preparation", "risk-compliance.regulatory-calendar", "receivables.outstanding-balance"],
  },
  {
    id: "receivables.payment-plan-coordination",
    name: "Payment Plan Coordination",
    domain: "receivables",
    boundary: "Builds a payment plan from the balance, the resident's proposal and the workspace plan policy, gets it approved, and creates it in the system of record once approved. Stops when the plan exists and the resident has its terms; missed installments return to delinquency detection.",
    notThis: { specialist: "receivables.bad-debt-review", because: "Bad debt review decides whether a balance is still collectible at all; payment plan coordination arranges collection of a balance the resident intends to pay." },
    triggers: ["payment plan", "installments", "can i pay in parts", "repayment agreement", "split payments", "catch up on rent"],
    inputs: ["outstanding balance", "resident proposal", "workspace payment plan policy", "jurisdiction rules affecting plans"],
    outputs: ["prepared plan with installment dates and amounts", "approval request", "plan created in the system of record after approval"],
    capabilities: ["ledger.read", "delinquency.read", "payment_plan.prepare", "payment_plan.create", "resident.message.prepare"],
    execution: "child_run",
    completion: {
      doneWhen: "The approved plan exists in the system of record, its installments sum to the agreed balance, and the resident has been sent the terms.",
      notDoneWhen: "The resident agreed to a plan in conversation but no approved plan was created.",
    },
    forbidden: ["create a plan before a person with authority approves it", "offer terms outside the workspace plan policy"],
    approvals: ["payment plan terms"],
    collaborators: ["receivables.outstanding-balance", "receivables.delinquency-detection", "resident-experience.payment-question-resolution"],
  },
  {
    id: "receivables.late-fee-policy-check",
    name: "Late Fee Policy Check",
    domain: "receivables",
    boundary: "Decides whether a late fee may be charged on an account and how much: the lease clause, the grace period, the jurisdiction's cap and timing rule in effect on the fee date, and any plan or hold that suspends it. Returns allowed, amount and rules cited; it does not post the fee.",
    notThis: { specialist: "receivables.delinquency-detection", because: "Delinquency detection classifies the account; the late fee check decides whether one specific fee is permitted and its amount." },
    triggers: ["late fee", "late charge", "fee cap", "waive late fee", "grace period ended"],
    inputs: ["lease late-fee clause", "jurisdiction late-fee rule record with effective date", "charge and payment dates", "active payment plan or hold"],
    outputs: ["allowed or not allowed with amount", "lease clause and jurisdiction rule cited", "prepared fee charge when allowed"],
    capabilities: ["lease.read", "ledger.read", "compliance.read", "charge.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "The result cites the lease clause and a jurisdiction rule record in effect on the fee date, and any allowed fee is prepared for approval.",
      notDoneWhen: "A fee was computed from the lease alone without a jurisdiction rule record.",
    },
    forbidden: ["apply a default late-fee rule where the property's jurisdiction has no rule record", "compute a fee above the lower of the lease amount and the jurisdiction cap"],
    approvals: ["posting a late fee"],
    collaborators: ["lease-admin.lease-clause-extraction", "risk-compliance.regulatory-calendar", "finance.charge-posting-preparation"],
  },
  {
    id: "receivables.nsf-and-returned-payment",
    name: "NSF & Returned Payment",
    domain: "receivables",
    boundary: "Handles a payment the bank returned after posting: prepares the ledger reversal, any returned-payment fee the lease and jurisdiction allow, and payment-method restrictions the written policy requires, and notifies the resident. Stops at prepared reversal, fee and message; it does not collect a replacement.",
    notThis: { specialist: "receivables.autopay-exception", because: "Autopay exceptions are pulls that failed before money arrived; NSF handles a payment that posted and was later reversed by the bank." },
    triggers: ["nsf", "returned payment", "bounced check", "insufficient funds", "reversed payment", "ach return"],
    inputs: ["bank return notice with reason code", "the posted payment", "lease returned-payment clause", "jurisdiction fee rule record", "payment method policy"],
    outputs: ["prepared payment reversal", "prepared returned-payment fee if allowed", "prepared resident notification"],
    capabilities: ["payment.read", "bank.read", "ledger.read", "compliance.read", "charge.prepare", "resident.message.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The reversal and any fee are prepared for approval, the balance reflects the return, and the resident has been notified.",
      notDoneWhen: "The return was noted but the original payment still shows as paid on the ledger.",
    },
    forbidden: ["charge a returned-payment fee the lease or jurisdiction does not allow", "restrict a resident's payment methods beyond the written policy"],
    approvals: ["payment reversal", "returned-payment fee"],
    collaborators: ["receivables.payment-posting-and-reconciliation", "receivables.late-fee-policy-check", "receivables.delinquency-detection"],
  },
  {
    id: "receivables.collections-placement-preparation",
    name: "Collections Placement Preparation",
    domain: "receivables",
    boundary: "Prepares a former resident's account for placement with a collection agency: final itemized balance, deposit applied, notices sent, dispute history, and the agency's required fields. Stops at a placement packet for approval; it does not contact the debtor or send the file.",
    notThis: { specialist: "receivables.bad-debt-review", because: "Bad debt review decides whether to write off or pursue a balance; placement prepares the packet once pursuit through an agency is chosen." },
    triggers: ["collections", "send to collections", "collection agency", "former resident balance", "placement"],
    inputs: ["final account statement", "deposit statement and delivery record", "notice and dispute history", "agency placement requirements", "jurisdiction collection rules"],
    outputs: ["placement packet with itemized balance and history", "missing items that block placement"],
    capabilities: ["ledger.read", "deposit.read", "document.read", "communication.read", "compliance.read", "collections.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The packet is complete against the agency's required fields, its balance reconciles to the final statement and deposit disposition, and it awaits approval.",
      notDoneWhen: "A balance was exported to the agency template without the deposit disposition or dispute history.",
    },
    forbidden: ["prepare placement for an account with an open dispute", "prepare placement before the required deposit statement was delivered"],
    approvals: ["placing an account with a collection agency"],
    collaborators: ["receivables.bad-debt-review", "receivables.move-out-receivable-and-deposit-withholding", "lease-admin.legal-and-eviction-handoff"],
  },
  {
    id: "receivables.bad-debt-review",
    name: "Bad Debt Review",
    domain: "receivables",
    boundary: "Reviews aged balances unlikely to be collected and recommends, per account, write-off, allowance, collections placement or continued pursuit, with recovery history and the accounting effect. Stops at recommendations and prepared entries; the decision is a person's.",
    notThis: { specialist: "receivables.collections-placement-preparation", because: "Collections placement prepares one account's agency packet; bad debt review decides across aged accounts which ones to pursue, reserve or write off." },
    triggers: ["bad debt", "write off", "uncollectible", "allowance", "aged receivables", "doubtful accounts"],
    inputs: ["aged receivables", "collection and payment plan history", "workspace write-off policy"],
    outputs: ["recommendation per account with reason", "prepared write-off or allowance entries"],
    capabilities: ["ledger.read", "delinquency.read", "gl.read", "journal_entry.prepare", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "Each reviewed account has a recommendation with its reason, and every recommended write-off has an entry awaiting approval.",
      notDoneWhen: "Balances were marked uncollectible without prepared entries or approval.",
    },
    forbidden: ["write off a balance without approval", "recommend write-off for an account on a payment plan in good standing"],
    approvals: ["write-off or allowance entries"],
    collaborators: ["receivables.collections-placement-preparation", "finance.journal-entry-preparation", "receivables.ar-forecast"],
  },
  {
    id: "receivables.move-out-receivable-and-deposit-withholding",
    name: "Move-Out Receivable & Deposit Withholding",
    domain: "receivables",
    boundary: "At move-out, totals the final balance, decides which charges may be deducted from the deposit under the lease, the inspection evidence and the jurisdiction's permitted deductions and deadline, and prepares the itemized deposit statement. Stops at a prepared statement and the refund or balance due.",
    notThis: { specialist: "finance.deposit-accounting", because: "Deposit accounting books the liability and its disposition; this decides which deductions are allowed and prepares the resident's statement." },
    triggers: ["move-out balance", "deposit deductions", "itemized statement", "final account", "withhold deposit", "deposit statement"],
    inputs: ["final ledger", "move-out inspection with photos", "lease deposit and damage clauses", "jurisdiction deposit rule record with deadline and permitted deductions", "forwarding address"],
    outputs: ["itemized deposit statement with evidence per deduction", "refund or balance-due amount", "statement delivery deadline"],
    capabilities: ["ledger.read", "deposit.read", "inspection.read", "lease.read", "compliance.read", "deposit.prepare"],
    execution: "child_run",
    completion: {
      doneWhen: "The itemized statement has evidence for every deduction, is approved, and is scheduled for delivery before the jurisdiction's deadline.",
      notDoneWhen: "Deductions were totalled but the statement was not approved or its delivery deadline was not set.",
    },
    forbidden: ["deduct normal wear as damage", "deduct a charge without inspection or invoice evidence", "let the statement deadline approach without escalating a pending approval"],
    approvals: ["deposit deductions and the deposit statement"],
    collaborators: ["inspections.move-out-inspection", "finance.deposit-accounting", "lease-admin.move-out-obligation-review", "lease-admin.security-deposit-terms-review", "receivables.collections-placement-preparation"],
  },
  {
    id: "receivables.rent-reporting-coordination",
    name: "Rent Reporting Coordination",
    domain: "receivables",
    boundary: "Prepares the rent payment data a workspace reports to credit bureaus or rent reporting services for residents who have opted in, and records resident disputes about reported data with the ledger evidence. Stops at a consent-checked file and dispute record; it does not submit the file.",
    notThis: { specialist: "resident-experience.resident-benefits-coordination", because: "Benefits coordination enrolls residents in programs such as credit building; rent reporting prepares the payment data itself and handles disputes about it." },
    triggers: ["rent reporting", "credit reporting", "report to bureau", "credit builder", "reporting dispute"],
    inputs: ["resident opt-in and consent records", "payment history", "reporting service format", "open disputes"],
    outputs: ["reporting file limited to consented residents", "dispute record with the ledger evidence"],
    capabilities: ["payment.read", "ledger.read", "resident.read", "document.read", "report.prepare"],
    execution: "expertise",
    completion: {
      doneWhen: "The file includes only residents with recorded consent, each record matches the ledger, and disputed items are excluded or marked.",
      notDoneWhen: "A file was generated for all residents without checking consent.",
    },
    forbidden: ["include a resident without recorded consent", "report an amount under dispute as delinquent"],
    approvals: ["submitting the reporting file"],
    collaborators: ["receivables.outstanding-balance", "risk-compliance.privacy-and-data-request", "resident-experience.resident-benefits-coordination"],
  },
  {
    id: "receivables.ar-forecast",
    name: "AR Forecast",
    domain: "receivables",
    boundary: "Projects collections for the coming weeks or months from scheduled charges, historical collection rates by delinquency stage, payment plan installments and autopay enrollment, with method and inputs stated. Stops at the forecast; it does not change charges or collection actions.",
    notThis: { specialist: "finance.cash-flow-analysis", because: "Cash flow analysis combines collections with payables, capital and owner movements; the AR forecast projects collections alone." },
    triggers: ["ar forecast", "collections forecast", "expected collections", "projected rent", "collection rate"],
    inputs: ["scheduled charges", "historical collection rates by delinquency stage", "payment plan installments", "autopay enrollment"],
    outputs: ["projected collections by period with method named", "range and the assumptions behind it"],
    capabilities: ["charge.read", "ledger.read", "delinquency.read", "analytics.read", "report.prepare"],
    execution: "deterministic",
    completion: {
      doneWhen: "The forecast states its window, method, inputs and their as-of dates, and reproduces from the same inputs.",
      notDoneWhen: "A projected figure was given without the rates or window it came from.",
    },
    forbidden: ["present forecast collections as collected revenue", "count unposted resident promises to pay as receipts"],
    approvals: [],
    collaborators: ["finance.cash-flow-analysis", "receivables.delinquency-detection", "receivables.bad-debt-review"],
  },
];
