/** Renewals & Retention — 10 Aval Specialists, coordinated by Renewals & Retention Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "renewals.renewal-eligibility",
    name: "Renewal Eligibility",
    domain: "renewals",
    boundary: "Checks an expiring lease against the written renewal policy and the jurisdiction rules on record: balance, open lease violations, owner instructions, program status and any rule that requires a renewal offer. Returns eligible, not eligible or needs review with reasons; it does not price or contact.",
    notThis: { specialist: "renewals.retention-risk", because: "Eligibility decides whether a standard offer may be made under policy; retention risk estimates how likely an eligible resident is to leave." },
    triggers: ["eligible for renewal", "can we renew", "renewal policy", "do not renew", "renewal check"],
    inputs: ["expiring lease", "ledger balance and open violations", "written renewal policy version", "jurisdiction renewal rules on record"],
    outputs: ["eligible, not eligible or needs review per lease", "the policy and rule version behind each result"],
    capabilities: ["lease.read", "renewal.read", "ledger.read", "compliance.read", "resident.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every lease in the renewal window has a recorded result citing the policy version and reasons.", notDoneWhen: "Eligibility was inferred from the balance alone without the policy and jurisdiction checks." },
    forbidden: ["mark a lease ineligible where the jurisdiction's just-cause or tenant-protection rules require a renewal offer", "use a factor outside the written policy, such as a repair request, complaint or accommodation request the resident made"],
    approvals: ["not-eligible results before they take effect"],
    collaborators: ["renewals.lease-expiration-monitor", "receivables.outstanding-balance", "lease-admin.lease-violation-workflow", "renewals.non-renewal-handoff"],
  },
  {
    id: "renewals.lease-expiration-monitor",
    name: "Lease Expiration Monitor",
    domain: "renewals",
    boundary: "Watches lease end dates against the workspace's renewal window and the notice lead time the jurisdiction rule on record sets for each unit, and opens renewal work on time. Flags leases rolling to month-to-month or expiring with no renewal work. Stops at opened work.",
    notThis: { specialist: "lease-admin.critical-date-tracking", because: "Critical date tracking keeps every lease date (options, escalations, notices); this monitor watches the renewal window and opens renewal work from it." },
    triggers: ["leases expiring", "expiration report", "renewal window", "month-to-month", "upcoming expirations"],
    inputs: ["lease end dates", "workspace renewal window", "jurisdiction notice lead times on record"],
    outputs: ["renewal work opened per expiring lease with its offer deadline", "flags for leases with no renewal work"],
    capabilities: ["lease.read", "renewal.read", "compliance.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Every lease expiring in the window has renewal work opened by the window's start, carrying its jurisdiction offer deadline.", notDoneWhen: "An expirations list was produced but renewal work was not opened for each lease on it." },
    forbidden: ["compute an offer deadline from a fixed notice period instead of the jurisdiction rule on record for the unit", "close an expiration because an offer was sent"],
    approvals: [],
    collaborators: ["renewals.renewal-eligibility", "lease-admin.critical-date-tracking", "risk-compliance.regulatory-calendar"],
  },
  {
    id: "renewals.renewal-pricing-support",
    name: "Renewal Pricing Support",
    domain: "renewals",
    boundary: "Prepares a recommended renewal rent per lease from the customer's own data (current rent, its own like-unit rents, retention risk, policy caps) and public comparables, and checks it against the rent increase limits on record. Stops at a recommendation a person approves.",
    notThis: { specialist: "market-revenue.renewal-market-analysis", because: "Renewal market analysis describes the market renewals face; pricing support turns it into a per-lease recommendation checked against caps." },
    triggers: ["renewal rent", "renewal increase", "how much to raise", "renewal pricing", "rent cap"],
    inputs: ["current lease rent and term", "the customer's own like-unit rents", "public comparables with provenance", "retention risk", "jurisdiction increase limits on record"],
    outputs: ["recommended rent per lease with the provenance of each input", "cap check result", "recommendation queued for approval"],
    capabilities: ["lease.read", "renewal.read", "market.public.read", "market.comparables.read", "pricing.recommend", "compliance.read"],
    execution: "expertise",
    completion: { doneWhen: "Each lease has a recommended rent with input provenance, a cap check result, and a recorded approval or rejection.", notDoneWhen: "A number was computed but not approved, or approved without the cap check." },
    forbidden: ["use a competitor's nonpublic rent, occupancy or renewal data", "recommend an increase above the rent stabilisation or increase limit on record for the unit"],
    approvals: ["renewal rent per lease or per policy tier"],
    collaborators: ["market-revenue.renewal-market-analysis", "renewals.retention-risk", "market-revenue.rent-comparable-research", "renewals.renewal-offer-preparation"],
  },
  {
    id: "renewals.renewal-offer-preparation",
    name: "Renewal Offer Preparation",
    domain: "renewals",
    boundary: "Assembles the renewal offer from approved rent and term options: offer letter, term choices, any approved incentive, response deadline and the notice content the jurisdiction rule on record requires for an increase. Stops at an approved offer document; delivery is outreach's job.",
    notThis: { specialist: "renewals.renewal-outreach", because: "Offer preparation produces the approved document; outreach delivers it, proves delivery and follows up for an answer." },
    triggers: ["renewal offer", "renewal letter", "prepare offer", "term options", "increase notice"],
    inputs: ["approved rent and terms", "approved incentive", "jurisdiction notice requirements on record", "offer templates"],
    outputs: ["renewal offer document", "rent increase notice content where required", "latest delivery date meeting the lead time"],
    capabilities: ["lease.read", "renewal.read", "renewal.prepare", "notice.prepare", "compliance.read"],
    execution: "deterministic",
    completion: { doneWhen: "The offer is approved and its delivery date meets the jurisdiction lead time on record.", notDoneWhen: "The offer was drafted but not approved, or its delivery date would miss the notice lead time." },
    forbidden: ["include a rent, term or incentive that has not been approved", "omit a notice element the jurisdiction rule on record requires for an increase"],
    approvals: ["renewal offer document"],
    collaborators: ["renewals.renewal-pricing-support", "renewals.renewal-outreach", "lease-admin.resident-notice-preparation"],
  },
  {
    id: "renewals.renewal-outreach",
    name: "Renewal Outreach",
    domain: "renewals",
    boundary: "Delivers approved renewal offers by a method the notice rules accept, records the delivery and its proof, and follows up on the workspace's cadence until the resident accepts, declines or counters. Stops at a recorded response; counters go to negotiation support.",
    notThis: { specialist: "renewals.renewal-negotiation-support", because: "Outreach delivers the offer and gets an answer; negotiation support prepares the response when the answer is a counter-offer." },
    triggers: ["send renewal", "renewal follow-up", "no response to renewal", "renewal reminder", "offer delivered"],
    inputs: ["approved offer", "resident contact preferences", "accepted delivery methods on record"],
    outputs: ["delivery record with proof", "follow-ups on cadence", "resident response: accept, decline or counter"],
    capabilities: ["renewal.read", "resident.read", "communication.read", "resident.message.send"],
    execution: "expertise",
    completion: { doneWhen: "The resident's response is recorded, or the offer's expiry is recorded with the delivery proof.", notDoneWhen: "The offer was sent and no response or expiry is recorded." },
    forbidden: ["deliver a rent increase notice by a method the jurisdiction rule on record does not accept", "press a resident with a deadline or consequence not in the approved offer"],
    approvals: [],
    collaborators: ["renewals.renewal-negotiation-support", "renewals.renewal-execution-coordination", "resident-experience.resident-inbox"],
  },
  {
    id: "renewals.renewal-negotiation-support",
    name: "Renewal Negotiation Support",
    domain: "renewals",
    boundary: "When a resident counters, prepares response options within the recorded negotiation authority (term swaps, approved incentive ranges), escalates anything beyond it, and records the terms finally agreed. Stops at agreed terms; it does not set incentive policy.",
    notThis: { specialist: "renewals.renewal-incentive-strategy", because: "Negotiation support answers one resident's counter within set ranges; incentive strategy sets those ranges for a property or portfolio." },
    triggers: ["counter offer", "resident wants lower rent", "negotiate renewal", "can you do better", "match offer"],
    inputs: ["resident counter and thread", "approved offer", "negotiation authority ranges"],
    outputs: ["response options within authority", "escalation beyond authority", "agreed terms recorded"],
    capabilities: ["renewal.read", "renewal.prepare", "lease.read", "communication.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Agreed terms are recorded and within authority or approved, or the counter is declined with the resident told.", notDoneWhen: "A counter was received and acknowledged but no response or escalation was made." },
    forbidden: ["use a resident's hardship, disability or accommodation request as negotiating leverage", "give residents different concessions for anything other than the policy's own factors (unit, term, tenure, market)"],
    approvals: ["counter-offer outside the pre-approved range"],
    collaborators: ["renewals.renewal-outreach", "renewals.renewal-pricing-support", "renewals.renewal-execution-coordination"],
  },
  {
    id: "renewals.retention-risk",
    name: "Retention Risk",
    domain: "renewals",
    boundary: "Ranks residents with expiring leases by likelihood of leaving from operational signals (repeat work orders, open complaints, rent gap to market, survey answers, move-out questions), citing the signals behind each, so outreach starts early. Stops at the ranking; it never feeds eligibility.",
    notThis: { specialist: "renewals.renewal-eligibility", because: "Retention risk estimates who may leave; eligibility decides under policy whether a standard offer may be made at all." },
    triggers: ["retention risk", "who might leave", "at risk residents", "likely to move out", "retention"],
    inputs: ["expiring leases", "work order and complaint history", "survey responses", "rent against the customer's own market rents"],
    outputs: ["ranked list with cited signals per resident", "suggested early action for high-risk leases"],
    capabilities: ["resident.read", "lease.read", "maintenance.read", "communication.read", "analytics.read"],
    execution: "expertise",
    completion: { doneWhen: "Each lease in the window has a ranking with cited signals and every high-risk lease has an assigned action.", notDoneWhen: "Scores were computed but high-risk leases have no action or owner." },
    forbidden: ["use a protected characteristic or a proxy such as household make-up as a signal", "pass the ranking into renewal eligibility"],
    approvals: [],
    collaborators: ["resident-experience.resident-satisfaction-and-feedback", "maintenance.repeat-issue-analysis", "renewals.renewal-pricing-support", "renewals.renewal-outreach"],
  },
  {
    id: "renewals.renewal-incentive-strategy",
    name: "Renewal Incentive Strategy",
    domain: "renewals",
    boundary: "Designs the property or portfolio renewal incentive rules (early-signing discount, upgrade credit, term-length pricing) within budget, weighing incentive cost against the turn and vacancy cost avoided. Stops at a policy proposal for approval; it does not negotiate with residents.",
    notThis: { specialist: "renewals.renewal-negotiation-support", because: "Incentive strategy sets the ranges for a property; negotiation support works one resident's counter inside them." },
    triggers: ["renewal incentive", "renewal concession", "early renewal discount", "retention budget", "incentive policy"],
    inputs: ["renewal outcomes history", "turn and vacancy costs", "retention budget", "concession analysis from the customer's own and public data"],
    outputs: ["incentive policy proposal with cost and expected effect", "negotiation authority ranges"],
    capabilities: ["renewal.read", "turn.read", "budget.read", "analytics.read", "report.prepare"],
    execution: "expertise",
    completion: { doneWhen: "An incentive policy with its budget and ranges is approved and recorded for the properties in scope.", notDoneWhen: "A proposal was written but not approved, or approved without the ranges negotiation uses." },
    forbidden: ["coordinate incentive levels with other owners or managers outside the workspace", "target incentives by a protected characteristic or a proxy for one"],
    approvals: ["incentive policy and its budget"],
    collaborators: ["market-revenue.concession-analysis", "turns.turn-budget", "renewals.retention-risk", "owner-services.owner-approval-coordination"],
  },
  {
    id: "renewals.renewal-execution-coordination",
    name: "Renewal Execution Coordination",
    domain: "renewals",
    boundary: "Once a resident accepts, gets the renewal lease or amendment drafted from the accepted terms, signed by every required party and countersigned, then updates the lease record and requests the new rent charge schedule. Stops at the new lease state.",
    notThis: { specialist: "lease-admin.lease-execution-preparation", because: "Execution preparation readies any lease document for signature; this carries an accepted renewal through signature to an updated lease record and charge schedule." },
    triggers: ["renewal accepted", "sign renewal", "renewal signed", "countersign", "update lease term"],
    inputs: ["accepted terms", "renewal document", "signature status", "current charge schedule"],
    outputs: ["executed renewal stored", "lease record showing the new term and rent", "charge schedule change request"],
    capabilities: ["renewal.read", "lease.read", "lease.draft", "lease.status.update", "task.route"],
    execution: "child_run",
    completion: { doneWhen: "The executed renewal with every signature is stored, the lease record shows the new term, and the charge schedule change is confirmed.", notDoneWhen: "The resident signed but the landlord has not countersigned, or it is signed but the charge schedule is unchanged." },
    forbidden: ["mark the lease renewed before every required signature is on the executed document", "change any term in the document from what the resident accepted"],
    approvals: ["landlord countersignature"],
    collaborators: ["lease-admin.lease-draft-assembly", "lease-admin.lease-execution-preparation", "receivables.rent-charge-schedule", "renewals.renewal-outreach"],
  },
  {
    id: "renewals.non-renewal-handoff",
    name: "Non-Renewal Handoff",
    domain: "renewals",
    boundary: "When a resident declines or a lease will not be renewed, records the reason, confirms the resident's written notice to vacate or prepares the landlord's non-renewal notice for legal review, and opens move-out work in turns, receivables and leasing. Stops at the handoffs.",
    notThis: { specialist: "lease-admin.legal-and-eviction-handoff", because: "That hands a tenancy to legal action; this closes a tenancy at its term end and opens move-out work." },
    triggers: ["not renewing", "notice to vacate", "resident declined renewal", "non-renewal", "moving out at end of lease"],
    inputs: ["resident response or owner decision", "lease notice requirements", "jurisdiction non-renewal rules on record"],
    outputs: ["recorded non-renewal with reason, notice date and move-out date", "landlord notice prepared for review where needed", "move-out work opened"],
    capabilities: ["lease.read", "renewal.read", "notice.prepare", "compliance.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "The non-renewal is recorded with notice and move-out dates, and move-out work is open in turns, receivables and leasing.", notDoneWhen: "The decline was noted but no notice is on record or move-out work is not opened." },
    forbidden: ["prepare a landlord non-renewal notice where just-cause rules on record apply without routing it to legal review", "treat a spoken intention to move as notice to vacate where the lease requires written notice"],
    approvals: ["landlord-initiated non-renewal notice"],
    collaborators: ["turns.move-out-scope-intake", "receivables.move-out-receivable-and-deposit-withholding", "leasing-marketing.vacancy-marketing", "lease-admin.move-out-obligation-review", "lease-admin.legal-and-eviction-handoff"],
  },
];
