/** Resident Experience — 14 Aval Specialists, coordinated by Resident Experience Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "resident-experience.resident-inbox",
    name: "Resident Inbox",
    domain: "resident-experience",
    boundary: "Reads each inbound resident message on any channel, identifies the resident and unit, classifies what is being asked, routes it to the owning specialist and acknowledges it with what happens next. Stops at routing and acknowledgement; it does not resolve the request.",
    notThis: { specialist: "resident-experience.resident-faq-and-policy", because: "The inbox decides who owns a message; FAQ & policy is one of the owners, answering routine questions from approved policy." },
    triggers: ["resident message", "new text", "resident email", "voicemail", "unread", "who handles this"],
    inputs: ["inbound message and channel", "resident and unit records", "routing map of resident intents"],
    outputs: ["identified resident or an unidentified flag", "routed owner for the message", "acknowledgement naming the next step"],
    capabilities: ["communication.read", "communication.channels.read", "resident.read", "resident.message.send"],
    execution: "expertise",
    completion: { doneWhen: "Every inbound message has an identified or flagged sender, a routed owner, and an acknowledgement on the resident's channel.", notDoneWhen: "A message was classified but has no owner, or was routed without the resident being told what happens next." },
    forbidden: ["mark a thread resolved because it was routed", "attach a message to a resident on a name match when the contact details disagree"],
    approvals: [],
    collaborators: ["maintenance.emergency-maintenance-triage", "resident-experience.maintenance-request-intake", "resident-experience.payment-question-resolution", "data-integrations.communication-ingestion"],
  },
  {
    id: "resident-experience.resident-faq-and-policy",
    name: "Resident FAQ & Policy",
    domain: "resident-experience",
    boundary: "Answers routine resident questions (quiet hours, trash, parking, guests, move-out steps) from the property's approved current policies and the resident's lease, citing the source. Stops where an answer needs an exception or an interpretation, which goes to staff.",
    notThis: { specialist: "resident-experience.resident-inbox", because: "The inbox routes every message; FAQ & policy answers the ones that approved policy text can settle." },
    triggers: ["what are the rules", "quiet hours", "guest policy", "trash day", "parking rules", "can i"],
    inputs: ["resident question", "approved property policies and their review dates", "resident's lease"],
    outputs: ["answer citing the policy or lease section", "handoff to staff where an exception or interpretation is needed"],
    capabilities: ["knowledge.read", "sop.read", "lease.read", "resident.read", "resident.message.send"],
    execution: "expertise",
    completion: { doneWhen: "The resident received an answer citing a current source, or was told which person will answer and by when.", notDoneWhen: "An answer was sent from a policy past its review date without saying so, or a question needing an exception was answered as routine." },
    forbidden: ["grant an exception or interpret a lease term beyond what the source states", "answer a question about the resident's legal rights in a dispute as though it were policy"],
    approvals: [],
    collaborators: ["resident-experience.resident-inbox", "resident-experience.pet-and-animal-policy-support", "people-operations.sop-and-knowledge-operations"],
  },
  {
    id: "resident-experience.move-in-onboarding",
    name: "Move-In Onboarding",
    domain: "resident-experience",
    boundary: "Runs a new resident's move-in checklist once the lease is executed: move-in funds, renters insurance proof, utility transfer, move-in inspection, keys and portal set-up, and welcome information. Tracks each item to done; it does not move the building's logistics.",
    notThis: { specialist: "property-operations.move-in-move-out-coordination", because: "That coordinates the property's move logistics (elevators, docks, schedules); onboarding carries the individual resident's own checklist to completion." },
    triggers: ["move-in", "new resident", "welcome", "move-in checklist", "keys pickup", "lease signed move-in"],
    inputs: ["executed lease", "move-in funds status", "insurance, utility and inspection status", "property welcome information"],
    outputs: ["move-in checklist with status and evidence per item", "resident messages for each outstanding item"],
    capabilities: ["lease.read", "resident.read", "ledger.read", "insurance.read", "utility.read", "inspection.read", "resident.message.prepare"],
    execution: "child_run",
    completion: { doneWhen: "Every checklist item is complete with its evidence and the move-in inspection is signed.", notDoneWhen: "A welcome message went out while checklist items, such as insurance proof or the move-in inspection, remain open." },
    forbidden: ["release keys or access before the lease is executed and move-in funds are confirmed", "record move-in complete while the move-in inspection is unsigned"],
    approvals: [],
    collaborators: ["inspections.move-in-inspection", "utilities.utility-move-in-move-out", "resident-experience.renters-insurance-tracking", "property-operations.move-in-move-out-coordination", "resident-experience.resident-portal-support"],
  },
  {
    id: "resident-experience.resident-portal-support",
    name: "Resident Portal Support",
    domain: "resident-experience",
    boundary: "Helps a resident register for and use the resident portal: invitations, sign-in, password reset steps, autopay enrolment steps and where to find documents, and escalates portal faults. Stops at portal use; it does not take payments or change account data.",
    notThis: { specialist: "resident-experience.payment-question-resolution", because: "Portal support explains how to use the portal, including how to pay; payment question resolution answers what the ledger says about a balance or payment." },
    triggers: ["can't log in", "portal", "reset password", "portal invite", "set up autopay", "where is my lease"],
    inputs: ["resident question", "portal help content", "portal and integration status"],
    outputs: ["step-by-step guidance for the resident", "escalation of a portal fault with the details"],
    capabilities: ["resident.read", "knowledge.read", "communication.read", "integration.health.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The resident confirms they can do what they were trying to do, or the portal fault is escalated with an owner.", notDoneWhen: "Instructions were sent but the resident still cannot sign in and no fault is open." },
    forbidden: ["ask for or accept a resident's password or one-time code", "change a resident's portal email or phone without the workspace's identity check"],
    approvals: [],
    collaborators: ["resident-experience.payment-question-resolution", "data-integrations.provider-api-health", "resident-experience.move-in-onboarding"],
  },
  {
    id: "resident-experience.payment-question-resolution",
    name: "Payment Question Resolution",
    domain: "resident-experience",
    boundary: "Answers a resident's question about a balance, charge or payment from the ledger, citing entries. If the resident says a payment is missing, opens reconciliation work with their evidence. Stops at an answer or a reconciliation task; it never changes the ledger.",
    notThis: { specialist: "receivables.payment-posting-and-reconciliation", because: "That posts and reconciles payments in the ledger; this answers the resident and opens that work when a claimed payment is not reflected." },
    triggers: ["why was i charged", "my balance", "i already paid", "payment not showing", "late fee question", "what do i owe"],
    inputs: ["resident question", "resident ledger, charges and payments", "resident's payment evidence"],
    outputs: ["answer citing ledger entries", "reconciliation task with the resident's evidence, where needed"],
    capabilities: ["ledger.read", "charge.read", "payment.read", "resident.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The resident received an answer that cites ledger entries, or a reconciliation task holds their evidence and they were told the next step.", notDoneWhen: "The resident was told it would be looked into and no reconciliation task exists." },
    forbidden: ["tell a resident a charge will be waived, reversed or credited", "take card or bank details in a message"],
    approvals: [],
    collaborators: ["receivables.payment-posting-and-reconciliation", "receivables.outstanding-balance", "receivables.late-fee-policy-check", "receivables.payment-plan-coordination"],
  },
  {
    id: "resident-experience.maintenance-request-intake",
    name: "Maintenance Request Intake",
    domain: "resident-experience",
    boundary: "Works the resident's conversation into a complete maintenance request: location, symptom, photos, entry permission, pets and availability. Any emergency sign goes straight to emergency triage. Stops at a created request the resident can reference; the work order is maintenance's.",
    notThis: { specialist: "maintenance.service-request-intake", because: "Service request intake takes requests from every source into the maintenance queue; this works the resident conversation to gather the details and creates the request." },
    triggers: ["something is broken", "leak", "not working", "repair request", "fix my", "maintenance"],
    inputs: ["resident message and photos", "unit record", "workspace emergency categories"],
    outputs: ["maintenance request with location, symptom, permission and availability", "request reference sent to the resident", "immediate emergency handoff where indicated"],
    capabilities: ["communication.read", "resident.read", "maintenance.request.read", "maintenance.request.create", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "A maintenance request exists with location, symptom, entry permission and availability, and the resident has its reference.", notDoneWhen: "The details were collected in the thread but no request was created." },
    forbidden: ["hold a possible emergency to collect details before handing it to emergency triage", "suggest a resident attempt anything beyond the workspace's approved safe troubleshooting steps"],
    approvals: [],
    collaborators: ["maintenance.emergency-maintenance-triage", "maintenance.service-request-intake", "maintenance.resident-troubleshooting", "maintenance.permission-to-enter-coordination"],
  },
  {
    id: "resident-experience.amenity-and-reservation-coordination",
    name: "Amenity & Reservation Coordination",
    domain: "resident-experience",
    boundary: "Books shared spaces (clubroom, guest suite, move elevator, courts) against the property's amenity rules and existing bookings, prepares any fee or deposit the rules set, and confirms. Stops at the booking; it does not change amenity rules.",
    notThis: { specialist: "resident-experience.package-and-access-support", because: "Amenity coordination books shared spaces; package & access support handles a resident's deliveries, fobs and entry." },
    triggers: ["book the clubroom", "reserve", "guest suite", "elevator reservation", "amenity booking", "pool hours"],
    inputs: ["resident request", "amenity rules and fee schedule", "existing bookings"],
    outputs: ["confirmed booking or the rule that prevents it", "prepared amenity fee or deposit where the rules set one"],
    capabilities: ["resident.read", "knowledge.read", "charge.prepare", "resident.message.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "The booking is recorded without overlap and confirmed to the resident, with any fee prepared for posting.", notDoneWhen: "A slot was offered but not recorded, or a fee was mentioned but not prepared." },
    forbidden: ["apply amenity rules differently between residents, including age-based limits the jurisdiction's familial-status rules bar", "confirm a booking that overlaps an existing one"],
    approvals: ["amenity fee or deposit before posting"],
    collaborators: ["property-operations.property-calendar", "property-operations.move-in-move-out-coordination"],
  },
  {
    id: "resident-experience.package-and-access-support",
    name: "Package & Access Support",
    domain: "resident-experience",
    boundary: "Handles one resident's package room or locker problems, fob and key replacement requests, guest access and routine daytime lockouts, and hands after-hours lockouts to the emergency procedure. Stops at the resident's own access; the property's key records are kept elsewhere.",
    notThis: { specialist: "property-operations.key-and-access-inventory", because: "Key & access inventory keeps the property's master record of keys and fobs; this resolves one resident's package or access problem against it." },
    triggers: ["locked out", "lost fob", "package missing", "locker code", "guest access", "replacement key"],
    inputs: ["resident request", "authorised occupants on the lease", "key and access records"],
    outputs: ["resolution or a replacement request for staff", "emergency handoff for after-hours lockouts"],
    capabilities: ["resident.read", "lease.read", "key_access.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The resident has access or their package, or a replacement or lockout task has an owner and a time the resident was told.", notDoneWhen: "The request was acknowledged but no task or owner exists." },
    forbidden: ["grant or change access for anyone the lease does not list as an authorised occupant", "confirm or deny to a caller whether a named person lives at the property"],
    approvals: [],
    collaborators: ["property-operations.key-and-access-inventory", "maintenance.emergency-maintenance-triage", "people-operations.on-call-schedule"],
  },
  {
    id: "resident-experience.renters-insurance-tracking",
    name: "Renters Insurance Tracking",
    domain: "resident-experience",
    boundary: "Keeps each lease's renters insurance requirement matched to current proof: policy dates, liability limit and the interested-party listing, with reminders before a lapse. Stops at status and reminders; a lapse is handed to compliance for any enforcement under the lease.",
    notThis: { specialist: "risk-compliance.renters-insurance-compliance", because: "Compliance owns the requirement and its enforcement across the portfolio; tracking keeps each resident's proof current and reminds them before it lapses." },
    triggers: ["renters insurance", "proof of insurance", "policy expiring", "insurance lapsed", "declarations page"],
    inputs: ["lease insurance requirement", "uploaded policy documents", "insurance records"],
    outputs: ["per-lease compliant, expiring or lapsed status", "reminder drafts", "lapse handoff to compliance"],
    capabilities: ["lease.read", "insurance.read", "document.extract", "resident.read", "resident.message.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Every lease in scope with a requirement has current proof on file or a recorded lapse handed to compliance.", notDoneWhen: "A reminder was sent but the lapse is not recorded or handed off." },
    forbidden: ["require an insurer, coverage amount or product the lease does not require", "enrol a resident in a master or force-placed policy or add its charge"],
    approvals: [],
    collaborators: ["risk-compliance.renters-insurance-compliance", "resident-experience.move-in-onboarding"],
  },
  {
    id: "resident-experience.resident-benefits-coordination",
    name: "Resident Benefits Coordination",
    domain: "resident-experience",
    boundary: "Explains and administers the property's resident benefits package as the lease addendum defines it: what is included, enrolment and opt-out where allowed, and handing service problems to the benefit's vendor. Stops at the addendum; it does not change the package or its fee.",
    notThis: { specialist: "resident-experience.resident-faq-and-policy", because: "FAQ & policy answers property rules; benefits coordination administers the specific services and fee in the benefits addendum." },
    triggers: ["resident benefits", "benefits package", "what am i paying for", "opt out of", "included services", "filter delivery"],
    inputs: ["benefits addendum", "resident charges", "benefit vendor contacts"],
    outputs: ["answer citing the addendum", "enrolment or opt-out request where the addendum allows", "vendor handoff for a service problem"],
    capabilities: ["lease.read", "charge.read", "resident.read", "knowledge.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The resident's question is answered from the addendum, or their enrolment change or vendor issue has an owner.", notDoneWhen: "A service complaint about a benefit was acknowledged but not passed to the vendor." },
    forbidden: ["present an optional benefit as mandatory, or a mandatory fee as optional, contrary to the addendum", "describe a benefit or fee the addendum does not disclose"],
    approvals: [],
    collaborators: ["receivables.rent-reporting-coordination", "lease-admin.lease-addendum-preparation", "resident-experience.payment-question-resolution"],
  },
  {
    id: "resident-experience.resident-complaint-resolution",
    name: "Resident Complaint Resolution",
    domain: "resident-experience",
    boundary: "Works a resident complaint (noise, a neighbour, a service failure, staff conduct) to an outcome: records it, checks it against the records, proposes a remedy and follows up. Allegations of discrimination, harassment, retaliation or safety go to risk and compliance, not this queue.",
    notThis: { specialist: "lease-admin.lease-violation-workflow", because: "The violation workflow enforces the lease against a resident; complaint resolution resolves the complainant's issue and hands a confirmed violation there." },
    triggers: ["complaint", "noise", "neighbor", "unhappy", "rude staff", "nothing gets fixed"],
    inputs: ["complaint and thread", "related work orders, notices and history", "workspace complaint SOP"],
    outputs: ["complaint record with findings", "proposed remedy", "follow-up with the resident and closing reason"],
    capabilities: ["communication.read", "resident.read", "lease.read", "work_order.read", "incident.prepare", "resident.message.prepare"],
    execution: "child_run",
    completion: { doneWhen: "The resident was told the outcome and either confirmed it or the case closed with a recorded reason after follow-up.", notDoneWhen: "An apology was sent but the cause has no action or owner." },
    forbidden: ["offer a rent credit, concession or fee waiver without approval", "handle an allegation of discrimination, harassment or retaliation as a routine service complaint"],
    approvals: ["any credit, concession or waiver offered as a remedy"],
    collaborators: ["risk-compliance.incident-intake", "lease-admin.lease-violation-workflow", "risk-compliance.fair-housing-guard", "maintenance.repeat-issue-analysis"],
  },
  {
    id: "resident-experience.accommodation-request-intake",
    name: "Accommodation Request Intake",
    domain: "resident-experience",
    boundary: "Recognises when a resident's message is a request for a reasonable accommodation or modification, whatever words are used, records it in the secure accommodation intake, acknowledges receipt and hands it to the accommodation workflow. Stops at secure intake; it never evaluates or decides.",
    notThis: { specialist: "risk-compliance.reasonable-accommodation-workflow", because: "Intake gets the request into the secure record on the day it arrives; the workflow reviews and decides it under policy and jurisdiction." },
    triggers: ["accommodation", "because of my disability", "grab bars", "accessible parking", "assistance animal", "need a ground floor"],
    inputs: ["resident message", "resident record"],
    outputs: ["secure intake record with the date received", "acknowledgement to the resident", "handoff to the accommodation workflow"],
    capabilities: ["communication.read", "resident.read", "accommodation.intake", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The request is in secure intake with its received date, acknowledged, and owned by the accommodation workflow.", notDoneWhen: "The request sits in a general thread or maintenance ticket rather than secure intake." },
    forbidden: ["ask for a diagnosis, medical records or the nature of a disability", "deny, discourage or delay a request, or require a particular form before accepting it"],
    approvals: [],
    collaborators: ["risk-compliance.reasonable-accommodation-workflow", "resident-experience.pet-and-animal-policy-support", "affordable.affordable-housing-accommodation-support"],
  },
  {
    id: "resident-experience.pet-and-animal-policy-support",
    name: "Pet & Animal Policy Support",
    domain: "resident-experience",
    boundary: "Answers pet policy questions (limits, fees, deposits, registration) and registers pets under the lease's pet addendum. Recognises an assistance animal request and routes it to accommodation intake, never treating it as a pet. Stops at pet policy.",
    notThis: { specialist: "resident-experience.accommodation-request-intake", because: "Pet support applies the pet policy; an assistance animal is not a pet, so its request goes to accommodation intake instead." },
    triggers: ["pet policy", "can i get a dog", "pet fee", "register my cat", "pet rent", "emotional support animal"],
    inputs: ["resident question", "pet addendum and property pet policy", "pet registrations"],
    outputs: ["answer citing the pet policy", "pet registration record", "handoff of an assistance animal request to accommodation intake"],
    capabilities: ["lease.read", "knowledge.read", "resident.read", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The resident's pet question is answered from the policy or the pet is registered, and any assistance animal request is in accommodation intake.", notDoneWhen: "An assistance animal was registered as a pet or charged pet fees." },
    forbidden: ["apply pet rent, pet deposit, breed, size or number limits to an assistance animal", "ask for certification or documentation of an assistance animal"],
    approvals: [],
    collaborators: ["resident-experience.accommodation-request-intake", "risk-compliance.reasonable-accommodation-workflow", "lease-admin.lease-addendum-preparation"],
  },
  {
    id: "resident-experience.resident-satisfaction-and-feedback",
    name: "Resident Satisfaction & Feedback",
    domain: "resident-experience",
    boundary: "Sends surveys at the workspace's defined moments (after move-in, after a work order, before renewal), themes the responses, routes each actionable negative response to an owner and reports trends. Stops at feedback; it does not score residents for renewal.",
    notThis: { specialist: "renewals.retention-risk", because: "Satisfaction & feedback collects and acts on what residents say; retention risk combines that with other signals to rank who may leave." },
    triggers: ["survey", "feedback", "nps", "satisfaction", "rating", "how are we doing"],
    inputs: ["survey moments and templates", "survey responses", "related work orders and threads"],
    outputs: ["themed results by property and moment", "owners assigned to actionable negative responses", "trend report"],
    capabilities: ["communication.read", "resident.read", "analytics.read", "report.prepare", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Responses in the period are themed and every actionable negative response has an owner.", notDoneWhen: "Surveys were sent or scores reported while negative responses remain unassigned." },
    forbidden: ["offer an incentive conditional on a positive rating or review", "post, edit or suppress public online reviews"],
    approvals: [],
    collaborators: ["renewals.retention-risk", "resident-experience.resident-complaint-resolution", "people-operations.process-improvement"],
  },
];
