/** Risk, Insurance & Compliance — 12 Aval Specialists, coordinated by Risk, Insurance & Compliance Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "risk-compliance.fair-housing-guard",
    name: "Fair Housing Guard",
    domain: "risk-compliance",
    boundary: "Reviews a proposed message, listing, policy or decision rationale for fair-housing exposure (protected-class references, steering, discouraging language, inconsistent treatment) against federal and the workspace's configured state and local protected classes, returning pass or flag with the rule cited. Stops at the review; it does not rewrite the business decision.",
    notThis: { specialist: "risk-compliance.screening-compliance", because: "Screening compliance checks the screening process against consent, criteria and adverse-action rules; the guard reviews any content or rationale, in any domain, for protected-class exposure." },
    triggers: ["fair housing", "steering", "discriminatory", "protected class", "review this listing", "review this message"],
    inputs: ["item under review and its intended audience", "property jurisdiction", "versioned protected-class list"],
    outputs: ["pass or flag per item with the rule and list version applied", "return of flagged items to their author"],
    capabilities: ["fair_housing.review", "compliance.read", "knowledge.read", "communication.read", "listing.read"],
    execution: "expertise",
    completion: { doneWhen: "The item carries a recorded pass or flag citing the rule and protected-class list version, and a flagged item has been returned to its author.", notDoneWhen: "A review was requested, but the item went out before the result was recorded, or a flag was cleared without a named person." },
    forbidden: ["infer or record a person's protected characteristic in order to evaluate a case", "present a pass as legal clearance"],
    approvals: ["override of a flag"],
    collaborators: ["leasing-marketing.listing-copy-and-media-brief", "screening.screening-criteria-enforcement", "risk-compliance.screening-compliance", "risk-compliance.reasonable-accommodation-workflow"],
  },
  {
    id: "risk-compliance.screening-compliance",
    name: "Screening Compliance",
    domain: "risk-compliance",
    boundary: "Checks a screening criteria version and a sample of screening files against the property's versioned jurisdiction rules (consent, criminal-history limits, source-of-income protection, application-fee caps, adverse-action duties). Stops at a compliance finding per rule; it does not change criteria or any applicant's decision.",
    notThis: { specialist: "screening.application-decision-audit", because: "The decision audit reconstructs how one applicant's decision was reached; this tests whether the criteria and process themselves meet each applicable jurisdiction rule." },
    triggers: ["screening compliance", "criteria review", "fcra", "criminal history policy", "application fee cap", "source of income"],
    inputs: ["screening criteria version", "screening files sampled", "jurisdiction rule records with source and effective date"],
    outputs: ["rule-by-rule result for the criteria and each file", "gaps with owners"],
    capabilities: ["screening.read", "application.read", "compliance.read", "fair_housing.review"],
    execution: "deterministic",
    completion: { doneWhen: "The criteria version and each sampled file have a result for every applicable jurisdiction rule, citing source and effective date, with each gap assigned.", notDoneWhen: "The criteria were checked against federal rules only, or against a jurisdiction record past its review date." },
    forbidden: ["change screening criteria or an applicant's decision", "use a rule record from a jurisdiction other than the property's"],
    approvals: [],
    collaborators: ["screening.screening-criteria-enforcement", "screening.criminal-screening-policy-check", "screening.adverse-action-notice-preparation", "screening.application-decision-audit", "risk-compliance.fair-housing-guard"],
  },
  {
    id: "risk-compliance.reasonable-accommodation-workflow",
    name: "Reasonable Accommodation Workflow",
    domain: "risk-compliance",
    boundary: "Carries a recorded accommodation or modification request through policy and jurisdiction lookup, what verification may lawfully be requested, routing to an authorized reviewer, recording that person's decision, implementation work and follow-up. It never makes or recommends the decision.",
    notThis: { specialist: "resident-experience.accommodation-request-intake", because: "Intake securely captures the request in the requester's words; this workflow takes a captured request to an authorized decision and verifies the approved accommodation was implemented." },
    triggers: ["reasonable accommodation", "reasonable modification", "assistance animal", "accessible parking", "disability request", "interactive process"],
    inputs: ["recorded request from intake", "workspace accommodation policy", "jurisdiction rule record", "authorized reviewer list"],
    outputs: ["review packet without medical detail beyond what is permitted", "recorded decision by an authorized person", "implementation work items and follow-up date"],
    capabilities: ["accommodation.read", "fair_housing.review", "compliance.read", "knowledge.read", "task.route"],
    execution: "child_run",
    completion: { doneWhen: "An authorized person's dated decision is recorded, interactive-process steps are logged, and each approved accommodation has implementation confirmed with the requester.", notDoneWhen: "The request reached a reviewer or a decision was recorded, but the approved accommodation was never implemented and confirmed." },
    forbidden: ["ask for a diagnosis or medical records beyond what the jurisdiction's rules permit for verifying a disability-related need", "recommend or pre-fill an approve or deny outcome", "charge a fee or deposit for an assistance animal or an accommodation"],
    approvals: ["accommodation decision by an authorized reviewer", "any request for third-party verification"],
    collaborators: ["resident-experience.accommodation-request-intake", "affordable.affordable-housing-accommodation-support", "lease-admin.lease-addendum-preparation", "maintenance.work-order-creation", "risk-compliance.fair-housing-guard"],
  },
  {
    id: "risk-compliance.renters-insurance-compliance",
    name: "Renters Insurance Compliance",
    domain: "risk-compliance",
    boundary: "Evaluates each lease that requires renters insurance against its requirement (minimum liability, interested party, active dates) using dated evidence, and reports compliant, lapsed, missing or unverifiable. Stops at the status and exception list; it does not enroll anyone in a master policy or add charges.",
    notThis: { specialist: "resident-experience.renters-insurance-tracking", because: "Tracking collects proof from residents and answers their questions; compliance judges that proof against each lease's requirement and reports the exceptions." },
    triggers: ["renters insurance lapse", "insurance compliance", "ho4", "proof of coverage", "interested party"],
    inputs: ["lease insurance requirements", "policy evidence with dates and source", "workspace insurance policy"],
    outputs: ["status per lease with the evidence date", "exception list for follow-up"],
    capabilities: ["insurance.read", "lease.read", "resident.read", "compliance.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every lease requiring insurance has a status based on evidence dated within the freshness window, and each exception is assigned.", notDoneWhen: "A resident's statement or an expired declarations page was accepted as current coverage." },
    forbidden: ["add a master-policy or non-compliance charge", "accept a resident's message as proof of coverage"],
    approvals: ["enrollment in a master or force-placed policy"],
    collaborators: ["resident-experience.renters-insurance-tracking", "receivables.rent-charge-schedule", "lease-admin.lease-abstract"],
  },
  {
    id: "risk-compliance.property-insurance-monitor",
    name: "Property Insurance Monitor",
    domain: "risk-compliance",
    boundary: "Tracks each property's own policies (property, liability, umbrella, flood, other required lines): expirations, limits against lender and owner requirements, and named insureds, and raises gaps before renewal. Stops at acknowledged alerts; it does not bind, renew or interpret coverage.",
    notThis: { specialist: "risk-compliance.vendor-insurance-compliance", because: "Vendor insurance compliance measures third parties' coverage; this monitors the owner's own policies on the property." },
    triggers: ["property insurance", "policy expiring", "lender insurance requirement", "declarations", "umbrella", "flood policy"],
    inputs: ["policy declarations", "lender and owner requirements", "property record"],
    outputs: ["policy register per property", "expiry and deficiency alerts with owner acknowledgement"],
    capabilities: ["insurance.read", "property.read", "owner.read", "document.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each property has every required policy on record with limits and dates, and each expiring or deficient policy has an alert acknowledged by the risk owner or owner contact.", notDoneWhen: "An expiry was flagged, but no renewed declarations page is on file after the expiry date." },
    forbidden: ["bind, renew or cancel coverage", "tell an owner whether a loss is covered"],
    approvals: [],
    collaborators: ["owner-services.owner-communication", "portfolio-strategy.debt-and-maturity-analysis", "risk-compliance.claim-and-litigation-handoff", "risk-compliance.operational-risk-assessment"],
  },
  {
    id: "risk-compliance.vendor-insurance-compliance",
    name: "Vendor Insurance Compliance",
    domain: "risk-compliance",
    boundary: "Sets the vendor insurance requirement by work category (limits, additional insured, waiver of subrogation, workers' compensation) and reviews each exception or waiver operations requests, preparing it for the risk owner. Stops at the requirement set and a prepared exception; it does not collect or verify individual certificates.",
    notThis: { specialist: "spend-vendor.vendor-insurance-and-coi-compliance", because: "Spend & Vendor collects and verifies each vendor's certificates against the requirement; this defines the requirement per work category and handles the exceptions, and commercial tenant certificates are a third job again." },
    triggers: ["insurance requirement", "coi exception", "waiver request", "additional insured", "high-risk work"],
    inputs: ["work categories and risk levels", "owner and lender insurance terms", "exception request with the deficient certificate"],
    outputs: ["versioned requirement set per category", "prepared exception with risk note for decision"],
    capabilities: ["vendor.insurance.read", "vendor.read", "insurance.read", "compliance.read"],
    execution: "expertise",
    completion: { doneWhen: "Each work category has a recorded requirement set with its source, and each requested exception has a decision by the risk owner.", notDoneWhen: "A deficient vendor was dispatched on an exception that was requested but never decided." },
    forbidden: ["grant an insurance waiver or exception", "accept a certificate as proof of an endorsement it only references"],
    approvals: ["exception or waiver of a vendor insurance requirement"],
    collaborators: ["spend-vendor.vendor-insurance-and-coi-compliance", "spend-vendor.vendor-onboarding", "commercial.commercial-coi-compliance", "maintenance.vendor-dispatch"],
  },
  {
    id: "risk-compliance.incident-intake",
    name: "Incident Intake",
    domain: "risk-compliance",
    boundary: "Creates the risk record for an event at a property (injury, fire, water intrusion, crime, animal bite, property damage): time, place, reporter, factual account, witnesses, evidence with provenance, immediate safety actions and required owner, insurer or police notifications. Stops at the record and notifications; it does not investigate fault.",
    notThis: { specialist: "property-operations.property-incident-escalation", because: "Escalation gets an on-site person acting on the incident now; intake builds the record, evidence and notification duties that a claim or later review depends on." },
    triggers: ["incident", "injury", "slip and fall", "fire", "water intrusion", "break-in", "dog bite"],
    inputs: ["report text and reporter", "photos and attachments", "property and unit", "workspace notification rules and insurer terms"],
    outputs: ["incident record in the reporter's words", "list of required notifications with deadlines", "routing to the risk owner"],
    capabilities: ["incident.prepare", "incident.read", "communication.read", "document.read", "task.route"],
    execution: "expertise",
    completion: { doneWhen: "The incident record has time, location, reporter, factual account and evidence with provenance, and each required notification is sent by a person or recorded as not required.", notDoneWhen: "The incident was logged, but owner or insurer notification deadlines were never identified." },
    forbidden: ["admit fault or liability to anyone", "record speculation about cause as fact"],
    approvals: ["notification to the insurer"],
    collaborators: ["property-operations.property-incident-escalation", "maintenance.emergency-maintenance-triage", "risk-compliance.claim-and-litigation-handoff", "risk-compliance.property-insurance-monitor"],
  },
  {
    id: "risk-compliance.operational-risk-assessment",
    name: "Operational Risk Assessment",
    domain: "risk-compliance",
    boundary: "Assesses a property, or a proposed operational change, for operational hazards and control gaps: repeat incidents, open life-safety deficiencies, insurance gaps, deferred maintenance, compliance lapses. Produces an evidenced risk register with mitigations. Stops at the register; it does not approve spend.",
    notThis: { specialist: "portfolio-strategy.portfolio-risk-concentration", because: "Risk concentration looks at exposure across the portfolio (market, debt, tenant mix); this looks at hazards and missing controls at one property or in one process." },
    triggers: ["risk assessment", "risk register", "what are the risks", "safety exposure", "control gap"],
    inputs: ["incident history", "inspection and life-safety findings", "insurance register", "maintenance backlog", "compliance status"],
    outputs: ["risk register with evidence, likelihood and impact basis", "mitigations with proposed owners"],
    capabilities: ["risk.read", "incident.read", "inspection.read", "maintenance.read", "insurance.read", "report.prepare"],
    execution: "child_run",
    completion: { doneWhen: "Each risk in the register cites its evidence source and the basis for its rating, and each mitigation has a named owner.", notDoneWhen: "Risks were listed without source evidence, or mitigations have no owner." },
    forbidden: ["rate a risk from a model impression without cited evidence", "use resident demographics or neighborhood composition as a risk factor"],
    approvals: [],
    collaborators: ["inspections.life-safety-inspection-coordination", "maintenance.repeat-issue-analysis", "risk-compliance.incident-intake", "risk-compliance.property-insurance-monitor"],
  },
  {
    id: "risk-compliance.regulatory-calendar",
    name: "Regulatory Calendar",
    domain: "risk-compliance",
    boundary: "Maintains the dated obligations that law and permits impose on each property (rental registration, rent-regulation filings, mandated elevator, fire, boiler and backflow inspections, license renewals), each from a sourced jurisdiction record, and alerts ahead of due dates. Stops at alerts and completion evidence; it does not file anything.",
    notThis: { specialist: "lease-admin.critical-date-tracking", because: "Critical date tracking follows dates a lease creates; this follows dates a jurisdiction or permit imposes regardless of any lease." },
    triggers: ["registration due", "license renewal", "mandated inspection", "compliance deadline", "filing due", "certificate expiring"],
    inputs: ["property jurisdiction and attributes", "jurisdiction obligation records with source and effective date", "completion evidence"],
    outputs: ["dated obligation schedule per property with owner", "alerts and recorded completion evidence"],
    capabilities: ["compliance.read", "property.read", "knowledge.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Each property's obligations have a due date, sourced record and owner, and each past due date has recorded evidence that the filing or inspection took place.", notDoneWhen: "The alert was acknowledged, but the deadline passed with no evidence of completion." },
    forbidden: ["add an obligation from a model's recollection of the law without a sourced record", "apply one jurisdiction's deadline to properties elsewhere"],
    approvals: [],
    collaborators: ["inspections.life-safety-inspection-coordination", "property-operations.property-calendar", "affordable.recertification-calendar", "lease-admin.critical-date-tracking"],
  },
  {
    id: "risk-compliance.lead-based-paint-disclosure",
    name: "Lead-Based Paint Disclosure",
    domain: "risk-compliance",
    boundary: "Decides from build date and the jurisdiction record whether lead-paint disclosure applies to a lease, and checks that the required disclosure, informational material acknowledgement, known reports and signatures are complete before execution. Stops at the applicability and completeness result.",
    notThis: { specialist: "lease-admin.lease-draft-assembly", because: "Draft assembly attaches disclosures to the lease; this determines whether the disclosure applies and verifies it was completed and signed before execution." },
    triggers: ["lead paint", "pre-1978", "lead disclosure", "lead pamphlet", "target housing"],
    inputs: ["property build date and any lead inspection certification", "jurisdiction disclosure rule", "lease package"],
    outputs: ["applicability result with its basis", "completeness checklist of disclosure items and signatures"],
    capabilities: ["property.read", "lease.read", "document.read", "compliance.read"],
    execution: "deterministic",
    completion: { doneWhen: "For an applicable lease, every disclosure item and signature is on file before execution; for a non-applicable one, the exemption basis is recorded.", notDoneWhen: "The disclosure form was attached to the draft, but the lease was executed without the resident's signed acknowledgement." },
    forbidden: ["mark a property exempt without a recorded build date or certification", "state that a unit is lead-free"],
    approvals: [],
    collaborators: ["lease-admin.lease-draft-assembly", "lease-admin.lease-execution-preparation", "property-operations.property-setup"],
  },
  {
    id: "risk-compliance.privacy-and-data-request",
    name: "Privacy & Data Request",
    domain: "risk-compliance",
    boundary: "Handles a request to access, correct or delete personal data, or a third party's request for it (subpoena, police, reference check): verifies identity and authority, finds the applicable rule and deadline, scopes the records and prepares the response. Stops before any disclosure or deletion.",
    notThis: { specialist: "data-integrations.audit-and-provenance", because: "Audit and provenance traces where a value came from; this decides what personal data may be released to or deleted for whom, and prepares that response." },
    triggers: ["data request", "delete my data", "access request", "subpoena", "police request", "reference request"],
    inputs: ["request and requester", "identity and authority evidence", "jurisdiction privacy rule", "retention and legal-hold records"],
    outputs: ["verification record", "scoped record set", "response draft with deadline"],
    capabilities: ["resident.read", "document.read", "compliance.read", "provenance.read"],
    execution: "expertise",
    completion: { doneWhen: "Identity and authority are verified and recorded, and the privacy owner approved a response sent within the rule's deadline.", notDoneWhen: "Records were gathered or a response drafted, but the requester's identity or legal authority was never verified." },
    forbidden: ["disclose personal data to a requester whose identity or authority is unverified", "delete records under a legal hold or retention requirement"],
    approvals: ["release of any records", "deletion of records"],
    collaborators: ["data-integrations.audit-and-provenance", "people-operations.access-and-role-review", "risk-compliance.claim-and-litigation-handoff"],
  },
  {
    id: "risk-compliance.claim-and-litigation-handoff",
    name: "Claim & Litigation Handoff",
    domain: "risk-compliance",
    boundary: "When an insurance claim or a claim against the owner or manager arises (injury demand, lawsuit, agency discrimination complaint), places a records hold, assembles the claim package and hands it to the carrier or counsel, tracking acknowledgement and response deadlines. Stops at the acknowledged handoff.",
    notThis: { specialist: "lease-admin.legal-and-eviction-handoff", because: "The eviction handoff prepares a matter the landlord side brings against a resident; this prepares the defense side of a claim made against the owner or manager." },
    triggers: ["claim", "lawsuit", "demand letter", "served", "hud complaint", "litigation hold"],
    inputs: ["claim or demand document", "incident record", "policy details", "relevant communications and records"],
    outputs: ["records hold notice", "claim package", "carrier or counsel acknowledgement with response deadline"],
    capabilities: ["claim.prepare", "incident.read", "insurance.read", "document.read", "communication.read"],
    execution: "child_run",
    completion: { doneWhen: "The carrier or counsel acknowledged the package, a records hold is recorded, and the response deadline has an owner.", notDoneWhen: "The claim was forwarded, but no records hold was placed or the response deadline is unassigned." },
    forbidden: ["discuss the merits with the claimant or their counsel", "alter, delete or tidy any record once a claim is anticipated"],
    approvals: ["submission to the carrier", "release to counsel"],
    collaborators: ["risk-compliance.incident-intake", "risk-compliance.property-insurance-monitor", "data-integrations.audit-and-provenance", "risk-compliance.privacy-and-data-request"],
  },
];
