/** Screening & Applicant Decisions — 12 Aval Specialists, coordinated by Screening & Applicant Decisions Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "screening.application-completeness",
    name: "Application Completeness",
    domain: "screening",
    boundary: "Checks a submitted application against the property's required fields, documents, signatures, screening consent and fees, and lists anything missing or unreadable. Stops before any verification or screening; it judges presence, not what the contents show.",
    notThis: { specialist: "screening.screening-criteria-enforcement", because: "Completeness asks whether everything required is present; criteria enforcement asks whether what is present meets the approved criteria." },
    triggers: ["application submitted", "missing documents", "incomplete application", "is the application complete", "consent missing"],
    inputs: ["submitted application and uploaded documents", "property application requirements", "consent and fee records"],
    outputs: ["complete, or the named missing and unreadable items", "missing-items request to the applicant"],
    capabilities: ["application.read", "document.read", "prospect.message.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "The application is marked complete with every requirement checked, or the applicant has been sent the specific missing items.", notDoneWhen: "The application was marked complete because its fields are filled while a required document is missing or unreadable." },
    forbidden: ["require a document or field that is not in the property's application requirements", "let screening start before the applicant's screening consent is on file"],
    approvals: [],
    collaborators: ["leasing-marketing.application-handoff", "screening.identity-verification", "screening.credit-screening-coordination"],
  },
  {
    id: "screening.identity-verification",
    name: "Identity Verification",
    domain: "screening",
    boundary: "Confirms the applicant is the person named on the application by comparing the identity document and the approved provider's identity check with the application data, and records a verified or unverified result with the mismatch. Stops at identity; it does not assess documents for fraud.",
    notThis: { specialist: "screening.application-fraud-detection", because: "Identity verification confirms who the applicant is; fraud detection looks for manipulated documents and suspicious patterns across the whole application." },
    triggers: ["verify identity", "id check", "driver's license", "identity mismatch", "id document"],
    inputs: ["application identity fields", "identity document", "provider identity check result"],
    outputs: ["verified or unverified result", "each field compared and any mismatch with its source"],
    capabilities: ["application.read", "document.read", "document.extract", "screening.read", "screening.request"],
    execution: "expertise",
    completion: { doneWhen: "The application carries a verified or unverified identity result with the provider check reference and every compared field.", notDoneWhen: "An ID was uploaded and looked at but no provider check or field comparison is recorded." },
    forbidden: ["ask about or record citizenship or immigration status beyond what the workspace's jurisdiction-reviewed criteria require", "treat a transliteration or name-order difference as a mismatch without a provider check"],
    approvals: [],
    collaborators: ["screening.application-fraud-detection", "screening.application-completeness", "risk-compliance.screening-compliance"],
  },
  {
    id: "screening.income-verification",
    name: "Income Verification",
    domain: "screening",
    boundary: "Calculates verified monthly income from extracted document figures (pay stubs, offer letters, benefit and support letters, bank statements) using the workspace's written income method, and compares it with the property's income requirement. Stops at the figure and ratio; employer contact is a sibling's job.",
    notThis: { specialist: "screening.employment-verification", because: "Income verification computes how much the applicant receives from all lawful sources; employment verification confirms a job exists with the stated employer." },
    triggers: ["verify income", "pay stubs", "income ratio", "rent to income", "benefit letter", "voucher amount"],
    inputs: ["extracted income documents", "workspace income calculation method", "property income requirement", "voucher or subsidy amount where applicable"],
    outputs: ["verified monthly income by source with the document behind each", "income-to-rent comparison against the requirement"],
    capabilities: ["application.read", "document.read", "document.extract", "screening.read", "knowledge.read"],
    execution: "deterministic",
    completion: { doneWhen: "Each income source is traced to a document, the total follows the written method, and the ratio result is recorded.", notDoneWhen: "An income figure was stated or estimated without the documents and method that produce it." },
    forbidden: ["exclude or discount a lawful source of income (vouchers, benefits, support) that the jurisdiction or workspace policy counts", "calculate the ratio on the full rent where the policy applies it to the tenant's portion of a subsidised rent"],
    approvals: [],
    collaborators: ["screening.employment-verification", "screening.screening-criteria-enforcement", "screening.application-fraud-detection", "affordable.voucher-and-pha-coordination"],
  },
  {
    id: "screening.employment-verification",
    name: "Employment Verification",
    domain: "screening",
    boundary: "Confirms the stated employer, position and start date through the approved provider or an employer contact found independently of the applicant's documents, and records the result. Stops at employment facts; income amounts belong to income verification.",
    notThis: { specialist: "screening.income-verification", because: "Employment verification confirms the job exists as stated; income verification calculates what the applicant earns from it and any other source." },
    triggers: ["verify employment", "employer verification", "call employer", "voe", "offer letter", "new job"],
    inputs: ["stated employer and position", "applicant's verification consent", "provider employment result or independently sourced employer contact"],
    outputs: ["confirmed, unconfirmed or unreachable employment result", "source and date of the confirmation"],
    capabilities: ["application.read", "screening.read", "screening.request", "communication.read"],
    execution: "expertise",
    completion: { doneWhen: "Employment is recorded as confirmed or unconfirmed with the provider reference or the independently sourced contact used.", notDoneWhen: "A verification request was sent but no answer is recorded, or confirmation came from a contact taken only from the applicant's documents." },
    forbidden: ["disclose anything to an employer beyond what the applicant's consent covers, such as the screening outcome", "treat a contact taken only from the applicant's own documents as independent confirmation"],
    approvals: [],
    collaborators: ["screening.income-verification", "screening.application-fraud-detection"],
  },
  {
    id: "screening.application-fraud-detection",
    name: "Application Fraud Detection",
    domain: "screening",
    boundary: "Examines application documents for specific signs of manipulation (edited metadata, arithmetic that does not add up on a pay stub, employer details that do not exist) and documents reused across the workspace's applications, and flags each with its evidence for human review. Stops at flags; it never denies.",
    notThis: { specialist: "screening.identity-verification", because: "Fraud detection tests whether documents are genuine; identity verification tests whether the applicant is the named person." },
    triggers: ["fake pay stub", "edited document", "suspicious application", "fraud check", "document doesn't add up"],
    inputs: ["application documents and extracted fields", "document metadata", "prior applications in the workspace"],
    outputs: ["flags, each citing the document, the field and the inconsistency", "no-flag result where none are found"],
    capabilities: ["application.read", "document.read", "document.extract", "screening.read", "application.review.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Every flag cites a specific document inconsistency and a person has reviewed each one.", notDoneWhen: "A fraud score or impression was produced, or flags exist that no reviewer has seen." },
    forbidden: ["raise a flag without a specific, recorded document or data inconsistency", "treat a name, address, language or country of issue as a fraud signal"],
    approvals: ["referral of a flagged application for human fraud review"],
    collaborators: ["screening.identity-verification", "screening.income-verification", "screening.employment-verification"],
  },
  {
    id: "screening.credit-screening-coordination",
    name: "Credit Screening Coordination",
    domain: "screening",
    boundary: "Orders the consumer credit report through the workspace's approved provider once consent is on file, retrieves it, preserves it with the provider's identity, and extracts the items the criteria use. Stops before applying criteria; the report is evidence, not a decision.",
    notThis: { specialist: "screening.screening-criteria-enforcement", because: "Credit coordination obtains and preserves the provider's report; criteria enforcement applies the approved criteria to it." },
    triggers: ["run credit", "order screening report", "credit report", "screening provider", "report not back"],
    inputs: ["complete application with screening consent", "approved screening provider", "criteria items to extract"],
    outputs: ["provider report attached with provider name, date and reference", "extracted criteria-relevant items linked to the report"],
    capabilities: ["application.read", "screening.request", "screening.read", "document.read"],
    execution: "deterministic",
    completion: { doneWhen: "The provider's report is attached to the application with its provider, date and reference, and the extracted items link back to it.", notDoneWhen: "The order was placed but the report is not back, or it came back but is not attached to the application." },
    forbidden: ["order a report without recorded applicant consent or through a provider the workspace has not approved", "alter, summarise away or discard any part of the provider's report"],
    approvals: [],
    collaborators: ["screening.screening-criteria-enforcement", "screening.application-completeness", "screening.adverse-action-notice-preparation"],
  },
  {
    id: "screening.rental-history-verification",
    name: "Rental History Verification",
    domain: "screening",
    boundary: "Verifies prior tenancies with landlords found independently of the application (dates, rent, notice given, balance owed) and reads any rental-history record the provider returns. Stops at tenancy facts with sources; weighing them against criteria is a sibling's job.",
    notThis: { specialist: "screening.credit-screening-coordination", because: "Credit coordination obtains a consumer report; rental history verification confirms tenancy performance with the prior landlords themselves." },
    triggers: ["landlord reference", "rental history", "prior landlord", "verify tenancy", "eviction record"],
    inputs: ["stated rental history", "provider rental-history record", "independently sourced landlord contacts"],
    outputs: ["per-tenancy result: dates, rent, notice, balance, source", "record items the jurisdiction's rules exclude from consideration, marked as excluded"],
    capabilities: ["application.read", "screening.read", "screening.request", "communication.read", "document.read"],
    execution: "expertise",
    completion: { doneWhen: "Each stated tenancy in the lookback window has a verified result or a recorded unreachable result with the attempts made.", notDoneWhen: "Landlords were contacted but responses are unrecorded, or an eviction filing is listed without its outcome." },
    forbidden: ["count an eviction filing that was dismissed, sealed or resolved for the tenant, or any record the jurisdiction's rules bar from consideration", "ask a prior landlord about the applicant's household, health or anything outside tenancy performance"],
    approvals: [],
    collaborators: ["screening.screening-criteria-enforcement", "screening.application-fraud-detection", "risk-compliance.screening-compliance"],
  },
  {
    id: "screening.criminal-screening-policy-check",
    name: "Criminal Screening Policy Check",
    domain: "screening",
    boundary: "Checks any use of criminal history against the workspace's written policy and the jurisdiction rules on record for the property: whether it may be considered, at what stage, over what lookback, and whether an individualised assessment is required. Stops at what may be considered; it does not assess the applicant.",
    notThis: { specialist: "screening.screening-criteria-enforcement", because: "This decides which criminal records may lawfully be considered and how; criteria enforcement then applies the permitted criteria to the application." },
    triggers: ["criminal background", "fair chance", "conviction", "lookback", "individualized assessment", "background check"],
    inputs: ["provider criminal-history results", "workspace criminal screening policy", "jurisdiction rules with source and effective date"],
    outputs: ["records permitted and excluded, each with the rule applied", "whether an individualised assessment is required and at what stage"],
    capabilities: ["screening.read", "application.read", "compliance.read", "knowledge.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every returned record is marked permitted or excluded under a cited policy and jurisdiction rule version.", notDoneWhen: "Records were reviewed without a cited rule, or an assessment the rules require is not queued for a person." },
    forbidden: ["consider an arrest without conviction or a record outside the applicable lookback period", "apply a blanket criminal-history exclusion", "consider criminal history before the stage the jurisdiction rule on record allows"],
    approvals: ["individualised assessment outcome"],
    collaborators: ["risk-compliance.screening-compliance", "screening.screening-criteria-enforcement", "screening.adverse-action-notice-preparation"],
  },
  {
    id: "screening.screening-criteria-enforcement",
    name: "Screening Criteria Enforcement",
    domain: "screening",
    boundary: "Applies the property's approved, versioned written criteria to verified application data and records met, not met or needs review for each criterion, with the source item. Produces a decision recommendation for an authorised person; it never makes the decision.",
    notThis: { specialist: "screening.conditional-approval-preparation", because: "Criteria enforcement produces the per-criterion result; conditional approval prepares the terms a person may offer when the criteria allow conditions." },
    triggers: ["apply criteria", "does the applicant qualify", "screening result", "meets criteria", "decision recommendation"],
    inputs: ["verified identity, income, employment, credit, rental and permitted criminal results", "approved criteria version for the property"],
    outputs: ["per-criterion result traced to its source item", "recommended outcome with the criteria version, queued for a person"],
    capabilities: ["application.read", "screening.read", "compliance.read", "knowledge.read", "screening.decision.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Every criterion has a result traced to a source item and criteria version, and the recommendation is in an authorised person's decision queue.", notDoneWhen: "The report was reviewed and summarised as acceptable without a per-criterion result." },
    forbidden: ["apply a criterion that is not in the approved criteria version for the property", "apply different thresholds or exceptions to applicants with the same results"],
    approvals: ["the eligibility decision"],
    collaborators: ["screening.conditional-approval-preparation", "screening.adverse-action-notice-preparation", "screening.criminal-screening-policy-check", "risk-compliance.screening-compliance"],
  },
  {
    id: "screening.conditional-approval-preparation",
    name: "Conditional Approval Preparation",
    domain: "screening",
    boundary: "Where the approved criteria allow a conditional approval, prepares the conditions from the workspace's conditions table (guarantor, co-signer, lawful additional deposit) and the applicant notice, and tracks the applicant's answer. Stops at terms a person approves.",
    notThis: { specialist: "screening.adverse-action-notice-preparation", because: "This prepares the conditions offered; a condition based on a consumer report is also adverse action, whose notice content that specialist prepares." },
    triggers: ["conditional approval", "guarantor", "co-signer", "additional deposit", "approve with conditions"],
    inputs: ["per-criterion results", "workspace conditions table", "jurisdiction deposit limits on record"],
    outputs: ["prepared conditions citing the table row", "applicant notice draft", "applicant's acceptance or decline"],
    capabilities: ["screening.read", "screening.decision.prepare", "adverse_action.prepare", "deposit.read", "compliance.read", "prospect.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "A person approved the conditions, the applicant was notified, and the applicant's acceptance or decline is recorded.", notDoneWhen: "Conditions were prepared but not approved, or sent without a recorded answer from the applicant." },
    forbidden: ["set a deposit or condition above the jurisdiction's limit or outside the workspace's conditions table", "offer conditions that differ from those offered to other applicants with the same results"],
    approvals: ["conditional approval terms", "applicant notice"],
    collaborators: ["screening.screening-criteria-enforcement", "screening.adverse-action-notice-preparation", "lease-admin.security-deposit-terms-review"],
  },
  {
    id: "screening.adverse-action-notice-preparation",
    name: "Adverse Action Notice Preparation",
    domain: "screening",
    boundary: "Assembles the adverse action notice after an authorised denial or conditional decision: the provider's exact reasons, the provider's name and contact details, that the provider did not decide, the free-report and dispute rights, and any jurisdiction-required content. Stops at an approved notice and its delivery record.",
    notThis: { specialist: "screening.conditional-approval-preparation", because: "This prepares the legally required notice content for a decision already made; conditional approval prepares the conditions themselves." },
    triggers: ["adverse action", "denial letter", "applicant denied", "fcra notice", "decline notice"],
    inputs: ["authorised decision record", "provider report, reasons and contact details", "jurisdiction notice requirements on record"],
    outputs: ["notice with each required element", "delivery record once sent"],
    capabilities: ["application.read", "screening.read", "adverse_action.prepare", "compliance.read"],
    execution: "deterministic",
    completion: { doneWhen: "A notice containing every required element was approved by a person and a delivery record exists.", notDoneWhen: "The notice was drafted but not approved, or approved but not delivered." },
    forbidden: ["paraphrase the provider's reasons or add reasons that are not in the recorded decision", "prepare a notice for delivery before an authorised person has made the decision it reports"],
    approvals: ["adverse action notice before delivery"],
    collaborators: ["screening.screening-criteria-enforcement", "risk-compliance.screening-compliance", "screening.application-decision-audit"],
  },
  {
    id: "screening.application-decision-audit",
    name: "Application Decision Audit",
    domain: "screening",
    boundary: "Reviews decided applications for traceability and consistency: criteria version applied, evidence per criterion, who decided and when, notice sent on time, and whether applicants with the same results got the same outcome. Stops at findings for the policy owner; it never reopens a decision.",
    notThis: { specialist: "risk-compliance.screening-compliance", because: "Screening compliance keeps the criteria and process lawful; the decision audit checks that individual decisions followed them." },
    triggers: ["audit decisions", "screening audit", "decision consistency", "who approved", "missing notice"],
    inputs: ["decided applications in the period", "criteria versions", "decision and notice records"],
    outputs: ["per-decision pass or exception with the missing item", "consistency exceptions across same-result applicants"],
    capabilities: ["application.read", "screening.read", "compliance.read", "provenance.read", "report.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Every decision in scope is checked and each exception has an owner assigned.", notDoneWhen: "An audit report was produced but its exceptions have no owner." },
    forbidden: ["change or reopen a decision", "infer applicants' protected characteristics from names, addresses or photos to test outcomes"],
    approvals: [],
    collaborators: ["risk-compliance.screening-compliance", "screening.adverse-action-notice-preparation", "data-integrations.audit-and-provenance"],
  },
];
