/** Spend & Vendor Operations — 14 Aval Specialists, coordinated by Spend & Vendor Operations Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "spend-vendor.vendor-onboarding",
    name: "Vendor Onboarding",
    domain: "spend-vendor",
    boundary: "Takes a new vendor from request to an approved vendor record: legal name, trades, service area, agreement, tax form, insurance certificate and remittance details, each collected and checked by its owner. Stops when the record is complete and awaiting approval; it does not approve the vendor.",
    notThis: { specialist: "spend-vendor.vendor-search", because: "Vendor search finds candidate vendors for a need; onboarding turns one chosen candidate into a complete, approvable vendor record." },
    triggers: ["new vendor", "onboard vendor", "add a contractor", "vendor setup", "vendor packet"],
    inputs: ["vendor name and contact", "workspace onboarding requirements by trade", "agreement template"],
    outputs: ["vendor record with each required item marked received or missing", "document requests sent to the vendor", "record submitted for approval"],
    capabilities: ["vendor.read", "vendor.prepare", "document.read", "communication.send"],
    execution: "child_run",
    completion: { doneWhen: "Every required onboarding item is received and checked, and the vendor record is with an approver.", notDoneWhen: "The vendor was added to the list while its tax form or insurance certificate was still missing." },
    forbidden: ["accept remittance or bank details from an email without out-of-band verification", "mark a vendor as approved"],
    approvals: ["adding the vendor to the approved list"],
    collaborators: ["spend-vendor.w-9-and-tax-information", "spend-vendor.vendor-insurance-and-coi-compliance", "spend-vendor.vendor-search"],
  },
  {
    id: "spend-vendor.vendor-insurance-and-coi-compliance",
    name: "Vendor Insurance & COI Compliance",
    domain: "spend-vendor",
    boundary: "Reads each vendor's certificate of insurance against the workspace's requirements for the vendor's trade: coverage types, limits, additional insured wording and expiry, and sets the vendor's insurance status. Stops at the status and requests for a corrected certificate; it does not dispatch or pay.",
    notThis: { specialist: "risk-compliance.vendor-insurance-compliance", because: "The risk specialist sets and audits the insurance policy across the portfolio; this one applies it to a vendor's certificate so dispatch and payment can rely on the status." },
    triggers: ["coi", "certificate of insurance", "vendor insurance", "insurance expired", "additional insured", "general liability"],
    inputs: ["vendor certificate of insurance", "insurance requirements by trade and property", "vendor record"],
    outputs: ["vendor insurance status with expiry date", "list of shortfalls against the requirement", "request for a corrected or renewed certificate"],
    capabilities: ["vendor.read", "vendor.insurance.read", "insurance.read", "document.read", "document.extract", "vendor.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The vendor record carries a current insurance status, expiry date and any shortfalls, drawn from the certificate on file.", notDoneWhen: "A certificate was received and filed without its limits and additional insured wording checked against the requirement." },
    forbidden: ["mark insurance compliant from a certificate that lists a different insured entity", "treat an expired certificate as compliant while a renewal is promised"],
    approvals: ["exceptions to the insurance requirement for a specific vendor"],
    collaborators: ["risk-compliance.vendor-insurance-compliance", "maintenance.vendor-dispatch", "spend-vendor.contract-expiration-monitor"],
  },
  {
    id: "spend-vendor.w-9-and-tax-information",
    name: "W-9 & Tax Information",
    domain: "spend-vendor",
    boundary: "Checks that each vendor's tax form is on file and complete: legal name matching the vendor record, entity type, taxpayer identification number format and signature, and flags vendors paid without one. Stops at the completeness result; 1099 reporting is finance's work.",
    notThis: { specialist: "finance.1099-and-vendor-tax-data", because: "Finance's 1099 specialist prepares year-end tax reporting from payments; this makes sure the tax form behind each vendor is complete before payments start." },
    triggers: ["w-9", "w9", "tin", "tax id", "vendor tax form", "backup withholding"],
    inputs: ["vendor record", "tax form on file", "payments made to the vendor"],
    outputs: ["tax-form completeness result per vendor", "list of vendors paid or pending payment without a complete form"],
    capabilities: ["vendor.read", "document.read", "document.extract", "bill.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every active vendor has a pass or fail tax-form check and each failure is on the request list.", notDoneWhen: "A tax form was uploaded and marked received without its name matching the vendor record." },
    forbidden: ["copy a full taxpayer identification number into a message, note or log", "change a vendor's legal name to match a form without recording the source"],
    approvals: [],
    collaborators: ["spend-vendor.vendor-onboarding", "finance.1099-and-vendor-tax-data", "spend-vendor.payment-preparation"],
  },
  {
    id: "spend-vendor.vendor-search",
    name: "Vendor Search",
    domain: "spend-vendor",
    boundary: "Finds candidate vendors for a trade and property from the approved list first, then from outside sources when the approved list cannot cover the need, with compliance status shown for each. Stops at a shortlist; it does not solicit bids or onboard.",
    notThis: { specialist: "spend-vendor.bid-solicitation", because: "Search produces the shortlist of who could do the work; bid solicitation asks those vendors for priced proposals." },
    triggers: ["find a vendor", "need a contractor", "who services", "no vendor for", "vendor options"],
    inputs: ["trade and scope", "property location", "approved vendor list with insurance status", "vendor performance history"],
    outputs: ["shortlist of candidate vendors with compliance and performance notes", "flag when only non-approved vendors fit"],
    capabilities: ["vendor.read", "vendor.insurance.read", "property.read", "market.public.read"],
    execution: "expertise",
    completion: { doneWhen: "A shortlist exists with each vendor's approval and insurance status stated, and it has been passed back to the requester.", notDoneWhen: "A list of names was returned without saying which are approved and insured." },
    forbidden: ["present an outside vendor as approved", "rank vendors on anything other than fit, compliance, performance and price"],
    approvals: [],
    collaborators: ["spend-vendor.vendor-onboarding", "spend-vendor.vendor-performance", "spend-vendor.bid-solicitation"],
  },
  {
    id: "spend-vendor.bid-solicitation",
    name: "Bid Solicitation",
    domain: "spend-vendor",
    boundary: "Issues a written scope and request for bid to the shortlisted vendors, answers their questions from the scope, and collects bids by the deadline. Stops at a closed bid set with every vendor's response or decline recorded; it does not compare or choose.",
    notThis: { specialist: "spend-vendor.bid-comparison", because: "Solicitation gets comparable bids in on the same scope and deadline; comparison evaluates them once the set is closed." },
    triggers: ["request for bid", "rfp", "get bids", "three quotes", "bid out", "scope of work"],
    inputs: ["scope of work", "shortlisted vendors", "bid deadline and site-visit arrangements"],
    outputs: ["request for bid sent to each vendor", "bid log with each response, decline or no-response", "closed bid set"],
    capabilities: ["vendor.read", "document.read", "communication.read", "communication.send"],
    execution: "child_run",
    completion: { doneWhen: "The deadline has passed and every invited vendor has a recorded bid, decline or no-response.", notDoneWhen: "Requests were sent but the bid set was never closed, or a late bid was added without recording it." },
    forbidden: ["share one vendor's bid or pricing with another vendor", "change the scope for one bidder without reissuing it to all"],
    approvals: ["the scope of work before it is issued"],
    collaborators: ["spend-vendor.vendor-search", "spend-vendor.bid-comparison", "maintenance.repair-quote-comparison"],
  },
  {
    id: "spend-vendor.bid-comparison",
    name: "Bid Comparison",
    domain: "spend-vendor",
    boundary: "Normalizes a closed bid set to the issued scope, lists inclusions, exclusions, allowances, schedule, warranty and price for each, and states a recommendation with the reason. Stops at the comparison; award and spend approval are for the approver.",
    notThis: { specialist: "maintenance.repair-quote-comparison", because: "Repair quote comparison handles quotes for a single work order; bid comparison evaluates formal bids against an issued scope for projects and contracts." },
    triggers: ["compare bids", "bid leveling", "which bid", "bid tab", "award"],
    inputs: ["closed bid set", "issued scope of work", "vendor compliance and performance"],
    outputs: ["bid tab normalized to the scope", "recommendation with the reason and scope gaps"],
    capabilities: ["vendor.read", "vendor.insurance.read", "document.read", "document.extract", "budget.read"],
    execution: "expertise",
    completion: { doneWhen: "Every bid is levelled to the same scope with gaps listed and a recommendation recorded for the approver.", notDoneWhen: "The lowest total was recommended without levelling exclusions and allowances." },
    forbidden: ["award a bid", "recommend a vendor whose insurance does not meet the requirement"],
    approvals: ["the award"],
    collaborators: ["spend-vendor.bid-solicitation", "spend-vendor.approval-routing", "spend-vendor.purchase-order-preparation"],
  },
  {
    id: "spend-vendor.purchase-order-preparation",
    name: "Purchase Order Preparation",
    domain: "spend-vendor",
    boundary: "Drafts the purchase order for approved or to-be-approved spend: vendor, property, scope or items, amount, GL coding and not-to-exceed terms, linked to its work order or bid. Stops at a draft PO in the approval path; it does not issue the PO to the vendor before approval.",
    notThis: { specialist: "maintenance.parts-and-materials-coordination", because: "Parts coordination decides which parts a repair needs; purchase order preparation writes the spend commitment for any purchase, parts or services." },
    triggers: ["purchase order", "po", "not to exceed", "commit spend", "order materials"],
    inputs: ["approved quote, bid or parts request", "vendor record", "property and budget line"],
    outputs: ["draft purchase order linked to its source", "budget line and coding on the PO"],
    capabilities: ["vendor.read", "budget.read", "gl.read", "purchase_order.prepare"],
    execution: "expertise",
    completion: { doneWhen: "A draft PO linked to its quote or work order is in the approval path with amount, vendor and coding set.", notDoneWhen: "A PO was drafted but never routed, or was sent to the vendor before approval." },
    forbidden: ["issue a PO to a vendor before it is approved", "split one purchase into several POs to stay under a threshold"],
    approvals: ["the purchase order"],
    collaborators: ["spend-vendor.approval-routing", "spend-vendor.bill-coding", "maintenance.spend-approval-preparation"],
  },
  {
    id: "spend-vendor.invoice-intake",
    name: "Invoice Intake",
    domain: "spend-vendor",
    boundary: "Captures a vendor invoice from email or upload: extracts vendor, invoice number, date, property, lines, tax and total, validates the vendor against the vendor record, and checks for duplicates. Stops at a clean invoice record queued for matching; it does not code or approve.",
    notThis: { specialist: "spend-vendor.invoice-work-order-matching", because: "Intake turns the document into a validated invoice record; matching then ties that record to the work order, PO and quote it bills for." },
    triggers: ["invoice", "bill from vendor", "ap inbox", "invoice attached", "statement from vendor"],
    inputs: ["invoice document", "vendor record", "prior invoices from the vendor"],
    outputs: ["invoice record with extracted fields", "vendor validation and duplicate-check results"],
    capabilities: ["document.read", "document.extract", "vendor.read", "invoice.read", "invoice.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The invoice record has every required field, a validated vendor and a duplicate-check result, and is queued for matching.", notDoneWhen: "Fields were extracted but the vendor was not validated or the duplicate check did not run." },
    forbidden: ["enter an invoice whose number and amount duplicate one already recorded for the vendor without flagging it", "accept changed remittance details printed on an invoice"],
    approvals: [],
    collaborators: ["spend-vendor.invoice-work-order-matching", "data-integrations.document-ingestion", "finance.financial-anomaly-detection"],
  },
  {
    id: "spend-vendor.invoice-work-order-matching",
    name: "Invoice/Work Order Matching",
    domain: "spend-vendor",
    boundary: "Matches an invoice to its work order, purchase order and approved quote, checks that the work is verified complete and the billed amount is within the approved amount, and records any variance. Stops at a match result; it does not approve or code the invoice.",
    notThis: { specialist: "spend-vendor.invoice-intake", because: "Intake validates the invoice as a document; matching checks it against the work, the PO and the quote it claims to bill." },
    triggers: ["match invoice", "three-way match", "invoice vs quote", "over the quote", "which work order"],
    inputs: ["invoice record", "work orders and their verification status", "purchase orders and approved quotes"],
    outputs: ["match result linking invoice to work order and PO", "variance against the approved amount", "hold reason when work is not verified"],
    capabilities: ["invoice.read", "work_order.read", "vendor.read", "bill.read"],
    execution: "expertise",
    completion: { doneWhen: "The invoice is linked to its work order and PO with the variance computed, or held with a stated reason.", notDoneWhen: "The invoice was matched to a work order that is not yet verified complete and passed on anyway." },
    forbidden: ["match an invoice to a work order at a different property", "pass an invoice over its approved amount without a recorded variance"],
    approvals: ["invoices over the approved amount or tolerance"],
    collaborators: ["maintenance.completion-verification", "spend-vendor.bill-coding", "spend-vendor.approval-routing"],
  },
  {
    id: "spend-vendor.bill-coding",
    name: "Bill Coding",
    domain: "spend-vendor",
    boundary: "Assigns the GL account, property, entity and any capital-versus-expense or owner-chargeable flag to a matched invoice's lines, following the workspace's chart of accounts and coding rules, and prepares the bill. Stops at a coded draft bill; it does not approve or post it.",
    notThis: { specialist: "finance.property-and-entity-allocation", because: "Allocation splits shared costs across properties and entities by rule; bill coding sets the GL account and property on a single vendor bill's lines." },
    triggers: ["gl code", "coding", "chart of accounts", "capex or opex", "which account"],
    inputs: ["matched invoice", "chart of accounts and coding rules", "work order category and property"],
    outputs: ["draft bill with GL, property and entity per line", "capital-versus-expense flag with reason"],
    capabilities: ["invoice.read", "gl.read", "accounting.read", "bill.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Every line of the draft bill has a valid GL account, property and entity, and the bill is queued for approval.", notDoneWhen: "The bill was coded to a suspense or miscellaneous account without a reason." },
    forbidden: ["code a bill into a closed accounting period", "code a cost to a property other than the one the work order names without a recorded allocation"],
    approvals: [],
    collaborators: ["finance.property-and-entity-allocation", "spend-vendor.approval-routing", "finance.general-ledger-review"],
  },
  {
    id: "spend-vendor.approval-routing",
    name: "Approval Routing",
    domain: "spend-vendor",
    boundary: "Sends each PO or bill to the approvers the workspace policy names for its amount, property, category and owner thresholds, tracks each step, and records who approved when. Stops at a fully approved or rejected item; it does not approve anything itself.",
    notThis: { specialist: "maintenance.spend-approval-preparation", because: "Spend approval preparation writes the case for a repair; approval routing applies the approval policy to any PO or bill and records the decisions." },
    triggers: ["approval", "approver", "pending approval", "who needs to sign off", "approval chain"],
    inputs: ["draft PO or bill", "approval policy by amount, property, category and owner", "approver roster"],
    outputs: ["approval chain for the item", "recorded approvals or rejection with time and approver"],
    capabilities: ["bill.read", "invoice.read", "owner.read", "staff.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Every approver the policy requires for the item has recorded an approval, or one has recorded a rejection.", notDoneWhen: "The first approver signed but a required owner or second-level approval is still outstanding." },
    forbidden: ["route an item to its own requester for approval", "skip an approval level the policy requires"],
    approvals: [],
    collaborators: ["owner-services.owner-approval-coordination", "spend-vendor.payment-preparation", "spend-vendor.purchase-order-preparation"],
  },
  {
    id: "spend-vendor.payment-preparation",
    name: "Payment Preparation",
    domain: "spend-vendor",
    boundary: "Assembles approved bills into a proposed payment batch by due date, discount terms and available funds per property, with vendor compliance and duplicate checks, for the controlled payment service. Stops at a prepared batch awaiting release; it never pays.",
    notThis: { specialist: "spend-vendor.approval-routing", because: "Approval routing gets a bill approved; payment preparation turns approved bills into a batch the payment service can release after its own approval." },
    triggers: ["payment run", "pay vendors", "check run", "ach batch", "due bills"],
    inputs: ["approved bills", "vendor remittance and compliance status", "property cash available", "payment calendar"],
    outputs: ["proposed payment batch with totals per property", "bills held with reason: insurance lapsed, missing tax form, insufficient funds or duplicate"],
    capabilities: ["bill.read", "vendor.read", "vendor.insurance.read", "bank.read", "payment.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "A batch of approved bills is prepared with holds explained and is waiting in the payment service for release.", notDoneWhen: "The batch was prepared and treated as paid, or payment was initiated and treated as reconciled." },
    forbidden: ["release or initiate a payment", "include a bill whose vendor remittance details changed since the last payment without recorded verification"],
    approvals: ["release of the payment batch"],
    collaborators: ["spend-vendor.w-9-and-tax-information", "spend-vendor.vendor-insurance-and-coi-compliance", "finance.bank-reconciliation"],
  },
  {
    id: "spend-vendor.contract-expiration-monitor",
    name: "Contract Expiration Monitor",
    domain: "spend-vendor",
    boundary: "Watches vendor service contracts for end dates, auto-renewal notice windows, price-escalation dates and insurance certificate expiries, and alerts the contract owner ahead of each. Stops at the dated alert; renewing, renegotiating or terminating is the owner's decision.",
    notThis: { specialist: "lease-admin.critical-date-tracking", because: "Critical date tracking watches lease dates; this watches vendor service contracts and their notice windows." },
    triggers: ["contract expiring", "auto-renew", "service agreement", "renewal notice", "contract end"],
    inputs: ["vendor contracts with dates and notice terms", "insurance expiry dates", "contract owners"],
    outputs: ["upcoming contract and certificate dates with days remaining", "alerts routed to the contract owner before each notice window"],
    capabilities: ["vendor.read", "document.read", "vendor.insurance.read", "task.route"],
    execution: "deterministic",
    completion: { doneWhen: "Each upcoming date inside the alert horizon has an alert acknowledged by its contract owner before the notice window closes.", notDoneWhen: "An alert was generated but nobody acknowledged it and the auto-renewal window passed." },
    forbidden: ["send a renewal or termination notice to a vendor"],
    approvals: [],
    collaborators: ["spend-vendor.vendor-insurance-and-coi-compliance", "spend-vendor.bid-solicitation", "maintenance.recurring-maintenance"],
  },
  {
    id: "spend-vendor.vendor-performance",
    name: "Vendor Performance",
    domain: "spend-vendor",
    boundary: "Scores each vendor from its own record: acceptance and response times, first-time completion, callbacks, invoice variance and resident feedback, with the work orders behind each figure. Stops at the scorecard; keeping, warning or dropping a vendor is a person's decision.",
    notThis: { specialist: "maintenance.repeat-issue-analysis", because: "Repeat-issue analysis looks for recurring faults in units and equipment; vendor performance measures how each vendor does its work across jobs." },
    triggers: ["vendor scorecard", "vendor performance", "slow vendor", "callbacks", "vendor review"],
    inputs: ["work orders by vendor", "invoice variances", "resident feedback on vendor jobs", "review window"],
    outputs: ["vendor scorecard with the work orders behind each figure", "vendors below the workspace's thresholds"],
    capabilities: ["vendor.read", "work_order.read", "invoice.read", "analytics.read", "report.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Each active vendor has a scorecard for the named window with every figure traceable to work orders or invoices.", notDoneWhen: "A ranking was produced from too few jobs to support it without stating the sample size." },
    forbidden: ["deactivate or suspend a vendor", "score a vendor from comments about the vendor's staff as people rather than the work"],
    approvals: [],
    collaborators: ["maintenance.repeat-issue-analysis", "spend-vendor.vendor-search", "maintenance.maintenance-sla-monitor"],
  },
];
