/** Turns & Make-Ready — 10 Aval Specialists, coordinated by Turns & Make-Ready Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "turns.move-out-scope-intake",
    name: "Move-Out Scope Intake",
    domain: "turns",
    boundary: "Opens the turn record when a move-out is confirmed and attaches what is known: move-out date, move-out inspection findings and photos, finish ages (paint, flooring, appliances) and prior turn history. Stops at an assembled intake; it writes no scope and judges no damage.",
    notThis: { specialist: "turns.turn-scope-creation", because: "Intake gathers the facts about the unit; scope creation turns those facts into the line items of work." },
    triggers: ["move-out", "notice to vacate received", "unit vacated", "start turn", "open turn"],
    inputs: ["notice or move-out record", "move-out inspection", "unit finish ages", "prior turns and work orders"],
    outputs: ["turn record with move-out date", "attached inspection findings, finish ages and history"],
    capabilities: ["lease.read", "turn.read", "inspection.read", "unit.read", "work_order.read"],
    execution: "deterministic",
    completion: { doneWhen: "A turn record exists with the move-out date, the move-out inspection and finish ages attached.", notDoneWhen: "Notice was received but no turn record exists, or the move-out inspection is not attached and the intake is not marked provisional." },
    forbidden: ["classify damage as resident-chargeable", "treat a pre-move-out walk as the move-out inspection without marking the intake provisional"],
    approvals: [],
    collaborators: ["inspections.move-out-inspection", "renewals.non-renewal-handoff", "turns.turn-scope-creation"],
  },
  {
    id: "turns.turn-scope-creation",
    name: "Turn Scope Creation",
    domain: "turns",
    boundary: "Converts the intake into line-item scope under the workspace's turn standard (clean, paint, flooring, repairs, appliances), marking each line as standard turn, damage or capital replacement and naming its trade. Stops at scope; pricing is the budget's job.",
    notThis: { specialist: "turns.turn-budget", because: "Scope creation decides what work the unit needs; the budget prices that work and checks approval thresholds." },
    triggers: ["turn scope", "what does the unit need", "make-ready scope", "scope of work", "full turn or partial"],
    inputs: ["turn intake", "workspace turn standard", "move-out inspection findings"],
    outputs: ["line-item scope with category and trade per line", "items beyond the standard marked for approval"],
    capabilities: ["turn.read", "turn.prepare", "inspection.read", "unit.read", "sop.read"],
    execution: "expertise",
    completion: { doneWhen: "Every inspection finding maps to a scope line or a recorded no-action reason, and each line has a category and trade.", notDoneWhen: "A scope was drafted that leaves inspection findings unaddressed." },
    forbidden: ["scope gas, electrical or structural work as a general turn task instead of a licensed-trade item", "add upgrades beyond the turn standard without marking them for approval"],
    approvals: ["scope items beyond the standard turn"],
    collaborators: ["turns.move-out-scope-intake", "turns.turn-budget", "lease-admin.move-out-obligation-review"],
  },
  {
    id: "turns.turn-budget",
    name: "Turn Budget",
    domain: "turns",
    boundary: "Prices each scope line from the workspace price book, contracted vendor rates or bids, totals the turn and compares it with the turn budget and the owner or workspace approval threshold. Stops at a priced budget with its approval status; it does not buy anything.",
    notThis: { specialist: "turns.turn-cost-variance", because: "The budget prices the turn before work; cost variance compares actual cost with that budget afterwards." },
    triggers: ["turn cost", "turn budget", "how much will the turn cost", "make-ready estimate", "over threshold"],
    inputs: ["turn scope", "price book and vendor rates", "bids", "approval thresholds"],
    outputs: ["priced scope with the price source per line", "total against budget and threshold", "approval request where required"],
    capabilities: ["turn.read", "turn.prepare", "budget.read", "vendor.read"],
    execution: "deterministic",
    completion: { doneWhen: "Every scope line is priced from a cited source and any approval the threshold requires is recorded.", notDoneWhen: "An estimate was produced but the threshold approval it needs is missing." },
    forbidden: ["split one turn's cost into parts to stay under an approval threshold", "price a line from a model estimate where the price book or a bid has a figure"],
    approvals: ["turn budget above the owner or workspace threshold"],
    collaborators: ["turns.turn-scope-creation", "spend-vendor.bid-comparison", "owner-services.owner-approval-coordination", "turns.turn-cost-variance"],
  },
  {
    id: "turns.turn-vendor-and-technician-sequencing",
    name: "Turn Vendor & Technician Sequencing",
    domain: "turns",
    boundary: "Builds the dependency-ordered task plan for a turn (trash-out, repairs, paint, flooring, clean, final) and assigns each task to an in-house technician or a qualified vendor, creating and dispatching the work orders. Stops at accepted assignments; day-to-day execution is a sibling's.",
    notThis: { specialist: "turns.turn-timeline", because: "Sequencing builds and assigns the plan; the timeline tracks the plan against target days and flags slippage." },
    triggers: ["schedule the turn", "assign vendors", "turn plan", "who is painting", "sequence trades"],
    inputs: ["approved scope and budget", "technician availability", "vendors with trade, insurance and licence status"],
    outputs: ["dependency-ordered task plan", "work orders created and dispatched per task", "assignee acceptances"],
    capabilities: ["turn.read", "work_order.create", "vendor.read", "vendor.insurance.read", "vendor.dispatch", "staff.read"],
    execution: "child_run",
    completion: { doneWhen: "Every scope line has a work order in dependency order with an assignee who has accepted it.", notDoneWhen: "Work orders were created or sent but not accepted." },
    forbidden: ["dispatch a vendor whose insurance or licence on record has lapsed for the trade", "schedule a task before the task it depends on is recorded complete"],
    approvals: [],
    collaborators: ["maintenance.technician-assignment", "maintenance.vendor-dispatch", "spend-vendor.vendor-insurance-and-coi-compliance", "turns.turn-timeline", "turns.cleaning-paint-repair-coordination"],
  },
  {
    id: "turns.cleaning-paint-repair-coordination",
    name: "Cleaning/Paint/Repair Coordination",
    domain: "turns",
    boundary: "Runs the day-to-day execution of a turn's cleaning, paint and repair work orders: confirms arrival, clears blockers, checks each task's completion evidence against its scope line and closes the work order once verified. Stops at closed work orders; it does not change scope.",
    notThis: { specialist: "turns.turn-vendor-and-technician-sequencing", because: "Sequencing assigns the tasks; this sees each cleaning, paint and repair task through to verified completion." },
    triggers: ["painter no-show", "cleaning done", "repair complete", "vendor finished", "turn blocker"],
    inputs: ["turn work orders", "scope lines", "completion photos and notes"],
    outputs: ["status per work order with evidence", "verified closures", "blockers raised with owner"],
    capabilities: ["work_order.read", "work_order.update", "work_order.close", "turn.read", "communication.read"],
    execution: "expertise",
    completion: { doneWhen: "Each cleaning, paint and repair work order is closed with evidence matching its scope line.", notDoneWhen: "A vendor reported the work done but the required photos or checks are missing." },
    forbidden: ["close a work order on a vendor's word without the evidence the turn standard requires", "approve extra work found mid-turn without a scope and budget change"],
    approvals: ["extra work found mid-turn"],
    collaborators: ["turns.turn-vendor-and-technician-sequencing", "maintenance.completion-verification", "turns.turn-budget"],
  },
  {
    id: "turns.turn-utility-coordination",
    name: "Turn Utility Coordination",
    domain: "turns",
    boundary: "Makes sure the vacant unit has the electricity, water and gas the turn's trades and final inspection need on the dates they need them, with meter reads at move-out and move-in. Stops at service for the turn; account transfers and billing belong to utilities.",
    notThis: { specialist: "utilities.vacancy-utility-coordination", because: "Vacancy utility coordination owns the account transfer and billing for every vacant unit; this schedules the service the turn's work and inspection depend on." },
    triggers: ["power off in vacant unit", "water shut off", "utilities for turn", "meter read", "no gas for inspection"],
    inputs: ["turn plan and dates", "utility service status for the unit", "move-out and move-in dates"],
    outputs: ["service confirmed for each dependent task date", "meter reads recorded", "requests to utilities for gaps"],
    capabilities: ["utility.read", "utility.prepare", "turn.read", "lease.read"],
    execution: "deterministic",
    completion: { doneWhen: "Service is confirmed for every task and inspection date in the plan, and move-out and move-in meter reads are recorded.", notDoneWhen: "A transfer request was made but service is not confirmed before the dependent task." },
    forbidden: ["let service be shut off in a vacant unit where freeze, mould or inspection risk depends on it", "bill vacancy-period usage to the outgoing or incoming resident"],
    approvals: [],
    collaborators: ["utilities.vacancy-utility-coordination", "utilities.utility-move-in-move-out", "turns.turn-timeline"],
  },
  {
    id: "turns.rent-ready-verification",
    name: "Rent-Ready Verification",
    domain: "turns",
    boundary: "Checks a unit against the rent-ready checklist: final inspection passed, every scope work order closed, keys and access reset, utilities on. Only on a pass does it set the unit rent-ready and notify leasing. Stops at unit status; it does not publish the listing.",
    notThis: { specialist: "turns.cleaning-paint-repair-coordination", because: "That verifies individual trade tasks; this verifies the whole unit against the rent-ready standard and the final inspection." },
    triggers: ["rent ready", "is the unit ready", "final walk", "make-ready complete", "ready to lease"],
    inputs: ["final inspection result", "turn work orders", "key reset record", "utility status"],
    outputs: ["rent-ready pass or the failed items", "unit status update", "notice to leasing"],
    capabilities: ["turn.read", "turn.prepare", "inspection.read", "work_order.read", "key_access.read", "unit.read"],
    execution: "deterministic",
    completion: { doneWhen: "The final inspection passed, all scope work orders are closed, access is reset, the unit is rent-ready and leasing is notified.", notDoneWhen: "The last vendor finished but the final inspection has not passed." },
    forbidden: ["count a checklist item as passed when its photo or inspection entry is missing", "set rent-ready while a scope work order is open"],
    approvals: [],
    collaborators: ["inspections.inspection-scheduling", "inspections.inspection-deficiency-triage", "turns.key-and-access-reset", "leasing-marketing.listing-readiness"],
  },
  {
    id: "turns.turn-timeline",
    name: "Turn Timeline",
    domain: "turns",
    boundary: "Tracks each active turn against its target days vacant along the dependency plan's critical path, flags a slipping task early with its cause, and keeps leasing's expected ready date current. Stops at the projection and flags; it does not reassign work.",
    notThis: { specialist: "turns.turn-vendor-and-technician-sequencing", because: "Sequencing makes the plan and assigns it; the timeline measures the plan against target and reports slippage." },
    triggers: ["turn status", "when will it be ready", "days vacant", "turn delayed", "ready date"],
    inputs: ["turn plan", "work order status", "target days vacant"],
    outputs: ["projected ready date per turn", "slipping tasks with cause and owner", "ready date shared with leasing"],
    capabilities: ["turn.read", "work_order.read", "report.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Every active turn has a current projected ready date and each slipping task has a cause and an owner.", notDoneWhen: "A status report was produced while late tasks are unassigned." },
    forbidden: ["give leasing a ready date the dependency plan does not support", "reset a target date to hide slippage"],
    approvals: [],
    collaborators: ["turns.turn-vendor-and-technician-sequencing", "leasing-marketing.listing-readiness", "portfolio-strategy.occupancy-and-vacancy-analysis"],
  },
  {
    id: "turns.key-and-access-reset",
    name: "Key & Access Reset",
    domain: "turns",
    boundary: "Resets every access point for the unit between residents: rekeys or re-cores locks, reprograms fobs, garage, mailbox and smart-lock codes, revokes the outgoing resident's credentials and records the new set. Stops at a reset unit; handing keys to a new resident is move-in's job.",
    notThis: { specialist: "property-operations.key-and-access-inventory", because: "Inventory keeps the property's master key and fob record; the reset changes one unit's access between residents and updates that record." },
    triggers: ["rekey", "change locks", "reset codes", "keys not returned", "fob deactivate"],
    inputs: ["unit access points", "outgoing keys returned", "access device records"],
    outputs: ["rekey or reprogram work orders", "outgoing credentials revoked", "new key and code set recorded"],
    capabilities: ["key_access.read", "turn.read", "unit.read", "work_order.create"],
    execution: "deterministic",
    completion: { doneWhen: "Every access point is changed or verified, outgoing credentials are revoked, and the new set is in the inventory.", notDoneWhen: "A rekey work order was created but not completed, or outgoing credentials are still active." },
    forbidden: ["reuse the outgoing resident's codes or keep a lock whose keys are unaccounted for", "write access codes in messages or free-text notes"],
    approvals: [],
    collaborators: ["property-operations.key-and-access-inventory", "turns.rent-ready-verification", "leasing-marketing.self-guided-tour-coordination"],
  },
  {
    id: "turns.turn-cost-variance",
    name: "Turn Cost Variance",
    domain: "turns",
    boundary: "After a turn, compares actual cost from matched invoices, bills and in-house labour with the approved budget line by line, explains each variance above threshold and feeds the price book. Stops at the variance record; it does not change coding or approvals.",
    notThis: { specialist: "turns.turn-budget", because: "The budget prices the turn before work; cost variance measures what it actually cost against that budget." },
    triggers: ["turn over budget", "turn actuals", "cost variance", "what did the turn cost", "price book update"],
    inputs: ["approved turn budget", "matched invoices and bills", "in-house labour records", "variance threshold"],
    outputs: ["actual against budget by line", "explained variances above threshold", "price book update proposals"],
    capabilities: ["turn.read", "invoice.read", "budget.read", "report.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Each completed turn has actual against budget by line with every variance above threshold explained.", notDoneWhen: "Variance was computed before all the turn's invoices were matched." },
    forbidden: ["count an unmatched or unapproved invoice as an actual turn cost", "move cost between turns or to capital to shrink a variance"],
    approvals: [],
    collaborators: ["spend-vendor.invoice-work-order-matching", "turns.turn-budget", "finance.budget-vs-actual"],
  },
];
