/** Utilities, Sustainability & Building Systems — 10 Aval Specialists, coordinated by Utilities, Sustainability & Building Systems Lead. */
import type { SpecialistDefinition } from "../types.ts";

export const SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "utilities.utility-account-setup",
    name: "Utility Account Setup",
    domain: "utilities",
    boundary: "Builds the utility account register for a property: provider, service type, account and meter numbers, which unit or common area each serves, and who holds the account. Stops at an accurate register and the setup requests it needs; it does not audit bills or bill residents.",
    notThis: { specialist: "utilities.utility-move-in-move-out", because: "Move-in/move-out transfers service for one unit at a change of occupancy; account setup builds the property's standing register of accounts and meters." },
    triggers: ["utility account", "new property utilities", "meter number", "set up service", "house meter", "account holder"],
    inputs: ["property and unit list", "provider bills and account documents", "meter locations"],
    outputs: ["utility account register mapping accounts and meters to units and common areas", "setup or transfer requests prepared for unassigned services"],
    capabilities: ["property.read", "unit.read", "utility.read", "utility.bill.read", "document.extract", "utility.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Every meter and account at the property maps to a unit or common area and a named account holder.", notDoneWhen: "Accounts were listed from bills but meters remain unmapped to units or common areas." },
    forbidden: ["open or close a provider account in the owner's or a resident's name without authorization on record"],
    approvals: ["new utility accounts opened in the owner's name"],
    collaborators: ["property-operations.property-setup", "utilities.utility-bill-audit", "data-integrations.document-ingestion"],
  },
  {
    id: "utilities.utility-bill-audit",
    name: "Utility Bill Audit",
    domain: "utilities",
    boundary: "Checks each provider bill against the account register and history: correct account and meter, rate class, billing-period gaps or overlaps, estimated reads, late fees and arithmetic, and lists the errors with the amount at stake. Stops at the audit result; disputing with the provider or paying is not its job.",
    notThis: { specialist: "utilities.leak-and-usage-anomaly", because: "Anomaly detection looks for physical causes such as leaks in usage; the bill audit looks for billing errors in what the provider charged." },
    triggers: ["utility bill", "water bill", "electric bill", "estimated read", "rate class", "overbilled"],
    inputs: ["provider bills", "utility account register", "prior billing history and rate schedules"],
    outputs: ["audit result per bill with errors and amount at stake", "bills cleared for payment preparation"],
    capabilities: ["utility.read", "utility.bill.read", "invoice.read", "document.extract"],
    execution: "deterministic",
    completion: { doneWhen: "Every bill for the period has an audit result, and each error names its amount and evidence.", notDoneWhen: "Bills were forwarded for payment without the period-overlap and estimated-read checks." },
    forbidden: ["pay or schedule payment of a utility bill", "contact a provider to dispute a bill without an authorized request"],
    approvals: ["billing disputes to raise with the provider"],
    collaborators: ["spend-vendor.invoice-intake", "utilities.leak-and-usage-anomaly", "finance.financial-anomaly-detection"],
  },
  {
    id: "utilities.resident-utility-billing",
    name: "Resident Utility Billing",
    domain: "utilities",
    boundary: "Calculates each resident's utility charge from submeter reads or the allocation method the lease and jurisdiction allow, such as RUBS, and prepares the charges for posting. Stops at prepared charges with the calculation shown; it does not post them or message residents.",
    notThis: { specialist: "utilities.submeter-exception", because: "Submeter exception resolves bad or missing reads; resident utility billing turns valid reads or an allowed allocation into charges." },
    triggers: ["rubs", "utility charge", "submeter billing", "bill back", "water charge", "resident utilities"],
    inputs: ["submeter reads or allocation inputs", "lease utility clause", "jurisdiction utility-billing rule", "provider bill totals"],
    outputs: ["prepared utility charges per resident with the calculation", "residents excluded for missing lease basis"],
    capabilities: ["utility.read", "utility.bill.read", "lease.read", "compliance.read", "charge.prepare"],
    execution: "deterministic",
    completion: { doneWhen: "Each resident charge is prepared with its lease basis, method and calculation, and total allocated does not exceed the provider bills.", notDoneWhen: "Charges were calculated but some residents lack a lease utility clause and were billed anyway." },
    forbidden: ["allocate more than the provider actually billed", "add an admin fee the lease and jurisdiction do not permit", "use an allocation method the jurisdiction prohibits"],
    approvals: ["the utility charge batch before posting"],
    collaborators: ["receivables.rent-charge-schedule", "utilities.submeter-exception", "affordable.utility-allowance-tracking"],
  },
  {
    id: "utilities.vacancy-utility-coordination",
    name: "Vacancy Utility Coordination",
    domain: "utilities",
    boundary: "Keeps utilities running in the owner's name for vacant units so the unit stays safe and workable, and watches vacant-unit consumption for surprises. Stops at service continuity and usage flags; move-out and move-in transfers belong to another specialist.",
    notThis: { specialist: "turns.turn-utility-coordination", because: "Turn utility coordination gets utilities on for make-ready work on a turn's timeline; this keeps any vacant unit's service in place and watches its usage between tenancies." },
    triggers: ["vacant unit utilities", "vacancy", "owner's name", "revert to owner", "empty unit power"],
    inputs: ["vacant units", "utility account register", "vacant-unit meter reads and bills"],
    outputs: ["vacant units confirmed in service under the owner", "vacant units with unexpected consumption"],
    capabilities: ["occupancy.read", "utility.read", "utility.bill.read", "utility.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Every vacant unit has confirmed service in the owner's name and a usage check for the period.", notDoneWhen: "A revert-to-owner request was sent but the provider has not confirmed the change." },
    forbidden: ["let service to a vacant unit lapse where heat or freeze protection depends on it"],
    approvals: [],
    collaborators: ["turns.turn-utility-coordination", "utilities.leak-and-usage-anomaly", "property-operations.occupancy-state-coordination"],
  },
  {
    id: "utilities.submeter-exception",
    name: "Submeter Exception",
    domain: "utilities",
    boundary: "Finds and resolves submeter read problems: missing, zero, negative, stuck, rolled-over or implausible reads and meter-to-unit mismatches, and requests re-reads or meter service. Stops at a clean or explicitly estimated read set; it does not calculate charges.",
    notThis: { specialist: "utilities.leak-and-usage-anomaly", because: "Leak detection interprets a valid but unusual read as a possible physical problem; submeter exception deals with reads that are wrong or missing." },
    triggers: ["zero read", "missing read", "submeter", "meter mismatch", "stuck meter", "read exception"],
    inputs: ["submeter read file", "meter-to-unit map", "read history"],
    outputs: ["exception list with the rule each read failed", "re-read or meter service requests", "resolved read set with estimates marked"],
    capabilities: ["utility.read", "unit.read", "work_order.create"],
    execution: "deterministic",
    completion: { doneWhen: "Every read in the period is valid, re-read or explicitly marked estimated with the method, before billing uses it.", notDoneWhen: "Exceptions were listed and billing went ahead on the unresolved reads." },
    forbidden: ["replace a failed read with an estimate without marking it estimated"],
    approvals: [],
    collaborators: ["utilities.resident-utility-billing", "utilities.leak-and-usage-anomaly", "maintenance.work-order-creation"],
  },
  {
    id: "utilities.energy-and-water-usage-analysis",
    name: "Energy & Water Usage Analysis",
    domain: "utilities",
    boundary: "Analyses a property's energy and water use over time, normalized for weather and occupancy where data allows, compares it with the property's own history and peers in the portfolio, and names savings opportunities. Stops at the analysis; it does not start projects or change systems.",
    notThis: { specialist: "utilities.sustainability-reporting", because: "Usage analysis is operational, finding where use can fall; sustainability reporting packages consumption and emissions for owners, lenders or regulators." },
    triggers: ["energy use", "water use", "consumption", "savings", "benchmark usage", "efficiency"],
    inputs: ["utility bills and interval data", "occupancy by period", "weather data where available"],
    outputs: ["usage trend per property and system with normalization stated", "savings opportunities with the evidence behind each"],
    capabilities: ["utility.read", "utility.bill.read", "occupancy.read", "sustainability.read", "analytics.read"],
    contextOnly: ["sustainability.read"],
    execution: "expertise",
    completion: { doneWhen: "The analysis names its window, normalization and data sources, and each opportunity cites the usage it rests on.", notDoneWhen: "A savings figure was estimated without stating the baseline or assumptions." },
    forbidden: ["state a savings figure as expected when it is an estimate from assumptions"],
    approvals: [],
    collaborators: ["utilities.sustainability-reporting", "maintenance.preventive-maintenance", "portfolio-strategy.capex-planning"],
  },
  {
    id: "utilities.leak-and-usage-anomaly",
    name: "Leak & Usage Anomaly",
    domain: "utilities",
    boundary: "Flags water, gas or electric use that departs from a meter's own baseline, such as continuous overnight flow or a vacant unit drawing load, and turns each flag into a maintenance request to investigate. Stops at the flag and the request; it does not diagnose a leak.",
    notThis: { specialist: "utilities.utility-bill-audit", because: "The bill audit checks that the provider charged correctly; anomaly detection checks whether usage points to a physical problem on site." },
    triggers: ["leak", "spike", "high usage", "continuous flow", "running toilet", "usage anomaly"],
    inputs: ["meter reads or interval data", "meter baselines", "occupancy status"],
    outputs: ["anomaly flags with the reads behind them", "maintenance requests opened to investigate"],
    capabilities: ["utility.read", "occupancy.read", "maintenance.request.create"],
    execution: "deterministic",
    completion: { doneWhen: "Each anomaly above threshold has a maintenance request linked to it.", notDoneWhen: "An anomaly was reported in a summary but no maintenance request was opened." },
    forbidden: ["tell a resident or owner there is a leak before anyone has inspected", "shut off a service"],
    approvals: [],
    collaborators: ["maintenance.service-request-intake", "maintenance.emergency-maintenance-triage", "utilities.vacancy-utility-coordination"],
  },
  {
    id: "utilities.sustainability-reporting",
    name: "Sustainability Reporting",
    domain: "utilities",
    boundary: "Prepares energy, water, waste and emissions reports for owners, lenders, benchmarking ordinances or ESG frameworks, from metered and billed data with coverage and estimation stated. Stops at the prepared report; submission to a regulator or framework is for an authorized person.",
    notThis: { specialist: "utilities.energy-and-water-usage-analysis", because: "Usage analysis finds operational savings; sustainability reporting assembles the figures a specific reporting requirement asks for, with coverage and method stated." },
    triggers: ["esg", "benchmarking", "energy star", "emissions", "sustainability report", "ordinance"],
    inputs: ["utility and waste data by property", "reporting requirement and deadline", "data coverage by meter"],
    outputs: ["prepared sustainability report with data coverage and estimation method", "list of missing meters or periods"],
    capabilities: ["utility.read", "utility.bill.read", "sustainability.read", "compliance.read", "report.prepare"],
    execution: "expertise",
    completion: { doneWhen: "The report is prepared for the named requirement with coverage stated and handed to an authorized submitter before the deadline.", notDoneWhen: "The report was drafted with estimated periods not marked as estimated." },
    forbidden: ["submit a report to a regulator or framework", "present estimated consumption as metered"],
    approvals: ["the report before submission"],
    collaborators: ["risk-compliance.regulatory-calendar", "utilities.energy-and-water-usage-analysis", "owner-services.property-performance-brief"],
  },
  {
    id: "utilities.waste-and-service-coordination",
    name: "Waste & Service Coordination",
    domain: "utilities",
    boundary: "Coordinates trash, recycling, compost and bulk pickup and other building service schedules with the service providers, and handles missed pickups, overflow and container changes. Stops at the service being scheduled or restored; the vendor contract itself is spend-vendor's.",
    notThis: { specialist: "spend-vendor.contract-expiration-monitor", because: "The contract monitor watches the service agreement's dates; this handles the day-to-day pickups, missed services and container changes under it." },
    triggers: ["trash", "recycling", "missed pickup", "dumpster", "bulk item", "compactor"],
    inputs: ["service schedules by property", "reports of missed or overflowing service", "provider contacts"],
    outputs: ["service requests sent to the provider", "missed-service log with resolution"],
    capabilities: ["property.read", "vendor.read", "communication.read", "communication.send"],
    execution: "expertise",
    completion: { doneWhen: "The missed or changed service has a provider confirmation and the pickup has happened.", notDoneWhen: "A request was sent to the provider and treated as the pickup having happened." },
    forbidden: ["order extra pickups or container changes that add cost above the spend threshold without approval"],
    approvals: ["service changes that add recurring cost"],
    collaborators: ["spend-vendor.contract-expiration-monitor", "property-operations.daily-operations-queue", "utilities.sustainability-reporting"],
  },
  {
    id: "utilities.utility-move-in-move-out",
    name: "Utility Move-In/Move-Out",
    domain: "utilities",
    boundary: "Transfers utility responsibility at a change of occupancy: confirms the incoming resident has service in their name by the lease date where the lease requires it, records final reads, and reverts service to the owner at move-out. Stops at confirmed transfers and recorded reads.",
    notThis: { specialist: "property-operations.move-in-move-out-coordination", because: "Move-in/move-out coordination runs the whole occupancy change; this handles only the utility transfers and final reads within it." },
    triggers: ["transfer utilities", "utilities in resident name", "final read", "move-in utilities", "move-out utilities"],
    inputs: ["move-in and move-out dates", "lease utility responsibilities", "utility account register"],
    outputs: ["confirmed utility transfers per service", "final meter reads recorded", "residents missing proof of service"],
    capabilities: ["lease.read", "utility.read", "utility.prepare", "resident.message.prepare"],
    execution: "expertise",
    completion: { doneWhen: "Each service at the unit has a confirmed holder for the new occupancy and final reads are recorded for the old one.", notDoneWhen: "The resident was told to set up utilities but no proof of service was received." },
    forbidden: ["put a service in a resident's name on their behalf without their authorization"],
    approvals: [],
    collaborators: ["property-operations.move-in-move-out-coordination", "utilities.vacancy-utility-coordination", "resident-experience.move-in-onboarding"],
  },
];
